# Neuromuscular Blockers

:::dual
Understanding of the pharmacology of neuromuscular blocking drugs
:::

The neuromuscular junction is a **chemical communication** between the motor neuron and the muscle cell, and relies upon:

* Release of ACH-containing vesicles from the motor nerve in response to influx of Ca^2+^
* Binding of ACh to nicotinic ACh receptors on the muscle cell\
Neuromuscular blockers generally act here, by antagonising the action of ACh.

:::column-margin
Nicotinic ACh receptors sit on the shoulders of junctional folds of muscle cells, whilst acetylcholinesterase is buried in the clefts.
:::

## Factors Affecting Neuromuscular Blockade

### Patient Factors

+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Factor                          | Effect                                        | Mechanism                                                                              |
+=================================+===============================================+========================================================================================+
| Hepatic Disease                 | ↑ Duration of aminosteroids and suxamethonium | ↓ Metabolism\                                                                          |
|                                 |                                               | ↓ Production of pseudocholinesterase in severe disease                                 |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Pseudocholinesterase deficiency | ↑ Duration of suxamethonium                   | ↓ Metabolism                                                                           |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Age                             | ↑ Sensitivity in neonates\                    | Incomplete maturation of NMJ                                                           |
|                                 | Particularly premature infants.               |                                                                                        |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Hypokalaemia                    | Potentiates non-depolarising blockade\        | ↑ Depolarisation threshold                                                             |
|                                 | Inhibits depolarising blockade                |                                                                                        |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Hyperkalaemia                   | Potentiates depolarising blockade\            | ↓ Depolarisation threshold                                                             |
|                                 | Inhibits non-depolarising blockade            |                                                                                        |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Hypermagnesaemia                | Potentiates blockade                          | ↓ ACh release\                                                                         |
|                                 |                                               | ↓ Sensitivity of post-synaptic membrane                                                |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Hypocalcaemia                   | Potentiates blockade                          | ↓ Presynaptic ACH release\                                                             |
|                                 |                                               | ↓ Sensitivity of post-synaptic membrane                                                |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Respiratory acidosis            | Potentiates blockade                          | Enhances effect of NMB agents                                                          |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Hypothermia                     | Potentiates blockade                          | ↓ Hepatic metabolism\                                                                  |
|                                 |                                               | ↓ Renal elimination\                                                                   |
|                                 |                                               | ↓ Hoffman degradation                                                                  |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Hypovolaemia                    | ↓ Rate of block onset\                        | Prolonged circulation time                                                             |
|                                 | ↑ Duration of block                           |                                                                                        |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Myasthenia Gravis               | ↑ Sensitivity to non-depolarising agents      | Autoimmune blockade of receptors gives pre-existing level of block                     |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+
| Eaton-Lambert Syndrome          | ↑ Sensitivity to all NMBs                     | Autoimmune destruction of voltage-gated Ca^2+^ channels prevent ACh vesicle exocytosis |
+---------------------------------+-----------------------------------------------+----------------------------------------------------------------------------------------+

:::column-margin
Depolarisation threshold refers to the magnitude of stimulus required to depolarise cell.
:::

### Drug Factors

+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Drugs                     | Effect                            | Mechanism                                                          |
+===========================+===================================+====================================================================+
| Frusemide                 | Potentiates blockade at low dose\ | Inhibits protein kinases (reducing AMP/ATP synthesis) at low dose\ |
|                           | Inhibits blockade at high dose    | Inhibits PDE at high doses, which ↑ ACh release                    |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Inhalational anaesthetics | Potentiates blockade              | Stabilise post-junctional membrane\                                |
|                           |                                   | Presynaptic ACh receptor blockade                                  |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Antibiotics               | Potentiates blockade              | Aminoglycosides and tetracyclines prolong blockade                 |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Local anaesthetics        | Potentiates blockade              | ↓ ACh release\                                                     |
|                           |                                   | Stabilises post-junctional membrane                                |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Anticholinesterases       | Inhibits blockade                 | ↑ ACh levels at the NMJ by ↓ ACh breakdown                         |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| OCP                       | Potentiates depolarising blockade | Competes for binding sites on plasma cholinesterases               |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Ca^2+^-channel blockers   | Potentiates blockade              | Inhibit Ca^2+^ dependent ACh release                               |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+
| Lithium                   | Potentiates blockade              | Augments action of NMBs                                            |
+---------------------------+-----------------------------------+--------------------------------------------------------------------+

### Additional Factors Affecting Onset of Neuromuscular Blockade

+-----------------------------+--------------------------------------------+---------------------------------------------------------------------------------+
| Factor                      | Effect                                     | Mechanism                                                                       |
+=============================+============================================+=================================================================================+
| **Potency**                 | Low potency decreases time to onset        | Bowman's principle                                                              |
+-----------------------------+--------------------------------------------+---------------------------------------------------------------------------------+
| **Dose**                    | Increased dose decreases time to onset     | Greater concentration gradient                                                  |
+-----------------------------+--------------------------------------------+---------------------------------------------------------------------------------+
| **Cardiac Output**          | High output decreases time to onset        | Increased drug delivery                                                         |
+-----------------------------+--------------------------------------------+---------------------------------------------------------------------------------+
| **Muscle group blood flow** | High muscular flow decreases time to onset | Increased drug delivery                                                         |
+-----------------------------+--------------------------------------------+---------------------------------------------------------------------------------+
| **Priming Principle**       | (May) decrease time to onset               | Pre-induction blockade of a portion of ACh receptors using a sub-paralytic dose |
+-----------------------------+--------------------------------------------+---------------------------------------------------------------------------------+

:::column-margin
Most additional factors affecting the onset of blockade can be directly attributed to **Fick's Law**:
:::

:::column-margin
**Bowman's principle** describes the relationship between dose and potency. In brief: Less potent drugs must be administered in higher doses to have their clinical effect, and so have a greater concentration gradient driving diffusion to the effect site.
:::

:::column-margin
A 'priming' dose of non-depolarising blocker should occupy <70% of ACh receptors, and so should not cause significant neuromuscular blockade in the awake patient.\
\
After induction, a second dose is given to occupy the remaining receptors and complete blockade.
:::

---

## References

1. Sterling E, Winstead PS, Fahy BG. [Guide to Neuromuscular Blocking Agents](http://www.anesthesiologynews.com/download/ANSE07_NeuroblockERWM.pdf). 2007. Anesthesiology News. 
2. ICU Adelaide. [Neuromuscular Blockers](https://icuadelaide.com.au/files/primary/pharmacology/neuromuscular.pdf).
3. Pino RM. [Revisiting the Priming Principle for Neuromuscular Blockers: Usefulness for Rapid Sequence Inductions](http://austinpublishinggroup.com/anesthesia-analgesia/fulltext/ajaa-v2-id1030.php). Austin J Anesthesia and Analgesia. 2014;2(5): 1030.
4. ANZCA February/April 2011