# Skeletal Muscle Innervation

:::CICM
Explain the concept of motor units
\
\
Describe the monosynaptic stretch reflex, single twitch, and tetanus
:::


## Motor Units

A motor unit consists of an α-motor neuron and the group of muscle cells that it innervates:

* An action potential in this neuron will cause contraction of all the myocytes in the unit
* Large muscles have many myocytes per unit
* Small, precise muscles (e.g. extraocular) have few myocytes per unit

## Force of Contraction

Muscle tension is dependent on three factors:

* **Initial myocyte fibre length**\
Optimal stretch maximises the number of overlapping actin and myosin filaments.
* **Number of contracting myocytes**\
Recruitment of additional motor units increases the force of contraction.
* **Frequency of Action Potentials**\
High frequency action potentials cause accumulation of calcium in the cytoplasm (the Bowditch or Treppe effect), increasing force of contraction.
    * As the absolute refractory period of skeletal muscle is shorter than cardiac muscle, **tetany**, or sustained muscle contraction, can occur

## Proprioception

Proprioception is the ability of the body to determine it's position in space. There are two key proprioceptive sensors:

* Muscle spindles
* Golgi tendon organs

### Muscle Spindles

Muscle spindles sense **changes in muscle length**. They:

* Are a specialised muscle fibre, known as **intrafusal fibres**
* Run **parallel** to myocytes (also known as **extrafusal fibres**)
* Consist of two elements:
    * Central, non-contractile portion which senses tension
    * Contractile ends\
    This allows the muscle spindle to adjust its length with its muscle, so that a constant tension in the non-contractile portion can be maintained over a range of muscle lengths.
* **Have** both **afferent** and **efferent innervation**:
    * Afferent type Ia fibres adjust their electrical output to signal both current fibre length and rate of change
    * Afferent type II fibres only signal fibre length
    * Efferent γ neurons innervate the contractile elements

:::column-margin
Voluntary muscle contraction results in contraction of both motor units (α1 neurons) and intrafusal fibres (γ-motor neurons).
\
\
Tonic innervation of γ-motor neurons increases muscle tone by stretching the non-contractile portions, increasing Ia firing and subsequent α-motor unit firing.
:::

### Golgi Tendon Organs

Golgi tendon organs are stretch receptors located between muscle and tendon. They:

* Run **in series** to myocytes
* Sense stretch
* Cause reflexive muscle **relaxation**, intended to prevent muscle damage

## Reflexes

A reflex is an **involuntary, predictable movement in response to a stimulus**. There are two types:

* **Monosynaptic**\
Motor neuron synapses directly with the sensory neuron. Monosynaptic reflexes:
    * Are **rapid**
    * Generate **simple** responses
    * Have **five components**:
        * Sensory receptor\
        Typically muscle spindles.
        * Afferent neuron\
        Type Ia afferents relay signal from muscle spindle to ventral horn via the dorsal root.
        * Synapse between afferent and efferent neuron\
        In the ventral horn
        * Efferent neuron\
        α-motor neuron travels from the ventral horn and innervates the motor unit.
        * Effector muscle
        Innervated motor unit contracts in response.
* **Polysynaptic**\
Motor neuron is separated from the sensory neuron by one or more interneurons in the dorsal horn. Polysynaptic reflexes:
    * Can be **modulated**\
    Interneuron activity can adjust reflex response.
    * **Slower**
    * More **complex**\
    e.g. Withdrawal of a limb from a hot object.


## Twitch and Tetany

* A **twitch** is the response of a muscle to a **single stimulus** (action potential)
* A **tetanic** contraction describes the sustained contraction produced by **repetitive stimulation** before relaxation can occur
  * This stimulation must be causing  above a **critical frequency**, which is dependent on the action potential duration for a cell
  * Repetitive stimulation causes repeated SR depolarisation, leading to sustained high intracellular Ca^2+^ levels as Ca^2+^ entry exceeds Ca^2+^ exit
  * Force from tetanic contraction is up to 4x greater than that of a twitch

---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
2. ANZCA March/April 2000