# Antiemetics


Antiemetic drugs can be classified by their mechanism of action:

* Serotonin antagonists
    * Ondansetron
* Corticosteroids
    * Dexamethasone\
    Has additional effects on postsurgical pain and fatigue.
* Dopamine antagonists
    * Phenothiazines
        * Chlorpromazine
        * Prochlorperazine
    * Butyrophenones
        * Droperidol
    * Benzamides
        * Metoclopramide
* Anticholinergics
    * Hyoscine
    * Atropine
* Antihistamines
    * Cyclizine
* NK~1~ antagonists
    * Aprepitant
* Others
    * Benzodiazepines
    * Cannabinoids
    * Propofol

## Comparison of Antiemetic Drugs

|Property|Ondansetron|Droperidol|Metoclopramide|Cyclizine
|--|--|
|**Class**|Serotonin antagonist|Benzamide dopamine antagonist|Dopamine antagonist|Piperazine derivative/H~1~ antagonist|
|**Uses**|Nausea. Ineffective for vomiting due to motion sickness or dopamine agonism|Antiemetic, sedation, behavioural control|Prokinetic, antiemetic|Antiemetic (including motion sickness and radiation sickness)
|**Presentation**|Tablet, wafer, clear solution for injection at 4mg.ml^-1^|Clear solution in brown glass, incompatible with thiopentone and methohexital|Clear solution in plastic|50mg tablets or 50mg.ml^-1^ light-sensitive solution
|**Route of Administration**|PO/SL/IV|IV|IV/PO|PO/IV/IM
|**Dosing**|4-8mg TDS <br>Give on induction for PONV|IV<br>Give at end of surgery for PONV|25-50mg IV (note 10mg has no antiemetic properties|1mg.kg^-1^ up to 150mg per day
|**Absorption**|PO bioavailability 60%||PO bioavailability 30-90%|PO bioavailability 80%
|**Distribution**|75% protein bound|90% protein bound, V~D~ 2L.kg^-1^|Minimal protein binding, V~D~ ~3L.kg^-1^||
|**Metabolism**|Hepatic to inactive metabolites. Dose reduction in hepatic impairment. t~1/2~ 3/24.|Extensive hepatic metabolism|Hepatic metabolism|Hepatic to inactive metabolites|
|**Elimination**|Renal elimination of inactive metabolites|Renal and hepatic of drug and metabolites|Renal of 20% unchanged drug and remainder as metabolites|Renal of metabolites|
|**Mechanism of Action**|Central and peripheral antagonism of 5-HT~3~ receptors, reducing input to the vomiting centre|Central D~2~ blockade and post-synaptic GABA antagonism|Antiemetic activity via central D~2~ antagonism, prokinetic activity via muscarinic agonism, peripheral D~2~ antagonism|Competitive H~1~ antagonist and anticholinergic at M~1~, M~2~, M~3~ receptors
|**CVS**|Bradycardia with rapid IV administration, QT prolongation|QT prolongation, hypotension secondary to α antagonism|↑/↓ HR, ↑/↓ BP|↑ HR and ↓ BP due to α antagonism
|**CNS**|Headache|Sedation (neurolepsis), extrapyramidal symptoms in ~1%|Extrapyramidal symptoms, neuroleptic malignant syndrome|Sedation|
|**GIT**|Constipation|Antiemetic|Antiemetic, prokinetic|Increased LoS tone|
|**Endocrine**|||Hyperprolactinaemia||


---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Sébastien Pierre, MD, Rachel Whelan. [Nausea and Vomiting After Surgery](https://academic.oup.com/bjaed/article/13/1/28/281153/Nausea-and-vomiting-after-surgery). Contin Educ Anaesth Crit Care Pain 2013; 13 (1): 28-32. doi: 10.1093/bjaceaccp/mks046
3. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.