# Electrical Safety

:::CICM
Explain the electrical concepts of current, potential difference, resistance, impedance, inductance, capacitance, frequency, and amplitude as they relate to biological signals and biomedical apparatus.
:::

:::ANZCA
Describe basic physics applicable to anaesthesia, in particular electrical concepts, current, potential difference, resistance, impedance, inductance and capacitance.
:::

Key electrical concepts include:

* **Charge**\
The property of a subatomic particle which causes it to experience a force when close to other charged particles. Charge is measured in coulombs (C).
* **Current**\
The flow of electrons through a conductor. Current is measured in amps (A).
* **Voltage**\
The strength of the force that causes movement of electrons.
    * By tradition, voltages are quoted relative to **ground** (or **earth**)
        * If a potential difference exists, a current will flow from that object to the earth via the path of least resistance
        * If this path contains a person, an electrical injury may result.
* **Resistance**\
Describes to what extent a substance reduces the flow of electrons through it. Resistance is measured in ohms (Ω).
    * Substances with **high resistance** are **insulators**
    * Substances with **low resistance** are **conductors**
* **Inductance**\
Property of a conductor by which a change in current induces an electromotive force in the conductor, and any nearby conductors
* **Capacitance**\
Ability of an object to store electrical charge. Measured in Farads (F), where one farad is when one volt across the capacitor stores one coulomb of charge.
    * A capacitor is an electrical component consisting of two conductors separated by an insulator (called a dielectric)
    * When a **direct current** flows, electrons (a negative charge) build up on one of these conductors (called a plate), whilst an electron deficit (positive charge) occurs on the other plate
        * Current will flow until the build up of charge is equal to the voltage of the power source
        * Current can be **rapidly discharged** when the circuit is changed
    * An **alternating current** can flow freely across a capacitor, and causes no buildup of charge
* **Impedance**\
Describes to what extent the flow of **alternating current** is reduced when passing through a substance.
    * Impedance can be conceptualised as 'resistance for AC circuits', and is a combination of **resistance** and **reactance**.
    * Reactance is a function of two things:
        * Induction of voltage in conductors by the alternating magnetic field of AC flow
        * Capacitance induced by voltages between these conductors


## Electrical Injury

Potential electrical injuries include:

* **Ventricular Fibrillation** secondary to **electrical shock**\
Likelihood is a function of:
    * Current density
    * Frequency\
    Lowest current density required is at **50Hz**.
* **Burns**\
Function of current density. Burns typically occur at the entry and exit point as this is where current density is highest.
* **Tetanic Contraction**\
Flexors are stronger than extensors, which may maintain grip on live wire. Death may result from either VF or asphyxiation from sustained respiratory muscle contraction.


### Electrical Shock

Electrical shocks are divided into two types, based on their ability to induce VF:

* **Microshock**\
Current required to induce VF when applied directly to myocardium.
    * Typical current is **0.05-0.1mA**
    * This requires **skin breach**\
    Potential causes:
        * Guidewire
        * Pacing lead
        * Column of conducting fluid
        * CVC
        * PICC
* **Macroshock**\
Current required to induce VF from surface contact.
    * Typical current is **100mA**
    * This is much higher than microshock because most of this current is not going to the ventricle, and so the total current must be greater to achieve sufficient **current density** in the myocardium to induce VF

:::column-margin
A variety of other detrimental effects can be seen at lower currents.

: Adverse Effects of Electrocution

| Current (mA) | Effect                                         |
|--------------|------------------------------------------------|
| 1            | Tingling                                       |
| 5            | Pain                                           |
| 8            | Burns                                          |
| 15           | Skeletal muscle tetany                         |
| 50           | Skeletal muscle paralysis & respiratory arrest |
:::


## Principles of Electrical Safety

Power points contain three terminals:

* **Active**\
240V in Australia and New Zealand.
* **Neutral**\
0V, relative to ground.
* **Earth**\
Direct pathway into ground.

:::column-margin
Note that measuring voltage for AC current is not intuitive, as the voltage will be negative half the time. The **root mean square** (RMS) is used instead - each value for the voltage is squared (giving a positive number), and then divided by the number of samples to give an average.
:::

An electrical circuit is completed between an appliance and the power station by returning current to the station via the earth. This is an **earth referenced power supply**.


### Electrical Dangers

Electrical risks include:

* **Shorting**\
Active wire connected to some other part of the equipment (e.g. case), resulting in electrical current traveling through components that it was not designed to.
    * Principle of earth wire, which provides path of least resistance for current to travel should a short occur
    * Earthing ↓ risk of electrocution if a person becomes part of the electrical circuit - ideally electrical current should flow down the circuit
* **Fire**\
Current that exceeds the capability of the conductor results in ↑ heat generation, equipment damage, and possible fire.
    * Principle of fuses which trigger when current drain is excessive\


## Methods of Electrical Safety

Design features to improve electrical safety include:

* **Insulation**\
Conductors are coated by a high-resistance substance, ↓ risk of shorting and heat generation.
* **High-resistance wires**\
Reduce risk of electrocution via devices that *require* an electrical connection to a patient, e.g. EEG or BIS.
* High resistance wires
* **Fuses**\
Safety devices which cease all current flow when current exceeds a certain threshold (typically 20A).
    *  If there is a fault which greatly lowers resistance (i.e. insulation breaks, causing a device to become live and drain via the earth wire), a high current will flow and the fuse will be triggered
    * Activation of a fuse requires:
        * Equipment malfunction that causes a high current flow
        * The fuse to work correctly
    * After a fuse has activated, electricity will be unable to flow and so the device will be inoperable\
    This presents its own safety concerns for critical equipment.
* **Residual Current Device**\
An RCD measures the current difference between the active and neutral lines, and therefore detects a 'leak' of current.
    * In an non-fault situation, these will be equal
    * In a fault situation, current will be being delivered by the active line but not returned via the neutral\
   The 'current gap' indicates current is instead flowing to the ground via the equipment/patient/staff.
    * An RCD will disconnect power within 10ms if there is a >10mA difference between the active and neutral lines
    * Activation of an RCD requires:
        * Equipment malfunction causing current to leak
        * A single fault will turn off the circuit
    * A working RCD will shut off power to the device, and so introduces similar risks to fuses
* **Line Isolation Supply**, with a **line isolation monitor**\
    * A line isolated supply is a 'transformer' with an equal number of windings, such that the:
        * Voltage produced is the same on each side of the 'transformer'
        * **Powerpoint is not physically connected to the supply**\
        This creates an **earth-*referenced***, **floating** power **supply**.
    * A line isolation monitor\
        * A line isolation monitor continuously checks the impedance between the:
            * Active wire and ground
            * Neutral wire and ground
        * Continuously evaluates the impedance between the:
            * Active wire and ground
            * Neutral wire and ground
        * In a no-fault situation, both impedances should be the same, and *close* to infinite\
        Impedance won't be *absolutely* infinite as there will always be a small current leak from devices, and therefore always some impedance to flow.
        * Measures the **prospective hazard current**, which states how much current *could* flow, *if* a fault completed the circuit
            * In a no-fault situation, the impedances are very high (close to infinite), and so the prospective hazard current is very low
            * In a single-fault situation, the calculated impedance for the affected line will be significantly lower, and therefore the prospective hazard current will increase
            * An alarm will sound when the prospective hazard current exceeds 20mA
        * This is called a **prospective hazard current**
            * In a single-fault situation, the calculated impedance for the affected line will be significantly lower, and therefore the prospective hazard current will increase
    * Activation of the line isolation supply:
        * Requires **two** separate faults\
            * Active wire must be connected to ground
            * Neutral wire must be connected to ground\
        * Occurs when the circuit: active wire - ground - neutral wire is created
    * The advantage of a line isolation supply is that:
        * A single fault is not dangerous
        * A single fault will not result in a power loss\
        Important for vital equipment.
    * The disadvantage of a line isolation supply is that:
        * ≥2 faults will not result in a power loss, and therefore are dangerous
* **Equipotential earthing**\
This is the **only method which prevents microshock**.
    * Ultra-low resistance earth cables are attached to electrical devices and the patients bed
    * These cables are then attached to special wall earth connectors
    * This ensures all equipment is referenced to a common ground, minimising the risk of leakage currents between devices and the patient by creating a low-resistance pathway that does not include the patient


### Classification of Electrically Safe Equipment

These classifications are designed to limit macroshock:

* **Class I: Earthed**\
Any part that can contact the user is earthed to ground.
    * If a fault develops such that parts of the device that the user can touch are live, then there is a risk of shock
    * If the case is earthed, the path of least resistance should be via the earth wire\
    This will cause a large current to flow, and should blow a fuse, ceasing current flow.
* **Class II: Double-insulated**\
All parts of the device that the user can touch have two layers of insulation around them, reducing the chance of the device becoming live.
* **Class III: Low-voltage**\
Device operates at less than 40V DC/24V AC, limiting the severity of shock a device can deliver.


### Classification of Electrically Safe Areas

* **B areas**\
Protection against macroshock. Options include:
    * Residual Current Devices
    * Line Isolation Supply
* **BF areas**\
Cardiac (microshock) protection.
    * Requires equipotential Earthing
* **Z areas**\
No particular protections.

---

## References

1. [Electricity and Electrical Hazards](http://www.anaesthesia.med.usyd.edu.au/resources/lectures/electricity.html).
2. Alfred Anaesthesia Primary Exam Tutorial Program
3. Aston D, Rivers A, Dharmadasa A. Equipment in Anaesthesia and Intensive Care: A complete guide for the FRCA. Scion Publishing Ltd. 2014.
