# Non-Invasive Blood Pressure

:::CICM
Describe the ~~invasive and~~ non-invasive measurement of blood pressure ~~and cardiac output~~ including calibration, sources of errors and limitations
:::

:::ANZCA
Describe the methods of measurement applicable to anaesthesia, including clinical utility, complications and sources of error in particular measurement of blood pressure.
:::

Non-invasive blood pressure measurements is performed with either a:

* **D**evice for **I**ndirect **N**on-invasive **A**utomatic **M**ean **A**rterial **P**ressure (DINAMAP)\
Automatic blood pressure cuff.
* Von Recklinghausen's oscillotonometer\
"Manual" blood pressure cuff.
    * Uses two cuffs, and therefore two tubes


## DINAMAP

Components:

* One cuff\
Performs both arterial occlusion and measurement.
* Tubing
* Device for inflating the occlusive cuff and gradually deflating it
* Pressure transducer
* Display

Method:

* Cuff is inflated above SBP
* Cuff deflates at a rate of 2-3mmHg.s^-1^\
When cuff pressure equals:
    * SBP\
    Turbulent flow occurs past the cuff, creating pressure oscillations. The pressure at which these are **first detected** is the **SBP**.
    * MAP\
    The pressure at which **amplitude** of oscillations is maximal.
* DBP is calculated from MAP and SBP


Cons:

* Requires an appropriately sized cuff\
Cuff should be ~20% greater than arm diameter.
    * Cuffs that are too small will over-read
    * Cuffs that are too wide will under-read
* Requires a regular rhythm
* Inaccurate at extremes of blood pressure
* Inaccurate when used more frequently than once per minute
* Inaccurate when the vessel is incompressible
    * Heavily calcified vessels
    * When applied to forearm/foreleg
* May cause neuropraxia


## Von Recklinghausen's Oscillotonometer

Components:

* Two cuffs
    * Occlusive cuff
    * Measurement cuff
* Tubing
* Device for inflating the occlusive cuff and gradually deflating it
* Aneroid barometer for transducing pressure
* Display

Process:

* Cuff is inflated until the radial pressure is no longer palpable\
This is approximates SBP.
* Cuff is deflated, and re-inflated to 20mmHg above the estimated SBP
* Cuff is deflated at a rate of 2-3mmHg.s^-1^ whilst auscultating the brachial artery\
When cuff pressure equals:
    * SBP\
    Turbulent flow occurs past the cuff, turbulent flow causes the first of the **Korotkoff sounds** (clear tapping pulsations) to be heard.
    * DBP\
    The cuff no longer compresses the vessel at all, so no turbulent flow occurs and nothing is auscultated. 


---

## References

1. ANZCA July/August 2000
2. Aston D, Rivers A, Dharmadasa A. Equipment in Anaesthesia and Intensive Care: A complete guide for the FRCA. Scion Publishing Ltd. 2014.
3. Leslie RA, Johnson EK, Goodwin APL. Dr Podcast Scripts for the Primary FRCA. Cambridge University Press. 2011.
