# Scavenging

:::ANZCA
Outline the hazards of anaesthetic gas pollution and the methods of scavenging anaesthetic gases.
:::

Scavenging is the removal and safe disposal of waste anaesthesia gases from the breathing circuit to avoid contamination of the theatre environment. Scavenging is important as continuous exposure of staff to anaesthetic gases has been implicated in:

* Cognitive impairment
* Spontaneous abortion
* Infertility
* Haematological malignancy

## Methods of Scavenging

A scavenging system consists of:

* Gas collection assembly\
    * Connects to the APL valve and ventilator relief valve\
    Collects gas vented from the circuit.
    * Uses a 30mm connector\
    Prevents accidental connection to the breathing system.
* Transfer tubing
* Scavenging interface\
The structure of the scavenging interface depends on the type of scavenging system.
    * Open interface\
    **Active** scavenging systems use a pump to generate a pressure gradient drawing gas to the disposal assembly. The scavenging interface is **open** to air to prevent the negative pressure being transmitted to the patient.
    * Closed interface\
    **Passive** scavenging systems use a series of positive and negative pressure relief valves.
        * When gas pressure in the collection assembly exceeds **5cmH~2~O**, the positive relief valve opens and gas enters a reservoir bag
        * When gas pressure in the disposal assembly falls below **0.5cmH~2~O**, the negative relief valve opens and gas enters the disposal assembly
* More transfer tubing
* Disposal assembly

---

## References

1. Aston D, Rivers A, Dharmadasa A. Equipment in Anaesthesia and Intensive Care: A complete guide for the FRCA. Scion Publishing Ltd. 2014.
