# SI Units


The International System of Units (**SI**, or *Système International d'Unités*), is a set of  measurement standards which defines (almost) all standards in terms of uniform natural phenomena, and form the base of the metric system. 

## Base SI Units

There are **seven base SI units**, with **many derived units** made from combinations of these. Base SI units are mutually independent. They consist of:

|Quantity|Unit|Abbreviation|Definition|
|--|--|--|--|
|**Time**|Second|s|Duration of 9,192,631,770 periods of the radiation corresponding to the transition between two hyperfine levels of the ground state of an atom of Cs-133
|**Length**|Metre|m|Distance that light travels in a vacuum in  1/299,792,458^th^ of a second
|**Current**|Ampere|A|The constant current that would produce a force of 2x10^-7^ Newton between two conductors of infinite length and negligible cross section in a vacuum
|**Temperature**|Kelvin|°K|1/273.16^th^ of the triple point of water. The **triple point** is the temperature at which **a substance** exists in **equilibrium** in **all three phases** (solid, liquid, gas).
|**Amount**|Mole|mol|The amount of substance which contains as many elementary entities as in 0.012kg of Carbon 12
|**Luminous Intensity**|Candella|cd|Luminous intensity of a source which emits monochromatic radiation at 540 x 10^12^ Hz at radiant intensity of 1/683 watts per steradian
|**Mass**|Kilogram|kg|Weight of the International Prototype Kilogram (IPK)

# Derived Units

|Quantity|Unit|Abbreviation|Conversion to Base SI Units|Definition|
|--|--|--|--|
|Area|Square metre|m^2^|$m^2$||
|Velocity|Metre per Second|m.s^-1^|$m \over s$||
|Acceleration|Metre per Second per Second|m.s^-2^|$m \over s^2$||
|Force|Newton|N|$N={kg.m \over s^2}$|Force required to accelerate 1kg at 1m.s^-2^
|Pressure|Pascal|Pa|$Pa = {N \over m^2} = {kg \over m.s^2} $|Force per area
|Energy/Work/Quantity of Heat|Joule|J|$J = N.m = {kg.m^2 \over s^2 }$|Energy converted when 1N is applied to 1kg over 1m
|Dose Equivalence|Sievert|Sv|$Sv = {J \over kg} = {m^2 \over s^2 }$|Radiation dose per mass
|Power|Watt|W|$W = {J \over s} = {kg.m^2 \over s^3 }$|Rate of energy conversion per second
|Electromotive Force|Volt|V|$V = {W \over A} = {kg.m^2 \over A.s^3 }$|Measure of electrical potential energy

---
## References

1. [Physical Measurement Laboratory](http://physics.nist.gov/). National Institute of Standards and Technology.
    * And various subpages