# Supplemental Oxygen


> <p style="color:purple";>Describe different systems to deliver supplemental oxygen and the advantages and disadvantages of these systems </p>

Devices for delivery of oxygen can be classified into:

* Variable performance devices\
* Fixed performance devices


## Variable Performance Devices

Variable performance devices:

* Do not deliver a fixed FiO~2~\
    * This is because respiratory flow is non-uniform\
    Although minute ventilation may be 5-6L.min^-1^, peak inspiratory flows are substantially higher.
    * Delivered FiO~2~ is dependent on oxygen flow and inspiratory flow
        * Increasing oxygen flow rate will increase FiO~2~, but the effect will vary depending on the device (volume, seal) and the patient
* Include:
    * Nasal Cannulae\
    Prongs delivering gas at 1-4L.min^-1^.
        * Higher flows may dry mucosa, and lead to epistaxis
        * Nasopharynx acts as an oxygen reservoir, somewhat increasing FiO~2~
        * Well tolerated
            * Allow eating, drinking, and talking
    * Hudson Mask\
    Simple unsealed mask, allowing gas flow up to 15L.min^-1^.
        * Cheap
        * Less well tolerated
        * Rebreathing may occur
    * Non-Rebreather Mask\
    Modified version of the Hudson mask, containing a reservoir bag.
        * Reservoir bag is filled during expiration
        * Gas is drawn from the reservoir bag during inspiration, increasing FiO~2~\
        Some air is entrained from around the mask and so FiO~2~ is < 1.
      \
## Fixed Performance Devices

Fixed performance devices:

* Theoretically deliver a fixed FiO~2~\
These are usually flow limited as well, and so FiO~2~ may decrease at higher inspiratory flows.
* Include:
    * Venturi\
    Consists of a cone through which oxygen flows. Apertures on the side of the cone entrain room air.
        * Air is entrained via:
            * Frictional drag of molecules
            * The venturi effect (though this is controversial)\
            The widening of the cone leads to an increase in fluid velocity and therefore a decrease in pressure, as per the Bernoulli principle.
        * Entrained air is proportional to flow rate, so the ratio of oxygen to air is constant for any given aperture size\
        This is known as the **entrainment ratio**.
        * Will deliver the specified FiO~2~ provided oxygen flow is above the minimum rate\
        Therefore become variable performance devices when inspiratory flow greatly exceeds oxygen flow.
      \
---
## References

1. Aston D, Rivers A, Dharmadasa A. Equipment in Anaesthesia and Intensive Care: A complete guide for the FRCA. Scion Publishing Ltd. 2014.
