# Temperature

:::CICM
Describe the measurement of body temperature.
:::

:::ANZCA
Describe the methods of measurement applicable to anaesthesia, including clinical utility, complications and sources of error in particular measurement of temperature.
:::

**Temperature** is average kinetic energy of molecules within a material, and is measured in degrees. Temperature is distinct from **heat**, which describes the transfer of thermal energy from one body to another body, and is measured Joules. The two are related by the **specific heat capacity**, which describes how much energy (J) must be applied to a body to raise its temperature by 1°K, without a change in state.

## Temperature Measurement

Temperature is measured by a number of methods:

* Liquid expansion thermometry
* Electrical thermometry


### Liquid Expansion Thermometry

This is used in mercury thermometers. These consist of:

* A graduated **evacuated capillary** of negligible volume, attached to
* A mercury reservoir, of much greater volume, separated by
* A constriction ring\
Prevents travel of mercury up the capillary by gravity.

Method:

* When heated, the kinetic energy of the mercury increases and it expands, forcing it up the capillary\
As the thermal expansion coefficient for all liquids is very small, the capillary must be of a very small volume to create a usable device.
* The speed that this occurs is related to the **time-constant** of the system\
This is typically 30 seconds. Measurement therefore takes ~4 time-constants, or 2 minutes.


Pros:

* Easy to use
* Accurate
* Reusable
* Sterilisable
* Cheap

Cons:

* Slow response\
Only accurate once it has reached thermal equilibrium.
* Glass can break\
May cause release of mercury or alcohol.
* Inaccurate at:
    * Low temperatures with mercury\
    Freezes at -38.8°C.
    * High temperatures with alcohol\
    Boils at 78.5°C. 


## Electrical Thermometry

Electrical methods include:

* **Resistance thermometer**\
Platinum wire increases electrical resistance with increasing temperature.
    * Therefore the voltage drop across the wire will correspond to the temperature of the wire
    * Change in resistance is linear across the temperature range
    * However, these are expensive.
* **Thermistor**\
Metal (e.g. SiO~2~) semiconductor which changes its resistance in a **predictably non-linear fashion** (run-away exponent) with temperature.
    * Can be manufactured so that change is linear over the clinical range
    * Much cheaper than wire resistance methods
    * The degree of voltage drop is usually very small, however this can be amplified using a **Wheatstone bridge**
    * e.g. Pulmonary artery catheter, oesophageal probe
* **Thermocouple**\
At the junction of two dissimilar metals, a potential difference will be produced proportional to their temperature. This is known as the Seebeck effect.
    * Non-linear (wash in exponent)
    * Degrade over time


---

## References

1. Aston D, Rivers A, Dharmadasa A. Equipment in Anaesthesia and Intensive Care: A complete guide for the FRCA. Scion Publishing Ltd. 2014.
2. Alfred Anaesthetic Department Primary Exam Tutorial Series
