# Temperature and Humidity


> Describe the measurement of temperature and humidity

**Temperature** is average kinetic energy of molecules within a material, and is measured in degrees. It is distinct from **heat**, which describes the transfer of thermal energy from one body to another body, and is measured Joules. The two are related by the **specific heat capacity**, which describes how much energy (J) must be applied to a body to raise its temperature by 1°K, without a change in state.

Humidity may be either **absolute** or **relative**:

* **Absolute Humidity** is the mass of water vapour in a volume of air
* **Relative Humidity** measures the percentage saturation of air at *current temperature*, or more formally: $Relative \ Humidity = {mass \ of \ water \ vapour \ in \ volume \ of \ air \over mass \ of \ water \ vapour \ if \ air \ was \ fully \ saturated} = {absolute \ humidity \over mass \ of \ water \ if \ air \ was \ fully \ saturated} $

## Measurement of Temperature

Temperature is measured by a number of methods:

### Liquid Expansion Thermometry

This is used in mercury thermometers. These consist of:

* A graduated **evacuated capillary** of negligible volume, attached to
* A mercury reservoir, of much greater volume, separated by
* A constriction ring\
Prevents travel of mercury up the capillary by gravity.

Mechanism:

* When heated, the kinetic energy of the mercury increases and it expands, forcing it up the capillary\
As the thermal expansion coefficient for all liquids is very small, the capillary must be of a very small volume to create a usable device.
* The speed that this occurs is related to the **time-constant** of the system\
This is typically 30 seconds. Measurement therefore takes ~4 time-constants, or 2 minutes.


#### Pros

* Easy to use
* Accurate
* Reusable
* Sterilisable
* Cheap

#### Cons

* Slow response\
Only accurate once it has reached thermal equilibrium.
* Glass can break\
May cause release of mercury or alcohol.
* Inaccurate at:
    * Low temperatures with mercury\
    Freezes at -38.8°C.
    * High temperatures with alcohol\
    Boils at 78.5°C. 

## Electrical

Electrical methods include:

* **Resistance thermometer**\
Platinum wire increases electrical resistance with increasing temperature.
    * Therefore the voltage drop across the wire will correspond to the temperature of the wire
    * Change in resistance is linear across the temperature range
    * However, these are expensive.
* **Thermistor**\
Metal (e.g. SiO~2~) semiconductor which changes its resistance in a **predictably non-linear fashion** (run-away exponent) with temperature.
    * Can be manufactured so that change is linear over the clinical range
    * Much cheaper than wire resistance methods
    * The degree of voltage drop is usually very small, however this can be amplified using a **Wheatstone bridge**
    * e.g. Pulmonary artery catheter, oesophageal probe
* **Thermocouple**\
At the junction of two dissimilar metals, a potential difference will be produced proportional to their temperature. This is known as the Seebeck effect.
    * Non-linear (wash in exponent)
    * Degrade over time


## Measurement of Humidity

Humidity can be measured by a number of methods:

* **Hair Hygrometer**\
Hair (actual hair) changes elasticity depending on the humidity of air. Changes in elasticity can be related to changes in humidity.

* **Wet and Dry Bulb**\
This system measures both temperature and relative humidity.
    * Two thermometers are used
        * One is wrapped in a wick, which is attached to a water reservoir\
        This is the wet thermometer.
        * The dry thermometer gives a measurement of surrounding air temperature
    * The wet thermometer is cooled due to evaporative cooling from the wick\
    High energy water molecules become vapour, leaving only low energy molecules behind.
    * The **temperature difference** between the thermometers is a function of:
        * Latent heat of vapourisation of water
        * How much evaporative cooling is occurring\
        This is function of humidity.
            * At 100% relative humidity, no evaporative cooling will take place and the temperatures will be equal
            * As humidity decreases, evaporative cooling will cool the wet thermometer, and the temperature difference allows humidity to be determined


---
## References

1. Aston D, Rivers A, Dharmadasa A. Equipment in Anaesthesia and Intensive Care: A complete guide for the FRCA. Scion Publishing Ltd. 2014.
2. Alfred Anaesthetic Department Primary Exam Tutorial Series
