# Acetylcholine Receptors

> Understanding of the pharmacology of anticholinesterase drugs.

<!--></!-->

> <p style="color:purple";>Describe the adverse effects of anticholinesterase agents.</p>

*This covers the pharmacology of acetylcholine receptors and the production and metabolism of ACh. Detailed information on specific agents is in the pharmacopeia.*

Acetylcholine is a neurotransmitter vital for normal function of:

* CNS
* ANS
* Muscle contraction

## Synthesis, Release, and Metabolism

ACh is produced is the nerve cytoplasm by **acetyltransferase** from:

* Choline\
From diet and recycled ACh.
* Acetyl-coenzyme A\
Produced in the inner mitochondrial matrix.

Once synthesised, ACh is then packaged into vesicles (each containing ~10,000 ACh molecules), which are **released in response to calcium** influx occurring at the culmination of an action potential.

Acetylcholine is metabolised by acetylcholinesterase on the post-junctional membrane. AChE:

* Has two binding sites:
    * Anionic binding site\
    Binds the positively charged quaternary ammonium moiety.
    * Esteratic binding site  \
    Binds the ester group of ACh.
* Once bound, ACh is acetylated
* Acetylated-ACh is then hydrolysed to produce **acetic acid**


## ACh Receptor Subtypes

There are two types of ACh receptor:

* **Nicotinic ACh receptors**
    * Inotropic\
    Linked to an ion channel.
        * Non-specific - may allow Na^+^, K^+^, or Ca^2+^ to cross
    * Consists of five subunits:
        * Two α\
        Bind ACh.
        * One β
        * One δ
        * One γ
    * Located in:
        * Post-synaptic NMJ
        * Preganglionic autonomic nervous system\
        Antagonism causes **ganglion blockade**.
        * Brain
    * Known as nicotinic because nicotine agonises this receptor
    * Activation:
        * 2 ACh molecules must bind to activate the receptor
        * Once bound, receptor undergoes a conformational change which opens the central ion pore\
        Permeability to Na^+^ (and to a lesser extent, K^+^ and Ca^2+^) increases, leading to depolarisation


* **Muscarinic ACh receptors**\
    * Metabotropic\
    G-protein coupled.
    * Known as muscarinic because muscarine also agonises this receptor
    * Subdivided into:
        * M~1~ (Gq)\
        Secretory glands and CNS.
        * M~2~ (Gi)\
        Heart.
        * M~3~ Gq\
        Bronchial and arteriolar smooth muscle.
        * M~4~ (Gi) and M~5~ (Gq)\
        CNS.


---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
