# Blood-Brain Barrier

:::ANZCA
Discuss the significance of the blood brain barrier
:::

The blood-brain barrier is a **physiological barrier** which prevents substances in the ECF of the body moving freely into the ECF of the brain. The functions of the BBB are:

* Maintain a stable extracellular milieu\
Optimises neuronal function by preventing fluctuations in plasma K^+^, Na^+^, and H^+^ affecting cerebral cells.
* Protection of the brain\
Isolates the brain from toxins.
* Protection of the body\
Isolates the rest of the body from CNS neurotransmitters.


## Anatomy

The BBB occurs in three layers:

* Capillary endothelial cells\
Joined with **tight junctions**, preventing free movement of solvent and solute.
    * Substances must move through capillary endothelium to reach the brain\
    Capillary endothelial cells contain high numbers of mitochondria, due to the higher energy cost of the active transport mechanisms.
* Basement membrane
* Astrocytes\
Glial cell which extends foot processes around the basement membrane, and reduce permeability of endothelial cells.

Due to their function, several important CNS structures must exist outside of the BBB. These are known as the **circumventricular organs**, and include:

* Sensing structures
    * Chemoreceptor trigger zone (Area Postrema)\
    Identifies toxins in the systemic circulation, triggering vomiting.
    * Hypothalamus\
    Osmoreceptors detect systemic osmolarity.
    * Subfornical organ\
    Role in CVS and fluid balance.
    * Organum vasculosum
* Secreting structures
    * Pituitary\
    Secretes hormones.
    * Pineal gland\
    Secretes melatonin.
    * Choroid plexus\
    Produces CSF via secretion and ultrafiltration of plasma.


### Movement of Substances

Substances can move via:

* **Diffusion**\
For lipid soluble molecules only; e.g:
    * CO~2~
    * O~2~
* **Facilitated diffusion**\
For movement of larger/less soluble molecules down their concentration gradient, e.g:
    * Glucose
    * Water
* **Active transport**\
Responsible for movement of most small ions; e.g:
    * Na^+^
    * Cl^-^
    * K^+^
    * Mg^2+^
    * Ca^2+^

Other substances are specifically excluded:

* **Catecholamines**\
Metabolised by MAO in capillary endothelium, preventing their action as CNS neurotransmitters.
* **Amino acids**\
Prevent action as neurotransmitters.
* **Ammonia**\
Metabolised in astrocytes to glutamine, limiting its neurotoxic effects.


---

## References

1. Lawther BK, Kumar S, Krovvidi H. [Blood–brain barrier](https://academic.oup.com/bjaed/article/11/4/128/266954/Blood-brain-barrier). Continuing Education in Anaesthesia Critical Care & Pain, Volume 11, Issue 4, 1 August 2011, Pages 128–132. 
2. Brandis K. [The Physiology Viva: Questions & Answers](http://www.anaesthesiamcq.com/vivabook.php). 2003.