---
level: 2
---

# Cerebrospinal Fluid

:::CICM
Describe the physiology of cerebrospinal fluid
:::

:::ANZCA
Describe the dynamics and metabolism of cerebrospinal fluid
:::

CSF is a **transcellular** fluid in the ventricles and subarachnoid space. ~150ml (2ml/kg) of CSF exist in a normal individual, divided evenly between the head and spinal column.

## Functions

* **Mechanical Protection**\
Due to its low specific gravity, CSF reduces the effective weight of the brain (by a factor of 30) and therefore reduces trauma caused by the acceleration and deceleration of the brain.
* **Buffering of ICP**\
CSF can be displaced to the spinal subarachnoid and have its rate of reabsorption increased in order to offset an increase in ICP by another space-occupying lesion.
* **Stable Extracellular Environment**\
Neurons are sensitive to ionic changes in the extracellular environment. Ionic concentrations in CSF are tightly controlled, which ensures stable neuronal activity. Additionally, toxins are actively removed from CSF.
* **pH Regulation**\
pH of extracellular fluid is important in the control of respiration, and is also tightly regulated.
* **Nutrition**\
Supply of O~2~ and simple sugars and amino acids, and removal of CO~2~ occurs occurs in CSF.

## Formation

CSF is produced in the **choroid plexus** (70%) and brain **capillary endothelial cells** (30%) at a rate of 0.4 ml.min^-1^ (**500ml.day^-1^**). It is produced by a combination of  **ultrafiltration** and **secretion** from plasma:

* Na^+^ is actively transported\
Drives flow of Cl^-^ ions and water.
* Glucose is transported via facilitated diffusion down its concentration gradient

### Factors Affecting Formation

Formation is relatively constant within normal parameters (altering the rate of absorption is the predominant means to control pressure), though it is reduced by:

* **Decreased Choroidal Blood Flow**\
CPP <70mmHg reduces CSF formation.

### Contents

| Content | Relative Change |      [CSF]      |
|---------+-----------------+-----------------|
| Na^+^   | -               | 140 mmol.L^-1^  |
| Cl^-^   | ↑               | 124 mmol.L^-1^  |
| K^+^    | ↓               | 2.9 mmol.L^-1^  |
| Gluc    | ↓               | 3.7 mmol.L^-1^  |
| pH      | ↓               | 7.33            |
| PCO~2~  | ↑               | 50mmHg          |
| Protein | ↓               | Variable*       |
| Ca^2+^  | ↓               | 1.12 mmol.L^-1^ |
| Mg^2+^  | ↑               | 1.2 mmol.L^-1^  |

Relative to plasma:^[CSF [protein] is  variable:\
\- Highest in the lumbar sac\
\- Lowest in the ventricles\
\- Always lower than plasma [protein]\
\
This means CSF is a **poor buffer solution**, which increases its sensitivity to derangements in respiratory acid-base status.]

* [Na^+^] is unchanged
* [Mg^2+^] and [Cl^-^] are increased
* Concentrations of everything else is less

## Circulation

CSF flow is driven by respiratory oscillations, arterial pulsations, and ongoing production in the choroidal plexus:

* **Production** in the **choroidal plexus** in the **lateral ventricles**
* To the **third ventricle** via the **Foramen of Munro**
* To the **fourth ventricle** via the **Aqueduct of Sylvius**
* To the **cisterna magna** via the two lateral **Foramina of Luschka** and the midline **Foramen of Magendie**
* It may now pass either:
    * **Cranially**, to the **basilar cisterns** and via the **Sylvian fissure** to the **cortical regions**
    * **Caudally**, to the **spinal subarachnoid space** via the **central canal**

## Reabsorption

Reabsorption of CSF:

* Occurs in the **arachnoid villi**, which are located in the **dural walls** of the **sagittal** and **sigmoid sinuses**
    * 85% of reabsorption occurs in intracranial arachnoid villi
    * Remainder by spinal arachnoid villi
* Is predominantly via pinocytosis and opening of extracellular fluid spaces
* Is **pressure-dependent**
    * Reabsorption occurs when the CSF pressure is **1.5mmHg greater** than venous pressure\
    Typically an ICP < 7mmHg results in minimal CSF reabsorption. Above this, CSF absorption increases in a linear fashion up to 22.5mmHg.

---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
2. Hall, JE, and Guyton AC. Guyton and Hall Textbook of Medical Physiology. 11th Edition. Philadelphia, PA: Saunders Elsevier. 2011. 
