---
level: 2
---

# Intraocular Pressure

Normal intraocular pressure is ~**15mmHg**, with a range of 12-20mmHg. Regulation of intraocular pressure is important for:

* Vision\
Sustained high (>25mmHg) can lead to blindness due to compression of axons of the optic nerve and the optic artery at the optic disc.

## Determinants of Intraocular Pressure

As the globe has typically poor compliance, a small increase in volume can cause a large increase in intraocular pressure. Factors affecting volume include:

* Volume of **aqueous humor**\
Aqueous humor is a clear fluid that fills the anterior and posterior chambers of the eye, and provides avascular tissues with nutrients and oxygen whilst still allowing light to pass freely between the lens and retina. Volume of aqueous humor is a function of:
    * Production\
    Aqueous humor is produced by secretion and filtration from capillaries in the ciliary body in the posterior chamber, and circulates through into the anterior chamber.
        * Production is accelerated by β2~2~ agonism
        * Production is inhibited by α~2~ agonism
        * Carbonic anhydrase inhibitors decrease aqueous humor production probably by decreasing sodium secretion into the eye
    * Reabsorption\
    Aqueous humor is reabsorbed into venous blood in the **canal of Schlemm**.
        * The **trabeculae meshwork** is the main source of resistance to reabsorption\
        If this is blocked, a significant reduction in reabsorption can occur and IOP will increase.
        * Reabsorption is affected by:
            * Haemorrhage\
            Blocks trabecular meshwork.
            * Muscarinic antagonism\
            Dilates pupil, which brings the iris closer to canal and decreases absorption.
            * α~1~ agonism\
            Dilates the pupil, decreasing absorption.
            * PGF~2α~\
            Relaxes ciliary muscle, increasing absorption.
* Volume of **blood** within the globe\
Affected by:
    * MAP 
    * Venous obstruction
* **External factors**\
Other factors affecting volume or compliance of the globe:
    * Extraocular muscle tension
    * Extraocular compression

---

## References

1. ANZCA July/August 2000
2. Hall, JE, and Guyton AC. Guyton and Hall Textbook of Medical Physiology. 11th Edition. Philadelphia, PA: Saunders Elsevier. 2011. 
3. Goel M, Picciani RG, Lee RK, Bhattacharya SK. [Aqueous Humor Dynamics: A Review. The Open Ophthalmology Journal](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3032230/). 2010;4:52-59.

