---
level: 2
---

# Spinal Cord Anatomy

:::CICM
Describe the major sensory and motor pathways (including anatomy)
:::

## Spinal Cord Anatomy

The spinal cord in transverse section consists of a central section of grey matter containing neuronal cell bodies and synapses, and a peripheral section of white matter containing myelinated ascending and descending pathways. Important pathways are:

* **Corticospinal tract**\
Motor function. Crosses at the brain stem.
* **Dorsal column**\
Light touch and proprioception. Crosses at the brain stem.
* **Spinothalamic tract**\
Pain and temperature. Crosses within two vertebral segments.
* **Spinocerebellar tract**\
Unconscious proprioception. Does not cross.


## Spinal Cord Blood Supply

Supply is predominantly from **three** major arteries:

* **One** anterior (median) spinal artery
	* Located along anterior midline of cord
	* Arises from the vertebral arteries caudal to the basilar\
	A branch from each vertebral join between C1 and C6 and form the single vessel.
	* Supplies **75%** of arterial blood to the spinal cord.
	* Reinforced by supply from:
		* Unpaired radicular arteries
			* Usually **5-10** total but only one in midthoracic regions\
			* Originate from posterior intercostal arteries
		* Artery of Adamkiewicz
			* Variable origin between T7 and L4
			* Left sided in the majority of patients
			* Principle supply to the lower two-thirds of the cord
	**Anterior** cord **supply** is much **more vulnerable** than the posterior portion.
* **Two** posterior (lateral) spinal arteries
	* Fed by smaller radicular arteries at almost every spinal levels
* An **arteriolar plexus** is formed by both anterior and posterior arteries, and forms a fine pial plexus known as the **vasa corona**\
This plexus is not able to compensate for a loss of supply to either anterior or posterior vessels.


Additional perfusion to the cervical region from:

* Posterior inferior cerebellar arteries
* Segmental branches


## Spinal Cord Syndromes

Lesions to certain anatomical regions of the spinal cord produce a particular constellations of findings.

### Complete Transection

A complete transection results in loss of movement and sensation below the level of the lesion. Initially, paralysis is flaccid (and other signs, such as priapism, may be absent in this 'spinal shock' phase) becomes spastic after a few weeks. Bowel and bladder function is lost.

Lesions above T10 will result in impaired cough in the initial stage as the abdominal wall is unable to contract (intercostal muscle function may be impaired as well, but this is of less importance clinically). 

### Central Cord Syndrome

Central cord syndrome results in a flacid paralysis and loss of sensation of the **upper limbs greater than the lower limbs**.

### Anterior Cord Syndrome

Anterior cord syndrome spares the dorsal columns only, therefore motor function and pain and temperature sensation are affected below the level of the lesion.

### Brown-Sequard Syndrome

Hemisection of the cord results in:

* **Ipsilateral** loss of **motor function** below the level of the lesion
* **Ipsilateral** loss of **light touch and proprioception** below the level of the lesion
* **Contralateral** loss of **pain and temperature** sensation below the level of the lesion
* **Ipsilateral** loss of **pain and temperature** sensation **at the level** of the lesion

### Cauda Equina

Cauda Equina syndrome results from compression of lumbosacral nerve roots below the level of the conus medullaris. It may produce a combination of UMN and LMN signs:

* Radiculopathy
* Sacral sensory loss
* Asymmetric LMN weakness and atrophy
* Erectile dysfunction and inability to ejaculate
* Urinary retention and overflow incontinence
* Constipation and overflow incontinence

---

## References

1. Goldber S. Clinical Neuroanatomy Made Ridiculously Simple. 3rd Ed. Medmaster. 2005.
2. McMinn, RMH. Last's Anatomy: Regional and Applied. 9th Ed. Elsevier. 2003.
