# Amiodarone


Amiodarone is an antiarrhythmic agent with a complex mechanism of action and many effects.

* K^+^ channel blockade in cardiac myocytes, inhibiting the slow outward current and slowing repolarisation (Class III)
* β-blocker-like activity on SA and AV nodes, decreasing automaticity and slowing nodal conduction (Class II)
* Ca^2+^ channel blocker-like activity on L-type Ca^2+^ channels, decreasing the slow inward Ca^2+^ current, increasing depolarisation time and decreasing nodal conduction (Class IV)
* α-blocker-like activity, decreasing SVR

```{r}
source("scripts/drugtables.R")

DrugTable("amiodarone", caption = "Amiodarone")
```

A **mnemonic** for some of the rarer effects is **BITCH**:

* **B**lue skin
* **I**nterstitial lung disease
* **T**hyroid
* **C**orneal
* **H**epatic

***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.
2. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.
