# Amiodarone


Amiodarone is an antiarrhythmic agent with a complex mechanism of action and many effects.
* K^+^ channel blockade in cardiac myocytes, inhibiting the slow outward current and slowing repolarisation (Class III)
* β-blocker-like activity on SA and AV nodes, decreasing automaticity and slowing nodal conduction (Class II)
* Ca^2+^ channel blocker-like activity on L-type Ca^2+^ channels, decreasing the slow inward Ca^2+^ current, increasing depolarisation time and decreasing nodal conduction (Class IV)
* α-blocker-like activity, decreasing SVR

|Property|Amiodarone|
|--|--|
|**Class**|Class III antiarrhythmic, though exhibits action from all 4 classes.|
|**Uses**|VT/VF, resistant arrhythmia, ALS.|
|**Presentation**|100/200mg tablets, IV: 150mg ampoule to be reconstituted in D5W.|
|**Route of Administration**|IV/PO.|
|**Dosing**|IV: Load with 5mg.kg^-1^ over 1/24, with a further 15mg.kg^-1^ over the following 24/24  PO: 200mg TDS for 1/52, 200mg BD for 1/52, 200mg OD thereafter.|
|**Absorption**|Poor PO absorption with bioavailability ~50%.|
|**Distribution**|Highly protein bound with very high V~D~ of ~70L.kg^-1^s due to accumulation in fat and muscle.|
|**Metabolism**|Hepatic metabolism with inhibition of CYP3A4, to the active **desmethylamiodarone**.|
|**Elimination**|Very long t~1/2~ of up to ~55 days. Biliary, skin, and lacrimal elimination, with < 5% of drug eliminated renally. Not removed by dialysis.|
|**Resp**|10% 3-year risk of pneumonitis, fibrosis, pleuritis.|
|**CVS**|↓ HR, ↓ BP, ↓ SVR, ↑ QT without risk of TDP. Irritant to peripheral veins.|
|**CNS**|Mild blurring of vision from corneal deposition, sleep disturbance, vivid dreams, peripheral neuropathy.|
|**MSK**|Photosensitivity, grey skin.|
|**Endocrine**|Hyperthyroidism (1%) and hypothyroidism (6%).|
|**GIT**|Nausea, vomiting, cirrhosis, hepatitis, and jaundice.|
|**Other**|Amiodarone has potential to cause a number of drug interactions due to its inhibition of CYP3A4 and its high protein binding. A selection include: Digoxin, statins, warfarin, phenytoin, and other antiarrhythmics. <br> Contraindicated in **porphyria**.

A **mnemonic** for some of the rarer effects is **BITCH**:

* **B**lue skin
* **I**nterstitial lung disease
* **T**hyroid
* **C**orneal
* **H**epatic

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014. Peck and hill
2. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.