# Beta-Blockers


β-blockers are competitive (often highly selective) antagonists of β-adrenoreceptors. They are sub-classified into into selective and non-selective agents:

* Selective (β~1~ antagonism) (BEAM)
    * Bisoprolol
    * Esmolol
    * Atenolol
    * Metoprolol
* Non-selective (β~1~ and β~2~ antagonism)
    * Propranolol
    * Sotalol
    * Timolol
* Non-selective (β & α antagonism)
    * Carvedilol
    * Labetalol


## Indications

* Cardio
    * Angina
    * Arhythmia
        * Rate-control in AF
        * Paroxysmal SVT
        * Sinus tachycardia from ↑ catecholamines
    * Cardiac Failure
    * Secondary prevention for MI


* Vascular
    * Hypertension (2^nd^ line)\
    Also useful for aggressive control of BP.
    * Hypotensive anaesthesia
    * Attenuate hypertensive response to laryngoscopy


* Non-CVS
    * Thyrotoxicosis
    * Glaucoma (topically)
    * Anxiety
    * Migraine prophylaxis


: Common Effects of Beta Blockers

|Property|Action|
|--|--|
|**Kinetics**|Variability primarily due to lipid solubility. Poor lipid solubility confers poor gut absorption and minimises need for hepatic metabolism. Lipid soluble agents will have CNS effects and be excreted in breast milk.
|**Respiratory**|Bronchospasm.
|**CVS**|↓ Inotropy, ↓ HR, ↓ MVO~2~, ↓ BP, ↑ SVR (β~2~ effect), worsen arrhythmia.
|**CNS**|Tiredness, nightmares, and sleep disturbance with lipid soluble agents. ↓ IOP.
|**Metabolic**|↓ Insulin release and blunted hypoglycaemic response (β~2~ effect).
|**Interactions**|Contraindicated with cardioselective Ca^2+^ channel blockers. due to extreme ↓ HR & ↓ inotropy.|

```{r}
source("scripts/drugtables.R")

DrugTable("esmolol", "metoprolol", "atenolol", "propranolol", "labetalol", caption = "Comparison of Beta-Blockers")
```

***

## References

1. Leslie RA, Johnson EK, Goodwin APL. Dr Podcast Scripts for the Primary FRCA. Cambridge University Press. 2011.
2. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
3. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
4. MacCarthy EP, Bloomfield SS. [Labetalol: a review of its pharmacology, pharmacokinetics, clinical uses and adverse effects.](https://www.ncbi.nlm.nih.gov/pubmed/6310529) Pharmacotherapy. 1983. Jul-Aug;3(4):193-219.
