# Calcium Channel Blockers


Ca^2+^-channel blockers:

* Have affinity for L-type calcium channels\
L-type channels exist in myocardium, nodal, and vascular smooth muscle.
    * Variable affinity for each causes a preference for either nodal and inotropic, or vascular effects
* Prevent Ca^2+^ entry into cells in a use-dependent fashion

: Classification of Calcium Channel Blockers

|Class|Chemical Structure|Drugs|
|--|--|--|
|Class I|Phenylalkylamines|Verapamil|
|Class II|Dihydropyridines|Nifedipine, amlodipine, nimodipine|
|Class III|Benzothiazepines|Diltiazem|

```{r}
source("scripts/drugtables.R")

DrugTable("verapamil", "amlodipine", "diltiazem", caption = "Comparison of Calcium-Channel Blockers")
```

***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
3. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.
