# Calcium Channel Blockers


Ca^2+^-channel blockers:

* Have affinity for L-type calcium channels\
L-type channels exist in myocardium, nodal, and vascular smooth muscle.
    * Variable affinity for each causes a preference for either nodal and inotropic, or vascular effects
* Prevent Ca^2+^ entry into cells in a use-dependent fashion

|Class|Chemical Structure|Drugs|
|--|--|--|
|Class I|Phenylalkylamines|Verapamil|
|Class II|Dihydropyridines|Nifedipine, amlodipine, nimodipine|
|Class III|Benzothiazepines|Diltiazem|

## Comparison of Calcium Channel Blockers

|Property|Verapamil|Amlodipine|Diltiazem|
|--|--|
|**Class**|Phenylalkylamine|Dihydropyridine|Benzothiazepine|
|**Uses**|SVT, excluding AF with WPW|HTN, Angina|Angina, HTN, SVT, Raynaud's, migraine, oesophageal dysmotility|
|**Presentation**|20-240mg tablet, PO solution, IV at 2.5mg.ml^-1^|Tablet|Tablet|
|**Isomerism**|Racemic preparation. The D-isomer also has some local anaesthetic activity|||
|**Route of Administration**|PO/IV|PO|PO|
|**Dosing**|80-160mg BD/TDS|2.5-10mg daily|30-120mg TDS|
|**Absorption**|20% bioavailability|60% bioavailability|40% bioavailability|
|**Distribution**|90% protein bound|90% protein bound, lipid insoluble.|80% protein bound|
|**Metabolism**| Hepatic to active norverapamil|Hepatic to inactive metabolites|Hepatic to active metabolites|
|**Elimination**|Renal elimination of active metabolites|Renal of inactive metabolites|Renal of active metabolites. t~1/2~ 2-7 hours|
|**CVS**|↓ HR via ↓ SA and ↓ AV nodal conduction, ↓ inotropy, ↓ SVR, ↓ BP, arrhythmia including HB|↓ SVR, ↓ BP, with reflexive ↑ HR, ↑ inotropy, ↑ CO|↓ AV nodal conduction but typically stable HR, ↓ SVR, ↓ CVR, ↓ MVO~2~, ↑ CO|
|**CNS**|↓ Cerebral vascular resistance|↓ Cerebral vascular resistance with **nimodipine**||
|**GIT**|||↓ LOS tone|
|**Interactions**|Contraindicated with concurrent β-blocker use due to profound ↓ HR, ↓ inotropy||Contraindicated with concurrent β-blocker use due to profound ↓ HR, ↓ inotropy|

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
3. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.
