# Centrally Acting Anti-Hypertensives


|Property|Clonidine|Methyldopa
|--|--|
|**Class**|Central α~2~-agonist (200:1 α~2~:α~1~)|Phenylalanine derivative|
|**Uses**| Analgesia, sedation, anti-hypertensive|Antihypertensive (especially in pregnancy)
|**Presentation**| Clear colourless solution at 150μg.ml^-1^|Tablets - not appropriate for urgent blood pressure reduction|
|**Route of Administration**| PO/IV at 10-200mcg up to QID. Can be added to neuraxial blockade at 1-2mcg.kg^-1^ to decrease opioid requirement.|PO/IV.
|**Dosing**| 50-200μg QID.|250-500mg PO BD/TDS.
|**Absorption**|100% PO bioavailability with rapid absorption|Highly variable PO bioavailability
|**Distribution**|20% bound, V~D~ 2L.kg^-1^|50% protein bound, V~D~ 0.3L.kg^-1^
|**Metabolism**|50% hepatic to inactive metabolites, t~1/2~β 9-18 hours|Intestinal and hepatic
|**Elimination**|50% renal elimination unchanged|40% renal elimination unchanged
|**Mechanism of Action**|Agonist of central α2 receptor, ↓ SNS tone via decreased NA release from peripheral nerve terminals.| Metabolised to α-methyl-noradrenaline in the CNS, which agonises central α2 receptors.
|**CVS**|Initial ↑ in BP due to α~1~ stimulation, evident with bolus dosing. Followed by prolonged ↓ in BP, ↑ PR, ↓ AV conduction, ↑ baroreceptor sensitisation (lower HR for a given increase in BP). Cessation may cause rebound HTN.|↓ SVR with unchanged HR or CO
|**CNS**| Sedation, analgesia due to ↓ NA release which ↓ opioid requirement. Adjunct in chronic pain and in opioid withdrawal. Anxiolysis at low doses. Central antiemetic effect.|May ↓ MAC
|**Metabolic**|Stress response to surgical stimulus is inhibited||
|**Renal**| Diuresis secondary to inhibition of ADH||


---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
