# Direct Vasodilators


Direct vasodilators include:

* Ca^2+^ channel blockers (see [Calcium Channel Blockers](calcium_channel_blockers.qmd))
* Nitrates\
Increase production of NO:
	* NO activates guanylate cyclase, increasing cGMP
	* cGMP inhibits Ca^2+^ uptake into smooth muscle and enhances its sequestration into smooth endoplasmic reticulum\
	The decrease in cytoplasmic [Ca^2+^] causes smooth muscle relaxation and vasodilation
* Hydralazine\
Multimodal mechanism of action, including:
	* Opens K^+^ channels, hyperpolarising vascular smooth muscle
	* Decreases intracellular Ca^2+^ in vascular smooth muscle
	* Activation of guanylate cyclase

```{r}
source("scripts/drugtables.R")

DrugTable("sodium_nitroprusside", "glyceryl_trinitrate", "hydralazine", caption = "Direct Vasodilators")
```

## Nitrate Toxicity

Nitrate toxicity can be related to:

* Cyanide
* Thiocyanate
* Methaemoglobinaemia

### Cyanide Toxicity

Cyanide toxicity occurs only with SNP, as CN^-^ is produced as a byproduct of metabolism or the effect of light.

* **Kinetics**\
	* Rapid cellular uptake
	* Small V~D~
	* Hepatically metabolised to **thiocyanate**, using thiosulfate as a substrate
* **Mechanism**\
CN^-^ binds to cytochrome oxidase, preventing oxidative phosphorylation. This causes histotoxic hypoxia, and is characterised by:
	* Rapid loss of consciousness and seizures
	* Metabolic acidosis
	* Lactataemia
	* Arrhythmia
	* Increased MVO~2~
	* Hypertension\
	Due to tachyphylaxis to SNP.
* Risk of cyanide toxicity from SNP is related to:
	* Infusion rate
	* Infusion duration
* **Management**
	* Supportive care, including inotropes
	* Cyanide chelators\
	Bind CN^-^, removing it from the circulation. Include:
		* Dicobalt edetate
		* Hydroxycobalamin (Vitamin B~12~)
		* Sulfur donors\
		Provide additional sulfhydryl groups, allowing further hepatic metabolism of CN^-^ to SCN. Include:
			* **Thiosulfate**
		* Nitrites\
		Converts Oxy-Hb to Met-Hb, which has a higher affinity for CN^-^ than cytochrome oxidase. Include:
			* Sodium nitrite
			* Amyl nitrite

### Thiocyanate Toxicity

Thiocyante is produced with hepatic metabolism of CN^-^. Toxicity occurs when thiocyanate accumulates, which occurs in:

* Long duration SNP infusions\
7-14 days.
* Patients with renal failure\
Reduced clearance, may occur in 3-6 days.
* Patients given thiosulfate for management of CN^-^ toxicity.


* **Effects**\
Multisystemic, including:
	* Rash
    * Abdominal pain
    * Weakness
    * CNS disturbance


* **Treatment**\
    * Dialysis

### Methaemoglobinaemia

Methaemoglobinaemia occurs when the Fe^2+^ (ferrous) ion in haemoglobin is oxidised to the Fe^3+^ (ferric) form, which is **unable** to **bind oxygen**.

* Due to the high concentration of oxygen in erythrocytes, methaemoglobin is continually being formed
* Several endogenous reduction systems exist to keep MetHb levels stable at ~1%
	* Predominantly cytochrome-*b*~5~ reductase
	* NADPH-MHb reductase\
	This reduces methaemoglobinaemia in the presence of a reducing agent, classically **methylene blue**.
	* Reduced glutathione\
	More important in preventing oxidative stress in other cells than the RBC.
* Disease occurs due to the loss in oxygen-carrying capacity from the loss of effective haemoglobin\
	* e.g. a 20% MetHb level gives a *theoretical* oxygen carrying capacity of 80% of the actual haemoglobin\
	There is in fact a slight **left shift** of the **oxyhaemoglobin dissociation curve**, as oxygen binds more tightly to the partially-oxidised haemoglobin.


***

## References

1. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
2. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
4. CICM September/November 2008
5. [LITFL- Cyanide Poisoning](http://lifeinthefastlane.com/ccc/cyanide-poisoning)
6. Thomas C, Lumb A. [Physiology of haemoglobin](https://academic.oup.com/bjaed/article/12/5/251/289041/Physiology-of-haemoglobin). Continuing Education in Anaesthesia Critical Care & Pain, Volume 12, Issue 5, 1 October 2012, Pages 251–256.
7. Wright RO, Lewander WJ, Woolf AD. [Methemoglobinemia: Etiology, Pharmacology, and Clinical Management](http://www.sciencedirect.com/science/article/pii/S0196064499701678). Annals of Emergency Medicine, Volume 34, Issue 5, 1999, Pages 646-656.
8. Russwurm M, Koesling D. [NO activation of guanylyl cyclase](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC526456/). The EMBO Journal. 2004;23(22):4443-4450.
