# Inotropes

>Understand the detailed pharmacology of inotropes ~~and vasopressors~~

Inotropes are agents which alter myocardial contractility.
* Positive inotropes increase contractility
* Negative inotropes decrease contractility

## Classes of Positive Inotrope


|Classes|Class I: Increase Intracellular Calcium|Class II: Calcium Sensitisers|Class III: Metabolic/Endocrine|
|--|--|--|--|
|**Examples**|Adrenaline, milrinone, glucagon, digoxin|Levosimendan|T3, Insulin|
|**General Mechanism of Action**|Increase intracellular Ca^2+^ by a variety of different pathways|Increase sensitivity of actomyosin to Ca^2+^|Variable. T3 potentiates the effect (or increases expression of) cardiac β~1~ receptors|


---
## References

1. Leslie RA, Johnson EK, Goodwin APL. Dr Podcast Scripts for the Primary FRCA. Cambridge University Press. 2011.
2. Tielens ET, Forder JR, Chatham JC, Marrelli SP, Ladenson PW. [Acute L-triiodothyronine administration potentiates inotropic responses to P-adrenergic stimulation in the isolated perfused rat heart](https://academic.oup.com/cardiovascres/article-pdf/32/2/306/1006742/32-2-306.pdf). Cardiovascular Research 32 (1996) 306-310.