# 2020B Question 09 

Discuss factors that influence the toxicity of local anaesthetics when used for topical anaesthesia of skin and mucosa.


## Examiner Report

This question had a very low pass rate as most candidates only addressed part of the question. Common mistakes included limiting the discussion to local anaesthetic systemic toxicity (LAST) and not discussing other forms of toxicity resulting from metabolites, pharmacodynamic effects, drug interactions and allergic reactions. Another common mistake was to only discuss the absorption of topical anaesthetics without acknowledging other pharmacokinetic processes.

Despite having a low pass rate, candidates typically wrote long answers. The long answers included topics that did not answer the question, such as detail on the mechanism of action of local anaesthetics, or added peripheral support to the answer, such as lengthy descriptions of the symptoms of LAST. Finally, using examples of local anaesthetics that are not used for topical anaesthesia did not attract any marks. In summary candidates are encouraged to read and answer the question carefully.

## Model Answer

Structure:
- Means of toxicity
- Determinants of drug uptake
- Determinants of LAST susceptibility


### Means of Toxicity


|Method|Detail|
| -- | -- 
|LAST|<p>- Systemic blockade of voltage-gated Na^+^ channels (∝ dose)</p><p>- CNS effects: e.g. Seizure, coma</p><p>- CVS effects: e.g. Arrhythmia, arrest</p>|
|Cocaine toxicity|<p>- Effects mostly ∝ dose</p><p>- Effects ?Additive ?Synergistic with other local anesthetics (e.g. Nasal surgery)</p><p>- CVS: ↑↑ Noradrenaline → ↑ BP, ↑ HR, coronary vasoconstriction,<br>  Cardiomyopathy (?Idiosyncratic)</p><p>- CNS: ↑↑ Dopamine → Euphoria, risk-taking</p><p>- Nasal: Profound vasoconstriction → Ischaemic necrosis (∝ dose)</p>|
|Prilocaine toxicity|<p>- ↑ Methaemoglobin → Hb unable to bind O~2~ (∝ dose)</p><p>- ↑↑ Risk of reductase deficiency: Neonate, congenital</p>|
|Hypersensitivity|<p>- i.e. Allergy, anaphylaxis (dose-independent)</p><p>- e.g. PABA metabolite of esters</p><p>- e.g. Sodium metabisulfite preservative with lignocaine</p>|

### Determinants of Drug Uptake


|Determinant|Detail|
| -- | -- |
|Diffusion rate:|<p>Fick’s Law: $Q = (C_1 - C_2) \times {Area \over Thickness} \times {Membrane \ Solubility \over \sqrt{Molecular \ Weight}}$</p>|
|↑ C1|<p>- ↑ Drug concentration (e.g. 10% lignocaine for airway topicalisation)</p><p>- Eutectic mixture: Optimal ratio → ↓ Melting point → Liquid state → ↑ C1 (cf. solution)</p><p>&emsp;- EMLA: 2.5% lignocaine + 2.5% prilocaine, melting point 18°C</p>|
|↓ C2|<p>- ↑ Tissue blood flow → ↓ C2 but also offset of local effect</p><p>- Intrinsic: e.g. Lower flow to foot cf. scalp</p><p>- Drug Additive: Adrenaline → ↓ Rate of absorption (e.g. Nasal lignocaine)</p><p>- Pathology: Hypothermia, shock, heart failure</p>|
|↑ Area|<p>- ↑ Area of application → ↑ Total absorption but ↔ Absorption per unit area</p>|
|↓ Thickness|<p>- Extensor thicker than flexor</p><p>- Lower limb thicker than upper limb</p><p>- Mucous membrane → ↓↓ Thickness, ↑↑ Rate of blood flow</p><p>&emsp;- Contraindication for EMLA, topical amethocaine</p><p>&emsp;- Risk of inadvertent overdose during topicalisation for AFOI</p>|
|↑ Diffusion Coefficient|<p>- ↑ Lipid solubility -(lignocaine 150x, prilocaine 50x procaine)</p><p>- ↑ % Unionized</p><p>&emsp;- Drug: Lignocaine 25%, prilocaine 33%, higher than most</p><p>&emsp;- Additive: NaOH in EMLA → ↑ PH</p><p>- ↓ Molecular weight (all LA drugs have similar MW 200-250g.mol^-1^)</p>|
|Diffusion Time:|<p>- Uptake ∝ Application time</p><p>- EMLA 30 mins for PIVC, 120 mins for skin graft</p><p>- 2% lignocaine viscous gargle ≤1 minute for pharyngeal topicalisation</p>|

### Determinants of LAST Susceptibility


|Determinant|Detail|
| -- | -- |
|Drug|<p>Pharmacokinetics (PK):</p><p>- Esters: Rapid metabolism by BChE → Short t1/2β</p><p>- Amides: Slow metabolism by liver → Long t1/2β</p><p>Pharmacodynamics (PD):</p><p>- Toxicity Threshold: Bupiv 1.5μg/mL, ropiv 4μg/mL, lignocaine 5μg/mL</p><p>- CC:CNS ratio – Bupivacaine 3:1, ropivacaine 5:1, lignocaine 7:1</p>|
|Patient|<p>PK:</p><p>- Absorption: See Above</p><p>- Distribution: Cachexia → ↑ Plasma concentration → ↑ Risk</p><p>- Metabolism: Liver disease → ↓ Rate of amide removal → ↑ Risk</p><p>PD:</p><p>- Class 1 antiarrhythmics → ↑ Na^+^ Channel blockade → ↑ Risk</p><p>- CVS</p><p>&emsp;- ↑ HR → ↑ Channel cycling rate → ↑ Risk</p><p>&emsp;- ↓ PaO~2~, ↓ pH, ↑ K^+^ → ↑ Risk</p><p>&emsp;- IHD, channelopathy → ↑ Risk arrhythmias</p><p>&emsp;- AV conduction delay → ↑ Risk high grade block from lignocaine</p><p>- CNS</p><p>&emsp;- ↑ PaCO~2~ (↑ CBF), ↓ PaO~2~, ↓ pH → ↑ Risk</p><p>&emsp;- Pregnancy → ↑ Local anaesthetic sensitivity</p><p>&emsp;- Epilepsy, tramadol → ↓ Seizure threshold</p>|


--- 

