# 2020B Question 15 

Discuss the pharmacokinetic implications of severe chronic kidney disease, using examples of drugs used in anaesthesia to illustrate your answer.


## Examiner Report

Most candidates attempted to define severe CKD and various GFR ranges were quoted. Better candidates recognised that CKD is on a spectrum with greater reductions in GFR with increasing severity, with end stage being GFR≤15 mL/min, or dialysis dependent.

The focus of this question is on PK changes and required candidates to describe these changes as well as the implications. The majority of answers were well structured with Absorption, Distribution, Metabolism and Elimination categories considered. For absorption, not many considered TBW changes resulting in oedema that may increase the barrier to diffusion and slow onset of patches or s/c drugs. Uraemia and its effects on gastric motility and nausea/vomiting, as well as GIT oedema may affect absorption of orally administered drugs.

Candidates were expected to give a reasonable explanation on at least distribution and elimination, with examples of commonly used drugs seen in anaesthesia. Too often, there was not enough detail in the answer. Stating that clearance of a drug will be reduced with a decrease in GFR and will require dose adjustment is not sufficient at this level. The kidneys are responsible for eliminating drugs unchanged as well as metabolites of drugs that may also be active. A frequent example given of an active metabolite was morphine-6-glucuronide, but it also requires a brief mention of what the potential effects of this are and how to minimise this, by changes in dosing intervals or using alternative drugs for instance.

Better candidates considered the effects of dialysis in their answers (with effects on TBW and drug concentration), as well as multiorgan involvement (e.g hepatorenal syndrome)

## Model Answer

Structure:
- Introduction
- Absorption
- Distribution
- Metabolism
- Excretion


### Introduction


|Term|Detail|
| -- | -- |
|Definition|Kidney damage or dysfunction of any cause for ≥3/12|
|Staging by GFR|<p>1. >90mL.min^-1^</p><p>2. 60-90</p><p>3. 30-60</p><p>4. 15-30</p><p>5. ≤15 or dialysis-dependent (= failure)</p>|
|Implications|<p>- Disturbs all aspects of pharmacokinetics</p><p>- Unpredictable drug behaviour</p><p>→ Titrate to effect ± ↓ dose ± ↓ frequency</p>|
|Risk factors for toxicity|<p>- Severe ↓ GFR</p><p>- Renal clearance of parent or active/toxic metabolite</p><p>- Low therapeutic index</p><p>→ e.g. Digoxin in ESKD</p>|

### Absorption


|Route|Detail|
| -- | -- |
|Oral|<p>- ↑ Urea → Delayed gastric emptying</p><p>→ Risk of dose stacking (e.g. PO metoprolol)</p>|
|Inhaled|<p>- Volatile uptake unaffected</p>|
|SC / IM / topical|<p>- ↑ TBW → Oedema → ↑ Diffusion distance → ↓ Rate of onset</p><p>- ±Cardiorenal syndrome → ↓ Blood flow → ↓ Rate of onset</p><p>→ Risk of dose stacking (e.g. GTN patch, IM ephedrine)</p>|

### Distribution


|Variable|Detail|
| -- | -- |
|Volume of distribution|- ↑ ECF volume → ↑ V~D~ water-soluble drugs → ↑ Loading dose<br>  (e.g. Suxamethonium)|
|Acid-base|<p>- ±Metabolic acidosis</p><p>- ↑ Unionised % of acidic drugs (e.g. Thiopentone → CVS toxicity)</p><p>- ↓ Unionised % of basic drugs (e.g. Morphine → ↓ Effect)</p>|
|Plasma proteins|<p>*Important for highly bound drugs.*</p><p>- ↓ Albumin → ↑ Free acidic drug (e.g. Diazepam → CNS depression)</p><p>- ↑ AAG → ↓ Free basic drug (e.g. Morphine → ↓ Effect)</p>|

### Metabolism


|Route of Clearance|Detail|
| -- | -- |
|Hepatic|<p>- Urea → Inhibition of CYP enzymes (e.g. Fentanyl → ↑ Duration)</p><p>- ±Hepatorenal syndrome</p>|
|Renal|- ↓ Drug metabolism (e.g. Insulin → ↑ Duration)|

### Excretion


|Route of Elimination|Detail|
| -- | -- |
|Renal|<p>Renal drug clearance ∝ GFR:</p><p>- Minimal metabolism: e.g. Pancuronium → ↑↑ duration) prefer atracurium</p><p>- Active metabolite: e.g. M6G → Opioid toxicity (prefer fentanyl)</p><p>- Toxic metabolite: e.g. Norpethidine → Seizure (prefer fentanyl)</p>|
|Haemodialysis|<p>Variable clearance:</p><p>- Small, unbound particles cleared→ Give after dialysis</p><p>- Large, bound drugs unaffected → Same schedule</p><br><p>Normalisation of TBW:</p><p>- ↓ V~D~ water-soluble drugs</p>|


--- 

