---
level: 3
---

# Adrenoreceptors

:::CICM
Understand the pharmacology of adrenoreceptor blocking drugs.
:::

Adrenoreceptors are classified by their varying sensitivity to different catecholamines^[This covers the pharmacology of adrenoreceptors. The production and metabolism of endogenous catecholamines is covered under [adrenal hormones](adrenal-hormones.md). Detailed information on specific sympathomimetic agents, including structure-activity relationships, is in the [pharmacopeia](adrenergic_drugs.md).]. Additionally:

* All adrenoreceptors are G protein-coupled receptors
    * Each receptor contains seven transmembrane α-helical subunits, three extracellular loops, and three intracellular loops
* Alpha receptors have different subunits and mechanisms of action
* **All beta receptors** are:
    * G~s~ coupled
    * Activate adenylate cyclase increasing cAMP, leading to increased Na^+^/K^+^ ATPase activity and hyperpolarisation


## Adrenoreceptor Subtypes

**α~1~-receptors**:

* Are present in smooth muscle\
Agonism causes vasoconstriction, relaxation of GIT muscle (via presynaptic receptors), and contraction of GU muscle.
* They are:
    * G~q~ coupled
    * Phospholipase C activated increases IP~3~, increase calcium

**α~2~-receptors**:

* Are present in the CNS, arterioles, pancreas\
Agonism causes sedation, analgesia, vasodilatation, and inhibition of insulin release.
* They are:
    * G~i~ coupled
    * Inhibits adenylate cyclase, decreasing cAMP

**β~1~-receptors**:

* Are present in cardiac muscle and the JGA
    * Cardiac agonism increases inotropy, chronotropy, and dromotropy
    * JGA agonism increases renin release
* Increase in cAMP increases intracellular calcium

**β~2~-receptors**:

* Are present in skeletal vascular and bronchial smooth muscle, the liver, and on cell membranes\
* Agonism causes:
    * Vasodilation and bronchodilation
    * Hepatic glycogenolysis
    * Increases activity of the Na^+^-K^+^ ATPase pump, increasing intracellular potassium
* Increase in cAMP increases Na^+^/K^+^ ATPase activity and hyperpolarisation

**β~3~-receptors**:

* Are present in fat\
Agonism causes lipolysis and thermogenesis.

---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
2. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
3. Barrett KE, Barman SM, Boitano S, Brooks HL. Ganong's Review of Medical Physiology. 24th Ed. McGraw Hill. 2012.