---
level: 3
---

# Cardiovascular Effects of Ageing

:::CICM
Describe the cardiovascular changes that occur with ageing.
:::

CVS effects of ageing can be divided into:

* Cardiac
* Vascular
* Autonomic

## Cardiac Changes

* Decreased maximum heart rate\
Due to fibrosis of the SA node causing reduced pacemaker cell number and function, and reduction in catecholamine receptor density.
    * $Maximum \ heart \ rate \approx 220 - Age$
* Decreased inotropy\
Minor.
* Increased reliance on atrial kick\
Reduced ventricular compliance increases the reliance on atrial kick to achieve adequate preload.
* Decreased diastolic compliance
    * Due to hypertrophy from increased afterload
* Decreased receptor density and number

## Vascular Changes

* Reduced compliance\
Due to loss of elastic tissue in the large arteries.
* Increased SVR\
Reduced compliance results in increased vascular resistance.
* Reduced endothelial cell function (decreased NO)\
Impairs the ability of the vascular tree to adapt to changes in pressure/volume leading to:
    * Elevated SBP
    * Reduced DBP\
    Reduced elastic recoil causes diastolic run off and a fall in diastolic blood pressure.
* Reduced catecholamine receptor density\
Reduced responsiveness to (and increased number of) circulating catecholamines.

## Autonomic Changes

* Impaired autonomic function\
Due to decreased catecholamine responsiveness.
* Impaired baroreceptor response
* Decreased exercise tolerance\
Reliance on preload to maintain cardiac output.

---

## References

1. ANZCA February/April 2016
2. Cheitlin MD. [Cardiovascular physiology-changes with ageing](http://onlinelibrary.wiley.com/doi/10.1111/j.1076-7460.2003.01751.x/abstract). Am J Geriatr Cardiol. 2003 Jan-Feb;12(1):9-13.