# Hepatic Blood Flow

:::CICM
Describe the distribution of blood volume and flow in the various regional circulations and explain the factors that influence them, including autoregulation. These include, but not limited to, ~~the cerebral and spinal cord,~~ hepatic and splanchnic, ~~coronary, renal and utero-placental~~ circulations
:::

The liver serves as a blood reservoir (30ml per 100g, half of which may be mobilised in hypovolaemia), and receives **25%** of cardiac output from a unique dual blood supply:

* **Hepatic arterial system**
    * Supplies about **one-third** of blood, but 40-50% of O~2~\
    * **SpO~2~** of **~98%** (as would be expected)
    * High-pressure, high-resistance, high-flow system (average velocity 18cm.s^-1^)
    * Capacity to autoregulate
* **Portal venous system**
    * Supplies the remaining **two-thirds** of blood
    * **SpO~2~** of **portal venous blood varies** depending on gut activity:
        * In the **resting gut**, SpO~2~ is **~85%**
        * In the **active gut**, SpO~2~ is **~75%**
    * Low-resistance, low-pressure, low-velocity system (average flow 9cm.s^-1^)
    * No capacity to autoregulate

## Regulation of Flow

As with other organs, blood flow is autoregulated via intrinsic and extrinsic mechanisms, and may be affected by external factors.

### Intrinsic Autoregulation

* Myogenic autoregulation
* Hepatic arterial buffer response\
This is also known as the "hepatic artery-portal venous semi-reciprocal interrelationship".
    * Hepatic arterial resistance is proportional to portal venous blood flow, such that a reduction in portal venous flow causes a decrease in hepatic arterial resistance and increases hepatic arterial flow\
    This is probably mediated by adenosine.

### Extrinsic Autoregulation

* Autonomic Nervous System\
Both the hepatic and portal vasculature have sympathetic innervation:
    * The hepatic artery has dopamine receptors, as well as β- and α-adrenoreceptors
    * The portal vein has only α-adrenoreceptors\
    Activation of these receptors causes venoconstriction, reducing the compliance of the hepatic vasculature and mobilising up to **250ml** of blood in times of sympathetic stress.
* Endocrine and hormonal effects\
A number of substances affect portal flow:\

|      Hormone       | Portal Vein Effect |        Hepatic Artery Effect        | Overall Effect on Flow |
|--------------------+--------------------+-------------------------------------+------------------------|
| **Adrenaline**     | Constriction       | Constriction (α), then dilation (β) | Reduced                |
| **Glucagon**       | Dilation           | -                                   | Increased              |
| **Secretin**       | -                  | Dilation                            | Increased              |
| **Angiotensin II** | Constriction       | Constriction                        | Reduced                |
| **Vasopressin**    | Constriction       | Constriction                        | Reduced                |
| **PCO~2~**         | Constriction       | -                                   | Reduced                |


### External Factors

Flow in the hepatic vein is dependent on venous return:

* Increased venous return (e.g. negative-intrathoracic pressure) increases hepatic flow
* Decreased  venous return (e.g. positive-pressure ventilation, tamponade, haemorrhage), reduces hepatic flow, and in extreme cases flow may only occur intermittently throughout the cardiac cycle

* **Exercise** reduces both portal vein and hepatic arterial flow

## Microvasculature

Hepatic arterioles and portal venules form the **hepatic triad** with a bile canaliculi. Hepatic arterioles and venules anastomose to form **sinusoids**, which create a specialised low-pressure (~2mmHg) capillary system which drains into the central veins of the hepatic acinus.

This arrangement:

* **Optimises hepatic O~2~ extraction**  \
  Increased hepatic O~2~ demand is met by increasing O~2~ extraction, rather than by increasing flow (as occurs in the heart).
* **Prevents shunting and retrograde flow**

---

## References

1. CICM March/May 2013
2. Leslie RA, Johnson EK, Goodwin APL. Dr Podcast Scripts for the Primary FRCA. Cambridge University Press. 2011.
3. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
4. Kogire M, Inoue K, Sumi S, Doi R, Yun M, Kaji H, Tobe T. [Effects of gastric 
inhibitory polypeptide and glucagon on portal venous and hepatic arterial flow in
conscious dogs](https://www.ncbi.nlm.nih.gov/pubmed/1425064). Dig Dis Sci. 1992 Nov;37(11):1666-70.