# Starling Forces

:::CICM
Describe the essential features of the micro-circulation including fluid exchange (Starling forces) and control mechanisms present in the pre- and post-capillary sphincters
:::

Interstitial fluid is an ultrafiltrate of plasma, with the net filtration pressure determined by the net effect of opposing hydrostatic and oncotic pressures:

$$NFP = P_{Capillary \ Hydrostatic} - P_{Interstitial \ Hydrostatic} - (P_{Capillary \ Oncotic} - P_{Interstitial \ Oncotic})$$

These four variables are known as **Starling's forces**.

Actual fluid movement is (of course) more complicated. **Hydrostatic pressure falls along the capillary**, and movement of solute and water are affected by other factors. Some of these are described by the:

* **Reflection coefficient** (σ)\
This describes the fact that a small amount of protein leaks from the capillary, slightly increasing interstitial oncotic pressure and slightly decreasing capillary oncotic pressure. It is dependent on the interstitial protein content, and has a value between 0 and 1.

* **Filtration coefficient** (Kf)\
Encompasses membrane permeability (to water) and membrane surface area. Varies between tissues:

The **Starling Equation** becomes:

$$Net \ Fluid \ Movement =  K_f(P_{CH} - P_{IH} - \theta(P_{CO} - P_{IO})$$

### Typical Values for Pressures (mmHg)

|                                       | Arteriolar End | Venous End |
|---------------------------------------+----------------+------------|
| **Capillary Hydrostatic Pressure**    |             25 |         10 |
| **Interstitial Hydrostatic Pressure** |             -6 |         -6 |
| **Capillary Oncotic Pressure**        |             25 |         25 |
| **Interstitial Oncotic Pressure**     |              5 |          5 |

### Organ-Specific Values

In the glomerulus:

* Reflection coefficient is close to 1 due to the impermeability of the glomerulus to protein
* Kf is high due to both high permeability and a large surface area.
* Hydrostatic pressure is high
* Glomerular oncotic pressure is essentially 0

In the liver:

* Reflection coefficient is close to 0 in hepatic sinusoids as they are very permeable to protein

In the lungs:

* Reflection coefficient of ~0.5 in the lungs due to significant leak of protein
    * Protein leak decreases as interstitial oncotic pressure rises, limiting further oedema formation
* The oncotic pressure gradient is small, and favours reabsorption
* Hydrostatic pressure gradient is small, but favours extravasation of fluid
    * Interstitial hydrostatic pressure becomes more negative closer to the hilum, drawing fluid into the pulmonary lymphatics


## Causes of Oedema

Oedema can be localised or generalised, and in both cases caused by:

* **Increased filtration pressure**
    Occurs when capillary hydrostatic pressure exceeds interstitial hydrostatic pressure. Causes:
    * Increased Venous pressure\
    This includes an increase in CVP:
        * CCF
        * TR
        * Increased venoconstriction
        * Increased MSFP
    * Impaired venous return
        * Obstruction
        * Respiratory muscle pump
        * Skeletal muscle pump
    * Positioning
* **Decreased oncotic pressure gradient**
    * Decreased plasma protein
        * Hepatic failure
        * Critical Illness
    * Increased interstitial oncotic pressure
        * Mannitol/starch extravasation
* **Increased capillary permeability**
    * Inflammatory proteins
        * Substance P
        * Histamine
        * Kinins
* **Inadequate Lymph Flow**

---

## References

1. Barrett KE, Barman SM, Boitano S, Brooks HL. Ganong's Review of Medical Physiology. 24th Ed. McGraw Hill. 2012.
2. Brandis, K. [Starling's Hypothesis](http://www.anaesthesiamcq.com/FluidBook/fl4_2.php). Anaesthesia MCQ.
3. ANZCA August/September 2001