# Anticoagulants

```{r}
source("scripts/drugtables.R")

DrugTable("warfarin", "heparin", "enoxaparin")
```


## HITTs

**Heparin-Induced Thrombotic Thrombocytopenia** comes in two flavours:

* **Type I**:
    * Is non-immune mediated
    * Occurs within 4 days of anticoagulant doses
    * Is an isolated thrombocytopenia without clinical significance
* **Type II**:
    * Is immune mediated
    * Occurs within 4-14 days
    * Is associated with serious thrombosis and high mortality (typically from PE) and morbidity (from CVA and limb ischaemia)

## Protamine

Protamine is:

* A basic cationic protein derived from salmon sperm which combines with the acidic anionic heparin to form a stable, inactive salt in solution
* Cleared more rapidly than heparin\
Rebound anticoagulation may occur.

Adverse effects from protamine include:

* Anaphylaxis
* Direct (non-anaphylaxis) histamine release
    * Bronchospasm
    * Hypotension
* Pulmonary hypertension\
This can be profound and result in a dramatic increase in RV afterload and EDV, with a corresponding fall in LV preload (interventricular interdependence), leading to dramatic hypotension and arrest.
    * Mediated by thromboxanes
    * Due to **protamine-heparin complexes**, rather than protamine alone\
    Administration of protamine in absence of heparin does not lead to pulmonary hypertension.
* Anticoagulation\
When given in excess.


***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
3. ANZCA August/September 2011
4. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
