# Antiplatelets


*Note aspirin is included under [COX inhibitors](cox_inhibitors.md)*.

## Classification of Antiplatelet Agents

Antiplatelet agents can be classified by which stage of platelet function they affect:

* Adhesion
    * vWF inhibitors\
    e.g. Dextran 70.
* Activation
    * Prostacyclins\
    e.g. Epoprostenol.
    * Phosphodiesterase inhibition\
    e.g. Dipyridamole.
    * COX inhibitors\
    Prevent thromboxane A2 production, e.g. aspirin.
* Aggregation
    * ADP receptor antagonists\
    Prevent activation of GP IIb/IIIa receptors, e.g. clopidogrel.
    * GP IIb/IIIa receptor antagonists\
    Prevent platelet aggregation via fibrin linkages between GP IIb/IIIa receptors, e.g. tirofiban.

## Comparison of Common Antiplatelet Agents

|Property|Clopidogrel|Dipyridamole|Tirofiban|Prasugrel|Ticagrelor
|--|--|
|**Class**|ADP antagonist|Phosphodiesterase inhibitor|GP IIb/IIa antagonists|ADP receptor antagonist/thienopyridine|P2Y~12~-receptor antagonist|
|**Uses**|PVD, STEMI, NSTEMI, stent prophylaxis|CVA|UA, NSTEMI|ACS|ACS|
|**Route of Administration**|PO only|PO/IV|IV only|PO|PO|PO|
|**Mechanism of Action**|Irreversibly prevents ADP from binding to its receptor on the platelet, preventing activation of the IIb/IIIa receptor|Inhibits platelet adhesion to walls, potentiates prostacyclin activity and increases platelet cAMP, ↓ Ca^2+^ and inhibiting platelet aggregation and deformation. Also acts as a coronary vasodilator.|Reversible antagonism of IIb/IIIa receptor, preventing platelet aggregation|Irreversibly binds to P2Y~12~, preventing platelet activation and aggregation. Greater potency than clopidogrel.|**Reversible**, non-competitive binding to P2Y12-receptor|
|**Dosing**|300mg load, 75mg daily thereafter|200mg BD for CVA|Load 25 mcg.kg^-1^, maintenance 15mcg.kg^-1^|60mg load, then 10mg daily|180mng load, then 90mg BD|
|**Absorption**|Rapid absorption and onset within 2 hours|Variable depending on oral intake|IV only. Onset within 10 minutes||PO absorption within 2-4 hours|
|**Distribution**|Highly protein-bound drug and metabolites|Highly protein bound|65% protein bound||99% protein bound|
|**Metabolism**|**Prodrug**. Majority hydrolysed by esterases to inactive drug, with a small proportion hepatically metabolised by **CYP450** to active form. Half-life ~8 hours, however prolonged duration of action (5-7 days) due to irreversible effect on platelets|Partial hepatic to inactive metabolites|Not metabolised.|**Prodrug**, hepatic by CYP 3A4 and 2B6. Irreversible binding gives same duration of action as clopidogrel.|**Not** a **prodrug**; extensive metabolism with active metabolites with elimintation t~1/2~ ~ 8 hours. Clinical effect persists despite this for somet ime: ~60% activity at 24 hours and 10% activity at 5 days.
|**Elimination**|Urinary and faecal|Renal and faecal|Urinary as unchanged drug. Platelet aggregation returns to baseline within 4-8 hours|Majority eliminated in urine|Majority eliminated in faeces, minimal renal elimination|
|**CVS**||Vasodilatation may drop CPP in AS and recent MI|Coronary artery dissection|Fewer cardiovascular adverse events (stent thrombosis, revascularisation, MI) compared with clopidogrel|
|**GIT**|Mucosal irritation||||
|**Haeme**|Haemorrhage|Thrombocytopaenia and haemorrhage|Haemorrhage|Greater risk of bleeding compared with clopidogrel|
|**Other**|Many pharmacokinetic interactions, including genetic variability. Previously thought to kinetically interact with omeprazole - more recently disproved.|||Greater benefit in diabetic patients compared with clopidogrel or ticagrelor|

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.
3. Australian Prescriber. [Prasugrel](https://www.nps.org.au/australian-prescriber/articles/prasugrel). National Prescriber. 2010.
4. Dobesh PP, Oestreich JH. Ticagrelor: Pharmacokinetics, Pharmacodynamics, Clinical Efficacy, and Safety. Pharmacotherapy. 2014 Oct;34(10):1077–90. 
