# Direct Thrombin Inhibitors


Direct thrombin inhibitors prevent cleavage of fibrinogen to fibrin, and are therefore very effective anticoagulants.

|Property|Dabigatran
|--|--|
|**Class**|NOAC
|**Uses**|VTE prophylaxis, AF
|**Presentation**|75/110mg Capsules
|**Route of Administration**|PO
|**Dosing**|VTE: 220mg daily, AF: 150mg BD
|**Absorption**|6.5% bioavailability
|**Distribution**|35% protein bound
|**Metabolism**|Prodrug - activated by plasma and hepatic esterases
|**Elimination**|Renal elimination of active drug
|**Haeme**|Haemorrhage
|**Immune**|Allergy
|**Other**|Significant interactions with amiodarone, quinidine, St. John's Wort, as well as other anticoagulant and antiplatelet agents. Dialysable. Potentially reversible with idarucizumab.

---
## References

1. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
2. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
