# Protein Metabolism

:::CICM
Describe the physiology of ~~fat, carbohydrate and~~ protein metabolism
:::

**Essential amino acids** cannot be produced by transamination - they must be supplied in the diet.

## Metabolism

Protein **catabolism** involves the **deamination** of amino acids. Deamination can occur in one of two ways:

* **Oxidative deamination**\
Hepatic deamination, removing the amino group to create a ketoacid and ammonia. Ammonia produced in the liver enters the urea cycle and becomes urea, which requires **3 ATP**.
* **Transamination**\
Amino group is transferred by aminotransferases to another amino acid or a ketoacid to produce:
    * Keto acids, which:
        * Enter the citric acid cycle and produce ATP
        * Get converted to glucose or fatty acids
    * Amino groups
        * Enter the urea cycle and become urea

:::column-margin
Ammonia can also be produced in the kidney by the deamination of glutamate in the kidney. In this instance:

* It is eliminated directly in urine as ammonium
* Does not enter the urea cycle
:::

---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
