# Tocolytics


Tocolytics are agents which decrease uterine tone. Tocolytics include:

* [β~2~-agonists](beta_agonists.md)
* [Ca^2+^-channel antagonists](calcium_channel_blockers.md)
* [COX Inhibitors](cox_inhibitors.md)
* MgSO~4~
* Nitrates
* Volatile anaesthetic agents

All tocolytics are discussed in more detail elsewhere - this covers just the mechanism of action of their uterine effects.

|Drug|β~2~-agonists|Ca^2+^-channel antagonists|COX Inhibitors|
|--|--|
|**Example**|Salbutamol, Terbutaline|Nifedipine|Indomethacin
|**Mechanism of Action**|Activate GPCR, ↑ cAMP, which activates protein kinase A and leads to inhibition of myosin light chain kinase and relaxation|Block L-type Ca^2+^ channels, causing relaxation|Inhibit prostaglandin synthesis, which are vital for uterine contraction

---
## References

1. Diaz, A. [Describe the mechanism of action and side effects of three classes of drugs that are used to increase uterine tone, and three classes of drugs used to decrease uterine tone](https://icuprimaryprep.files.wordpress.com/2015/01/q24-describe-the-mechanism-of-action-and-side-effects-of-three-3-classes-of-drugs-that-are-used-to-increase-uterine-tone-and-three-3-classes-of-drugs-used-to-decrease-uterine-tone.pdf). Primary SAQs.