# Internal Jugular Vein

:::CICM
Describe the anatomy relevant to central venous access (including ~~femoral,~~ internal jugular, ~~external jugular, subclavian and peripheral~~ veins).
:::

:::ANZCA
Describe the anatomy and anatomical relations of the great veins relevant to performing central venous cannulation, including the ultrasound anatomy.
:::

The internal jugular vein:

* Originates at the **jugular bulb**\
This is a dilatation formed by the confluence of the inferior petrosal sinus and the sigmoid sinus.
* Exits the skull via the **jugular foramen**
* Descends laterally to the internal carotid (and later the common carotid) in the **carotid sheath**
* Terminates behind the sternal end of the clavicle, where it joins with the **subclavian vein** to form the **brachiocephalic vein**

## Borders

* Anteriorly by SCM
* Posteriorly by the lateral mass of C1, scalene muscles, and lung pleura
* Medially by the internal carotid

## Relationships

* Vagus nerve lies behind/between the carotid and IJV
* Cervical sympathetic plexus lies posterior to the carotid sheath
* Deep cervical lymph nodes lie close to the vein
* External jugular crosses the sternomastoid belly of SCM, running posteriorly and more superficial to the IJV, later perforating deep fascia to drain into the subclavian vein
* Pleura rises above the clavicle, and is close to the vein at its termination
* Thoracic duct passes lateral to the confluence of the left IJV and SCV, and may be injured during **left** IJV cannulation
    * The right lymphatic duct may be injured during right IJV cannulation, but due to its smaller size this is less common


## Surface Anatomy

Identify the triangle formed by the two heads of SCM and the clavicle. Palpate the artery, and ensure the site of entry is **lateral** to the carotid. Aim:

* Caudally, at a 30 angle to the frontal plane
* Parallel to the sagittal plane
* Towards the ipsilateral nipple


## Ultrasound Anatomy

Identify the vein deep to SCM, noting that it is (unlike the adjacent ICA):

* Non-pulsatile
* Thin walled
* Compressible


## Approaches

* Anterior\
At the medial border of SCM, 3-4cm above the clavicle. Requires retraction of the carotid medially.
* Central approach\
At the apex of the triangle formed by each muscle belly of SCM and the clavicle.
* Posterior approach\
At the posterior edge of SCM, just superior to where the EJV crosses the sternomastoid.


---

## References

1. McMinn, RMH. Last's Anatomy: Regional and Applied. 9th Ed. Elsevier. 2003.
2. http://radiopaedia.org/articles/internal-jugular-vein
3. http://www.frca.co.uk/article.aspx?articleid=100030
4. [Internal jugular vein catheterisation: Posterior and Central Approach](http://www.thecardiacicu.com/for_experts/jugular_intro_eng.html)