# Antipsychotics


Antipsychotics are drugs used for the management of psychoses and thought disorders. They have a complicated mechanism of action with effects on multiple receptors:

* Central dopamine (typically D~2~, but varies with agent) antagonism\
Responsible for the antipsychotic properties
* 5-HT~2~ antagonism


* Other receptors which are quantitatively less important:
    * H~1~ antagonism
    * α~1~ antagonism
    * Muscarinic ACh antagonism


Based on their affinity to various receptors, they are (loosely) classified as either:

* **Typical** or 1^st^ generation antipsychotics\
Higher affinity for D~2~ receptors (subsequently less blockade of 5-HT~2~), causing a greater effect on 'positive' symptoms' and a greater incidence of extrapyramidal side effects
* **Atypical** or 2^nd^ generation, which typically have fewer motor effects\
Have greater effect on negative symptoms.


: Common Features of Antipsychotics

|Property|Drug
|--|--|
|**Uses**| Behavioural emergencies, schizophrenia/psychosis
|**CVS**|QT prolongation
|**CNS**|Apathy, ↓ initiative, ↓ response to external stimuli, ↓ aggression. No loss of intellectual function. 
|**Endocrine**|↑ Prolactin (typical antipsychotics)
|**Haeme**|Leukopenia and agranulocytosis (predominantly clozapine, but can be all)
|**Metabolic**|Weight gain, diabetes, hypercholesterolaemia (all atypical > typical)
|**Other Toxicities**|Neuroleptic malignant syndrome, EPSE

### Neuroleptic Malignant Syndrome

**Antipsychotic Malignant Syndrome** is rare and presents similarly to MH, with a rapid rise in body temperature and confusion. It has a high mortality (up to 20%).

### Extra-Pyramidal Side Effects

Motor disturbances from antipsychotic use are termed EPSEs, and are divided into two main types:

* **Acute Dystonic Reactions** are involuntary movements and parkinsonian symptoms. They are:
    * More common with typical agents
    * Decline with ongoing use
    * Reversible with cessation of the agent

* **Tardive dyskinesia** is similar to ADR, except:
    * Involuntary movements are more pronounced and disabling
    * It occurs with long term use (10-20 years)
    * They are **irreversible**, and worsen when therapy is stopped



```{r}
source("scripts/drugtables.R")

DrugTable("haloperidol", "olanzapine", "clozapine", caption = "Comparison of Antipsychotics")
```

***

## References

Rang and Dale
Smith, Scarth, Sasada
Critical Care Drugs Manual http://lifeinthefastlane.com/book/critical-care-drugs/
https://dailymed.nlm.nih.gov/dailymed/archives/fdaDrugInfo.cfm?archiveid=8248
https://www.ncbi.nlm.nih.gov/pubmed/8453823
