# Anticonvulsants

> An understanding of the pharmacology of ~~anti-depressant, anti-psychotic,~~ anti-convulsant~~, and anti-Parkinsonian~~ medication

Anticonvulsants work via a number of different mechanisms:

## Sodium Channel Blockers

Sodium channel blockers:

* Stabilise the inactive state of the channel, preventing return to the active state and prevent generation of further action potentials\
This halts post-tetanic potentiation and limits the development of seizure activity.
* May also have Class I antiarrhythmic properties\
Due to Na^+^ blocking effects.
* Include:
    * Phenytoin
    * Carbamazepine
    * Lamotrigine

## GABA Mediators

GABA is the key inhibitory neurotransmitter in the CNS. GABA mediators:

* Enhance the effect of GABA\
Multiple potential mechanisms:
    *  Direct GABA-receptor agonists\
    e.g. Benzodiazepines and phenobarbital.
    * Positive allosteric modulation\
    e.g. Propofol and thiopentone.
    * GABA reuptake inhibition\
    e.g. Tiagabine.
    * GABA transaminase inhibition\
    e.g. Vigabatrin.
    * Increase GABA synthesis\
    e.g. Sodium Valproate.

## Glutamate Blockers

Glutamate is an important CNS excitatory neurotransmitter. Glutamate antagonists:

* Are generally avoided due to their side effect profile, which includes psychosis and hallucinations
* Include topiramate

## Other Agents

Gabapentin and pregabalin:

* Do not appear to mediate GABA
* Inhibit of excitatory α~2~δ voltage-gated calcium channels in the CNS\
This gives them anticonvulsant properties.


---

## References

1. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
2. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
3. [Medscape - Antiepileptic Drugs](http://emedicine.medscape.com/article/1187334-overview#showall). Accessed December 2015.
