# Benzodiazepines


Benzodiazepines are double-ringed positive allosteric modulators of the GABA receptors in the CNS. They:

* Bind to the α/γ interface of the receptor, increasing affinity of the receptor for GABA
* This leads to **hyperpolarisation** of the **cell membranes** and decreased neuronal transmission\
The mechanism varies between receptors:
    * GABA~A~ is a **ligand gated** post-synaptic Cl^-^ ion channel\
    Activation **increases Cl^-^ conductance** via **increasing frequency** of channel opening.
    * GABA~B~ is a pre- and post-synaptic **G-protein coupled** receptor\
    Activation **increases K^+^ conductance**.


## Common Features of Benzodiazepines

|Property|Action|
|--|--|
|**Uses**|Sedation, anxiolysis, hypnotic, anticonvulsants, amnestic, muscle relaxation|
|**Absorption**||
|**Distribution**|Highly lipid soluble and protein bound, very low V~D~|
|**Metabolism**|Generally active metabolites.
|**Elimination**|Renal elimination of active and inactive metabolites.
|**Resp**|↓ V~T~, ↑RR, apnoea.
|**CVS**|↓ SVR, ↓SBP, ↓ DBP, ↑HR. Typically stable CO.
|**CNS**| Hypnosis, sedation, anterograde amnesia, anticonvulsant, ↓ CBF. ↓ MAC.
|**MSK**|Skeletal muscle relaxation.
|**Metabolic**|↓ Adrenergic stress response.

## Comparison of Benzodiazepines

|Property|Midazolam|Diazepam|Clonazepam|
|--|--|
|**Physicochemical**|pKa 6.5. Structure is dependent on surrounding pH - at a pH < 4 its ring structure opens and it becomes water soluble.|40% propylene glycol.||
|**Route of Administration**|PO/IV/IM.|PO/IV/IM.|PO.|
|**Absorption**|50% PO bioavailability.|Good PO bioavailability.||
|**Distribution**|V~D~ 1.5L.kg^-1^, 95% protein bound.|95% protein bound.||
|**Metabolism**| Partially metabolised to oxazepam and 1-α-hydroxy-midazolam. Clearance ~7ml.kg^-1^.min^-1^.|Hepatic to all active metabolites including oxazepam, temazepam, and des-methyl-diazepam (has t~1/2~β up to 100 hours).|Hepatic to inactive metabolites.|
|**Elimination**|t~1/2~β 2-4 hours, prolonged with cirrhosis, CHF, obesity and in the elderly.|t~1/2~β 20-45 hours.||

---
## References

1. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
2. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
4. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.