# Neuraxial Blockade

:::dual
Describe the physiological consequences of a central neuraxial block
:::

Central neuraxial blockade refers to blockade of fibres in the spinal cord by administration of intrathecal or epidural local anaesthetic.

## Respiratory Responses

An increasing level of block will lead to greater effects:

* Thoracic\
    * Impediment to active expiration and expectoration due to blockade of intercostals and abdominal wall musculature
    * Loss of vital capacity
    * Loss of some accessory muscle use
* Cervical\
Impediment due to diaphragmatic blockade.
    * Shoulder weakness with C3-C5 spread may warn of impending respiratory compromise

## Cardiovascular Responses

Occur due to blockade of sympathetic chain fibres in the thoracolumbar region.

An increasing level of block will lead to greater effects:

* Sacral\
Parasympathetic blockade only. Minimal CVS effects.
* Lower thoracic/lumbar\
Arteriolar and venous vasodilation in lower abdomen and lower limbs, causing a fall in SVR, BP, and GFR.
* Upper thoracic\
Loss of cardioaccelerator fibres above T5, causing a reduction in heart rate and contractility, compounding hypotension due to fall in SVR.
* Cranial Nerves\
Vagal blockade will reduce PNS tone and attenuate some of the loss of SNS tone.
* Brainstem\
Inhibition of vasomotor centre with profound fall in CVS parameters.

## CNS Responses

An increasing level of block will lead to greater effects:

* Cervical\
Horner's syndrome (miosis, anhydrosis, ptosis) due to loss of sympathetic trunks.
    * Spread to C6-C8 may cause numbness, paraesthesia and weakness in the hands and arms
* Cranial nerve
Pupillary dilation due to CN III blockade.
* Brainstem and Cerebral Cortex 
Anaesthesia due to blockade of the reticular activating system and thalamus. 
    * Intracranial spread may cause slurred speech and sedation

***

## References

1. Diaz, A. [Cardiovascular Response to Central Neuraxial Blockade](https://primarysaqs.files.wordpress.com/2009/12/2007b9briefly-explain-the-cvs-responses-to-central-neural-blockade.pdf). Primary SAQs.
2. ANZCA July/August 2007
3. [High or total spinal anesthesia](https://www.nysora.com/anesthesia/high-or-total-spinal-anesthesia/). NYSORA.
