# Nitrous Oxide

:::dual
Describe the pharmacology of nitrous oxide
:::

:::dual
Describe the comparative pharmacology of nitrous oxide, ~~halothane, enflurane, isoflurane, desflurane, sevoflurane, xenon and ether~~
:::


```{r}
source("scripts/drugtables.R")

DrugTable("nitrous_oxide")
```

## Entonox


Entonox is a 50/50 mixture of nitrous oxide and oxygen, used as analgesia in labor and minor procedures.

+--------------------------------------+-----------------------------------------------------------------------------------------------------------+
| Property                             | Entonox (50% O~2~, 50% N~2~O)                                                                             |
+======================================+===========================================================================================================+
| **Pharmaceutics**                    | The gases dissolve each other and behave differently than would be expected from their individual         |
|                                      | properties. This is the **Poynting effect**.                                                              |
+--------------------------------------+-----------------------------------------------------------------------------------------------------------+
| **Critical Temperature/Pressure**    | *Pseudo*critical temperature of **-6°C**, below which it will separate into **liquid** 50% N~2~O (with    |
|                                      | some dissolved O~2~), and gaseous O~2~. This is most likely to occur at 117 bar, and can lead to delivery |
|                                      | of a hypoxic mixture.                                                                                     |
|                                      |                                                                                                           |
|                                      | Delivery of a hypoxic mix is prevented by:                                                                |
|                                      |                                                                                                           |
|                                      | - Storing cylinders horizontally (↑ area for diffusion)                                                   |
|                                      | - Storing cylinders at temperatures > 5°C                                                                 |
|                                      | - Using a dip tube so that liquid 50% N~2~O is used before the gaseous mixture                            |
+--------------------------------------+-----------------------------------------------------------------------------------------------------------+

***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
3. ANZCA February/April 2006
4. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
5. Emmanouil DE, Quock RM. [Advances in Understanding the Actions of Nitrous Oxide](http://www.anesthesiaprogress.org/doi/abs/10.2344/0003-3006%282007%2954%5B9%3AAIUTAO%5D2.0.CO%3B2). Anesthesia Progress. 2007;54(1):9-18. doi:10.2344/0003-3006(2007)54[9:AIUTAO]2.0.CO;2.
6. Hendrickx, J., Peyton, P., Carette, R., & De Wolf, A. (2016). [Inhaled anaesthetics and nitrous oxide](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2614651/). European Journal of Anaesthesiology, 33(9), 611–619.
7. Brown S, Sneyd J. [Nitrous oxide in modern anaesthetic practice](https://academic.oup.com/bjaed/article-pdf/16/3/87/9436668/mkv019.pdf). 2016. BJA Education, 16(3), 87–91.
