# Propofol


Propofol (2-6 di-isopropylphenol) is a phenolic derivative with effects on many receptors including:

* GABA~A~\
Potentiates the effect of GABA, prolonging Cl^-^ channel opening and hyperpolarising the cell.
* Glycine
* Nicotinic ACh
* D~2~ receptors


|Property|Action|
|--|--|
|**Class**|Phenolic derivative|
|**Uses**|Induction of anaesthesia, sedation, TIVA|
|**Presentation**| White oil-in-water emulsion at a **pH of 7-8.5** containing:<br>- 10-20mg.ml^-1^ propofol<br>- 10% Soybean oil (solubilising agent)<br>- 1.2% Purified egg phosphatide (emulsifier) <br>- 2.25% Glycerol (for tonicity)<br>Bacteriostatic additives including:<br>- Generics: Sodium metabisulfite<br>- Diprivan: Disodium edetate (less allergenic)<br>  Risk of bacterial contamination limits shelf life.<br> Energy content is 1.1kcal.ml^-1^|
|**pKa**| 11 - almost all is unionised (and active) at physiologic pH|
|**Route of Administration**|IV only|
|**Dosing**|Induction: 1-2.5mg.kg^-1^ Maintenance: 4-12mg/kg/hr. Target plasma concentration of 4-8μg.ml^-1^ to maintain general anaesthesia|
|**Distribution**|98% protein bound. Very high V~D~ at 4L.kg^-1^. Rapid initial distribution: t~1/2~α (fast) 1-3 minutes, intermediate distribution t~1/2~α (slow) 30-70 minutes. t~1/2~ke0~~ of **2.7** min.|
|**Metabolism**| Hepatic and extra-hepatic metabolism to inactive glucuronides and sulphates; t~1/2~β 2-12 hours. **Clearance** of <strong>30-60ml.kg.min^-1^</strong>, unaffected by renal and hepatic disease. Context sensitive half-time peaks at **50 minutes** following a 9 hour infusion.|
|**Elimination**|Tri-exponential. Renal elimination of inactive metabolites.|
|**Resp**|Respiratory depression, apnoea. Strong suppression of laryngeal reflexes. ↓ Response to hypoxia and hypercapnea. Bronchodilation.
|**CVS**|↓ Arterial and venous vasodilation (via stimulating NO release) causing ↓ SVR and ↓ VR, with ↓ BP. ↓ Inotropy via ↓ in SNS tone, ↓ MVO~2~. Depresses baroreceptor reflex. Pain on injection due to lipid emulsion.|
|**CNS**|Hypnosis. Rapid LoC (within 1 arm-brain circulation time). ↓ CMRO2, CBF, and ICP. Anticonvulsant. ↓ IOP. Paradoxical excitatory effects seen in ~10% - dystonic movements of subcortical origin. EEG demonstrates non-specific seizure-like activity.|
|**MSK**|Pain on injection into small veins|
|**Renal**|Green urine|
|**GIT**|Anti-emetic. ↓ Hepatic Blood Flow|
|**Metabolic**|Fat overload syndrome, lipaemia following prolonged infusion. Inhibits mitochondrial function.|
|**Toxic Effects**|Propofol infusion syndrome: Acidosis, bradycardia, and MODS following prolonged infusion (>24 hours), particularly with high doses (>4mg.kg^-1^.hr^-1^), in children, and potentially in the presence of mitochondrial defects. Believed due to inhibition of mitochondrial function.|


---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. CICM July/September 2007
http://ceaccp.oxfordjournals.org/content/4/3/76.full.pdf
http://www2.pedsanesthesia.org/meetings/2007winter/pdfs/Morgan-Friday1130-1150am.pdf