---
level: 3
---

# Acid-Base Balance

:::CICM
Describe the role of the kidneys in the maintenance of acid/base balance
:::

Acids produced by the body can be:

* **Volatile** (CO~2~)\
    * Body produces and eliminates <strong>~13-20mol.day^-1^</strong>
    * Removed by the lungs
* **Fixed** (everything else)
    * Include lactate, sulphate, phosphate, and ketones
    * Body produces and eliminates <strong>10mmol.kg^-1^.day^-1^</strong>
    * Eliminated by the kidney\
    Mechanisms for elimination of acid include:
        * Reabsorption of HCO~3~^-^\
        This is equivalent to the removal of the same amount of H^+^.
        * As there is usually a net production of acid, under normal circumstances **all filtered HCO~3~^-^ is reabsorbed**
        * Note that removal of an acid load is associated with greater HCO~3~^-^ generation and reabsorption, not increased H^+^ secretion 
        * Bound to filtered buffers
        * As ammonium
    * The rate and extent of these reactions is dependent on ECF pH and ion concentrations, which gives the kidney control over ion concentrations
    * Urinary pH can fall as low as ~4.4, before the active transport of H^+^ is inhibited


## Bicarbonate and the Kidney

Buffer systems minimise changes in pH until the kidney can eliminate excess hydrogen.

Bicarbonate is the predominant ECF buffer system (see [Acid-Base physiology](principles-of-acid-base-physiology.md) for more on buffers). By adjusting the level of HCO~3~^-^ the kidney is able to adjust pH, as per the Henderson-Hasselbalch equation:

$$\begin{aligned}
pH &= pK_a + log{[HCO_3^-] \over [CO_2]} \\
&= 6.1 + log{24 \over 1.2} \\
&= 7.4
\end{aligned}$$

Where:

* $pK_a$= 6.1, the pKa of HCO~3~^-^
* $[HCO_3^-]$= 24, the normal [HCO~3~^-^] in mmol.L^-1^
* $[CO_2]$= 1.2, the normal [CO~2~] in mmol.L^-1^

Bicarbonate is:

* Freely filtered\
4320 mmol.day^-1^ of HCO~3~^-^ is filtered (24mmol.L^-1^ x 180 L.day^-1^, normal range is 4-5mol.day^-1^)
* Reabsorbed in the PCT (90%), thick ascending limb, DCT, and CT\
Adjusting rate of absorption allows correction of an acidosis or alkalosis. All **HCO~3~^-^ reabsorption is equivalent to a loss of H^+^**.

### Reabsorption of Bicarbonate

Reabsorption of bicarbonate involves several steps:

* H^+^ is secreted into the lumen in one of three ways:
    * Primary H^+^ ATPase in the PCT and DCT
    * H^+^-Na^+^ antiporter in the PCT and ascending limb
    * H^+^-K^+^ ATPase in the CT
* Secreted H^+^ combines with filtered HCO~3~^-^ to form CO~2~ and H~2~O
* CO~2~ and H~2~O diffuse into the tubular cell
* CO~2~ and H~2~O are converted back into HCO~3~^-^ and H^+^ in the tubular cell
* HCO~3~^-^ is reabsorbed into the capillary via the HCO~3~^-^-Cl^-^ antiporter, and the H^+^ ion is available to be secreted into the tubule (in exchange for K^+^ in the collecting ducts and Na^+^ in the proximal tubule)

This complicated process allows HCO~3~^-^ to be moved from the tubule to the tubular cell and then to the capillary. **There is no elimination of H^+^** by this method - the purpose of H^+^ secretion is to facilitate the **reabsorption of HCO~3~^-^** into the tubular cell.

## Ammonia

Glutamine provides a mechanism for elimination of a large number of H^+^ ions:

* This is important in:
    * Elimination of excess metabolic acid
    * Renal compensation for acidosis
* This occurs via:
    * Filtered glutamine is absorbed into **proximal tubular cells** and metabolised to NH~4~^+^ (ammonium) and HCO~3~^-^
    * HCO~3~^-^ diffuses into blood, and the NH~4~^+^ is secreted into the tubule via the NH~4~^+^-Na^+^ antiporter and eliminated in urine\
    * The $NH_3 + H^+ \Leftrightarrow NH_4$reaction has a pKa of 9.2 meaning:
        * Ammonia cannot act as an effective urinary buffer
        * Ammonia is not a **titratable acid**, as it will not release H^+^ ions as urinary pH increases\
        This means filtered ammonia does not contribute to the lower limit of urinary pH (4.4), which is why it is so important in the renal correction of severe metabolic acidosis.

## Bound to Filtered Buffers

Secreted H^+^ may also combine with a filtered buffer (e.g. PO~4~^3-^). **These H^+^ ions are not reabsorbed**. About **36mmol** of H^+^ is eliminated with filtered PO~4~^3-^ each day, with each PO~4~^3-^ binding **two** H^+^ ions.

---

## References

1. CICM Sep/Nov 2014
2. ANZCA Feb/April 2012
3. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
4. [Acid-Base Online Tutorial, University of Conneticut](http://fitsweb.uchc.edu/student/selectives/TimurGraham/Bicarbonate_reabsorption.html)
5. Brandis, K. [Renal Regulation of Acid-Base Balance](http://www.anaesthesiamcq.com/AcidBaseBook/ab2_4b.php), in 'Acid-base pHysiology'.