---
level: 3
---

# Dialysis

Dialysis is the **separation of particles in a liquid based on their ability to pass through a membrane**. 

## Indications

Failure of normal renal functions, i.e.:

* **A**cid
* **E**lectrolyte derangement\
Particularly hyperkalaemia.
* **I**ntoxications
* **O**verload
* **U**raemia

## Physical Mechanisms

Principles underlying the methods of dialysis include:

* **Diffusion**\
Diffusion is the **spontaneous movement of substances from a higher concentration to a lower concentration**, where rate of movement is proportional to the concentration gradient (as per Fick's Law).
* **Ultrafiltration**\
Movement of water, as determined by Starling's Forces.
* **Convection**\
Movement of solute together with a solvent, due to the frictional forces between pulling dissolved substances along. Also known as  bulk flow or **solvent drag**. Responsible for clearance of many small molecules during haemofiltration.

## Implementation

* **Haemodialysis**\
Uses diffusion.\
    * Blood is pumped through an extracorporeal circuit that contains a dialyser.
    * Dialysate flow is countercurrent, which maximises the gradient for diffusion.
    * Solutes move across a membrane between blood and dialysate, as per Fick's Law:
        * Concentration gradient between blood and dialysate
            * Flow rate of blood and dialysate
        * Solubility of the solute
            * Mass
            * Charge
            * Protein binding
        * Dialysis membrane permeability
            * Thickness
            * Porosity
            * Surface area

* **Haemofiltration**\
Uses ultrafiltration.\
    * Both a positive hydrostatic pressure in blood and a negative hydrostatic pressure in dialysate is generated, causing ultrafiltration and removal of solutes via solvent drag.
    * Elimination via bulk flow is **independent of solute concentration gradients across the membrane**.
    * Transport is dependent on Starling Forces:
        * The transmembrane pressure generated\
        This is a function of:
            * Blood flow to the membrane\
            Determines hydrostatic pressure.
            * Oncotic pressure gradient
        * Porosity of the membrane
    * Additionally, a high filtration fraction will cause excessive haemoconcentration, and clotting of the filter
    * The filtered fluid (ultrafiltrate) is discarded, and replaced with another fluid depending on the desired fluid balance.

### Differences

* Renal Replacement Therapy (RTT) can be via:
   * Peritoneal dialysis (PD)
   * Intermittent haemodialysis (IHD)\
   IHD causes greater cardiovascular instability compared to CRRT as the fluid and electrolyte shifts occur more rapidly.
   * Continuous Renal Replacement Therapy (CRRT)
        * Continuous Veno-Venous Haemofiltration (CVVH)
        * Continuous Veno-Venous Haemodiafiltration (CVVHDF)

Method chosen depends desired effect:

* Small molecules (<500 Da) and electrolytes can be removed by filtration or dialysis
* Medium-sized molecules (500-5000 Da) are best removed by filtration
* Low molecular weight proteins (5000-50000 Da) are removed by filtration\
This includes removal of inflammatory proteins, which may be beneficial in sepsis.
* Water is best removed by filtration

## Pharmacokinetics of RRT

Pharmacokinetics are unpredictable, but are broadly affected by:

* **Drug factors**
    * **Free drug in plasma**\
    Drugs with a small proportion of free drug in plasma are (unsurprisingly) poorly removed by RRT (but **may be removed via plasmapheresis**). These include:
        * Highly (> 80%) protein bound substances\
        Examples included phenytoin, warfarin, and many antibiotics.
            * Not that this **may not apply in overdose**\
            Once protein binding sites are saturated, both free drug fraction and efficacy of dialysis is increased.
            * Drugs with a V~D~ greater than 1L.kg^-1^
    * **Size/Molecular Weight**\
        * Small molecules (< 500 Da) are more easily cleared by diffusive methods of RTT
        * Molecules > 15kDa are poorly dialysed\
        This includes proteins, heparins, and monoclonal antibodies.
    * **Volume of distribution**\
    Drugs with high volumes of distribution are poorly dialysed, as removal of drug from plasma only removes a small proportion of total-body drug content.

* **Dialysis factors** 
    * **Dose/Flow rates**\
    Reduced flow rates will reduce clearance.
        * Conventional high-flux haemodialysis has more rapid clearance compared to lower-flux haemoperfusion or CRRT
    * **Membrane permeability**\
    * **Timing**\
    Drugs given between IHD or SLED sessions will not be cleared until the next session.s

* **Patient factors**
    * **Residual renal function**\
    Patients residual GFR will also affect pharmacokinetics.


### An Incomplete List of Drugs 

|                           Drugs Removed on RRT                           | Drugs not removed on RRT |
+--------------------------------------------------------------------------+--------------------------+
| Barbiturates                                                             | Digoxin                  |
| Lithium                                                                  | TCAs                     |
| Aspirin                                                                  | Phenytoin                |
| Sotalol/Atenolol                                                         | Other beta-blockers      |
| Theophylline                                                             | Gliclazide               |
| Ethylene Glycol                                                          | Benzodiazepines          |
| Methanol                                                                 | Warfarin                 |
| Aminoglycosides, metronidazole, carbapenems, cephalosporins, penicillins | Macrolides, quinolones   |

---

## References

1. Johnson CA, Simmons WD. [Dialysis of Drugs](http://www.just.edu.jo/DIC/Manuals/Dialysis%20of%20Drugs.pdf). Nephrology Pharmacy Associates.