---
level: 3
---

# Glomerular Filtration and Tubular Function

:::CICM
Describe glomerular filtration and tubular function.
:::

## Glomerulus

* The **glomerulus** is a set of capillaries which invaginate **Bowman's capsule**
* Fluid filters out of the capillary bed into Bowman's space based on **Starling forces**:
  * Membrane permeability
  * Hydrostatic pressure gradients
  * Oncotic pressure gradient
    * Reflection coefficient

### Glomerular Filtration Rate

**Glomerular Filtration Rate** is:

* The volume of *plasma* filtered by the glomerulus each minute\
Normal renal *blood* flow is 1.1 L.min^-1^, however renal *plasma* flow is less (600 ml.min^-1^ for a normal haematocrit). Therefore, the normal filtration fraction (proportion of renal blood flow which is filtered) is ~20%.
* Typically **125ml.min^-1^**\
    * Decreases with age (partially due to loss of nephron number)


GFR can be expressed as the **product** of **Net Filtration Pressure** and the combination of membrane permeability and membrane surface area, designated **K~f~** (the filtration coefficient):

$GFR = NFP \times K_f$

* **Net Filtration Pressure** is given by opposing **Starling Forces** across the glomerular membrane:
    $NFP = P_{Glomerular \ Hydrostatic} - P_{Bowman's \ Hydrostatic} -P_{Glomerular \ Oncotic}$\
    * The average capillary NFP is ~17mmHg^[As protein is not filtered in normal states, the oncotic pressure in Bowman's Space is usually assumed to be 0mmHg.]
    * **Hydrostatic pressure**\
    Determined by renal blood flow and the relative constriction of the **afferent** and **efferent** arterioles. Hydrostatic pressure **decreases along the capillary**, and is affected by:
        * MAP
            * Catecholamines
            * Local autoregulation
                * Myogenic
                * Tubuloglomerular Feedback
                * Hormones
                    * Angiotensin II constricts the efferent arteriole more than the afferent arteriole, causing an increase in renal resistance with only a small decrease in GFR.
                    * Prostaglandin E2 dilates the afferent arteriole, increasing GFR <br> <br>
    * **Osmotic pressure**\
    **Increases along the capillary**, as protein free-fluid is filtered leaving a higher concentration of protein within the capillary. This change in capillary oncotic pressure is proportional to the filtration fraction - a greater filtration fraction will cause a higher oncotic pressure of fluid in the capillary.


* **Membrane permeability**\
Overall permeability is:
    * A function of:
        * Membrane permeability, in turn affected by:
            * **Capillary endothelium**
            * **Basement membrane**\
            **Negatively charged** molecules have **reduced filtration** as the basement membrane is also negatively charged which opposes movement out of the capillary.\
            * **Foot processes** of podocytes\
            Molecules **less** than **7000 Dalton** are **freely filtered**, whilst larger molecules are filtered less.
            * Membrane Surface Area\
            Typically very high for water and solutes. 
    * Affected by:
        * Glomerulonephritis
            * Change in basement membrane or podocyte foot processes
        * Angiotensin II causing contraction of mesangial cells


## Tubular Function

### Proximal Tubule

The proximal tubule reabsorbs 60% of glomerular filtrate. It **reabsorbs basically everything**, including protein, and secretes H^+^, organic ions (such as uric acid and salicylates), ammonium, and up to 60% of filtered urea load.


### Loop of Henle

The loop of Henle consists of a **thin descending limb** and a **thick ascending limb**:

* The descending limb reabsorbs water only
* The thick ascending limb:
  * Reabsorbs common ions (Na^+^, K^+^, Cl^-^) and HCO~3~^-^
  * Excretes H^+^
* The function of the loop is to concentrate urine in states of water deprivation\
This is done via the countercurrent mechanism.

#### Countercurrent Multiplier

The countercurrent concentrating system is:

* Formed from the loop of Henle and collecting ducts
* Driven entirely by the removal of NaCl from the ascending limb
* Most easily understood in stages:
  * NaCl is actively transported out of the thick ascending limb, increasing interstitial osmolality *at that level*
  * Increased interstitial osmolality results in water reabsorption from the descending limb, increasing tubular osmolality *at that level*
  * This more concentrated tubular fluid then flows to a deeper, more concentrated level, and more water is reabsorbed
  * The effect is progressive concentration of tubular and interstitial fluid, but with a low and stable energy cost as the relative gradients that each transport pump works against is small
  * The end result is a dilute urine leaving the ascending limb, but a highly concentrated medullary interstitium

#### Countercurrent Exchange

The **vasa recta** are peritubular capillaries that:

* Surround the loop of Henle of juxtamedullary nephrons
* Follow the loop into the medulla
* Have typically low blood flow\
This prevents "washout" of the countercurrent multiplier, as the slow blood flow allows solute concentrations to equalise at each level of the loop.
  * In hypovolaemic situations, renal blood flow falls and vasa recta flow decreases, further reducing washout
  * When renal blood flow is high, vasa recta flow increases\
  This washes out part of the medullary concentration gradient and reduces the concentrating ability of the kidney.

### Distal tubules

Fluid entering the distal tubule has about **one-third** the **osmolarity** of plasma. The distal tubule:

* Reabsorbs: Na^+^, Cl^-^, HCO~3~^-^, Ca^2+^
* Secretes: K^+^, H^+^

### Collecting Ducts

* The collecting ducts lie in the interstitium (concentrated by the loop of Henle)
* In the absence of aquaporins, the collecting ducts are **impermeable to water**
  * Osmolality can fall as low as **50 mmol.L^-1^** due to continued reabsorption of solute
  * In the presence of aquaporins, water flows down the osmotic gradient into the concentrated interstitium, resulting in a highly concentrated urine
  * ADH also **increases** collecting duct permeability of **urea**
    * Urea moves via solvent drag with water

---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
2. Greger R, Windhorst U. Comprehensive Human Physiology: From Cellular Mechanisms to Integration. Springer-Verlag Berlin Heidelberg. 1996. 
3. CICM March/May 2010

