# Sodium and Water

:::CICM
Describe the function, distribution, regulation and physiological importance of sodium~~, chloride, potassium, magnesium, calcium and phosphate~~ ions
:::

Normal total body Na^+^ is 60mmol.kg^-1^, 70% of which is exchangeable. Total body Na^+^ is distributed as:

* 50% in ECF\
Sodium is the dominant extracellular cation.
  	* Typical ECF [Na^+^] of 140mmol.L^-1^.
* 45% in bone
* 5% in ICF\
A minor intracellular cation.\
  	* ICF [Na^+^] varies with cell type, but is typically 12-20mmol.L^-1^.
  	* Concentration is kept low by the action of the 2Na^+^-3K^+^ ATPase exchange pump and the low permeability of the cellular membrane to Na^+^


## Function of Sodium

* **Regulation of ECF volume**\
Principal ECF cation. Changes in sodium levels cause compensatory fluid shifts. Loss of sodium *content* will result in hypotension/hypovolaemia, with consequent baroreceptor stimulation and activation of the RAAS. Baroreceptors will activate with a **7-10% change in volume**.

* **Osmolarity**\
Changes in sodium *concentration* affect osmoreceptors and will affect ADH and thirst mechanisms. Osmoreceptors will activate with a **1-2% change in osmolality**.
* **Acid-Base balance**\
Na^+^-H^+^ exchange pumps in the kidney are stimulated in acidosis.

* **Resting Membrane Potential**\
Alterations in sodium concentration will affect intracellular potassium to a similar degree, which will alter the RMP.

## Regulation of Sodium and Water

Regulation of any system is typically a balance between **input** and **output**:

* Sodium intake is **essentially unregulated**
* Therefore, sodium concentration is a function of:
	* Sodium elimination
	* Sodium reabsorption
	* **Water homeostasis**\
	Control of total body water is a major mechanism to regulate sodium concentration.


### Sodium Elimination

Sodium is eliminated in:

* Sweat and GIT\
Obligatory and not amenable to regulation.
	* Acclimatisation to hot environments improves the efficiency of sweating by reducing its tonicity, reducing sodium loss
* GIT
* Urine\
	* Adjust renal elimination is the main mechanism to regulate sodium concentration\
	Can be performed in two ways:
		* **Changes in GFR**\
		Changes in GFR due to hyper or hypovolaemia will (indirectly) adjust sodium elimination. Increased plasma volume increases GFR, and vice versa.
		* **Changes in sodium reabsorption**\
		This is the main mechanism for controlling sodium in euvolaemia, and is mediated primarily by **aldosterone**.


### Sodium Reabsorption

Given that:

* Normal glomerular filtrate is ~180L.day^-1^ 
* The dominant osmole in glomerular filtrate is sodium
* Normal urine output is ~1.5L^-1^


The majority of filtered sodium must be reabsorbed. This is called **bulk reabsorption** and occurs in the PCT and LOH:

* 60% of total reabsorption is by the Na^+^-K^+^ ATPase pump in the PCT
* 30% of total reabsorption is by the Na^+^-K^+^-2Cl^-^ co-transporter in the LOH


The remaining 10% of sodium reabsorption occurs in the DCT and CT. As it is under the influence of aldosterone, it is the component which is important in regulation. Aldosterone increases Na^+^ reabsorption by increasing the number or activity of these pumps:

* Na^+^-Cl^-^ pumps in the DCT
* Na^+^-K^+^ ATPase pumps in **principal cells** of the DCT
* Na^+^-H^+^ pumps in **intercalated cells** of the CT


### Water Homeostasis

Body water homeostasis involves:

* Sensors\
Osmoreceptors present in the:
	* Macula densa\
	* Circumventricular organs\
	Subfornical organ and the vascular organ of the lamina terminalis.
		* Change in cellular volume secondary to changes in osmolality alter hormone secretion.
* Effectors\
Predominantly hormonal:
	* [ADH](pituitary_and_hypothalamus.md#pit)\
	* [RAAS](endocrine_functions_of_the_kidney.md#raas)
	* [Natriuretic peptides](adrenal-hormones.md#min)


---

## References

1. Brandis K. [The Physiology Viva: Questions & Answers](http://www.anaesthesiamcq.com/vivabook.php). 2003.
2. CICM September/November 2014
3. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
4. National Research Council. [Recommended Dietary Allowances](https://www.nap.edu/catalog/1349/recommended-dietary-allowances-10th-edition). 10th Ed. 1989. National Academies Press.