# 2020A Question 7

Describe the anatomy of the neonatal airway, and what implications this has for airway management.


## Examiner Report

70.1% of candidates achieved a pass in this question.


The question incorporated two parts - description of the neonatal airway and implications of the mentioned features on airway management. This was concisely and effectively communicated by a two or three column table.


Important points to address were the size and shape of the occiput, the relative size of the tongue to the oral cavity, a description of the epiglottis, the position of the larynx and a description of the shape and relative size of the larynx and cricoid. With relatively few facts being required to pass the question it was important to use precise language in the description of each feature


Common errors included the use of imprecise or vague descriptions of anatomical features or failing to describe the implication of each feature on airway management. Descriptions of airway features of the neonate which were self-evident (for example, the airway is small), without explanation of the implication, failed to attract marks.


Many candidates provided lengthy descriptions of features of the neonatal cardiorespiratory system which were not related to the airway. No marks were awarded for this information.

## Model Answer

Structure:

- Upper airway
- Lower airway
- Other

## Upper Airway


|Property|Consequence|
|--|--|
|<p>Narrow upper airways:</p><p>- Narrow nasal passages</p><p>- Large tongue</p><p>- Narrow pharynx</p>|<p>- ↑ Resistance. Provides auto-PEEP</p><p>- Guedel airway useful during mask ventilation</p>|
|<p>Obligate nose breather because of</p><p>- Large tongue</p><p>- High laryngeal inlet (C3-4 cf. C6)</p>| Any nasal obstruction = dangerous|
|Prominent occiput:|<p>- Tendency for flexion → Obstruction</p><p>- Folded towel under shoulders for bag-mask vent and intubation</p>|


## Lower Airways


|Property|Consequence|
|--|--|
|<p>Narrower lower airways</p><p>- Includes larynx, trachea and bronchi<br>  Resistance 25cmH~2~O/L/s on day 2</p><p>- Previously believed that the narrowest point cricoid ring; newer research suggests this is not the case</p>|<p>- Any further obstruction = dangerous</p><p>- Risk of subglottic stenosis with prolonged intubation</p>|
| Epiglottis long, U shape, floppy|<p>- Can be bypassed using straight bladed laryngoscope (Miller)</p><p>- Risk of glottic obstruction by misplaced LMA</p>|
|<p>- Laryngeal inlet is high C3-4 and anterior</p><p>- Larynx </p>| Different intubation mechanics|
| Short trachea|<p>- Risk of endobronchial intubation during neck flexion</p><p>- Risk of accidental extubation during neck extension</p>|


### Other


|Property|Consequence|
|--|--|
|Risk of oxygen toxicity|<p>- Bronchopulmonary dysplasia</p><p>- (Other: Retinopathy of prematurity, necrotising enterocolitis)</p>|
|Non-respiratory functions|<p>- Innate immunity e.g. Mucocilicary escalator present in neonate and adult</p><p>- Adaptive immunity: Passive (from breast milk) vs endogenous. No endogenous IgG or IgA in neonatal alveolar lining fluid</p>|


--- 

 