# 2017B Question 14 

Describe the pharmacodynamic properties of propofol excluding its effects on the central nervous system. Describe how these influence clinical use.


## Examiner Report

60.8% of candidates achieved a pass in this question.


Propofol is a core drug in the practice of anaesthesia. The best answers used a systems based approach and gave appropriate clinical examples e.g. a 20% reduction in SVR may cause hypotension and require the use of vasopressor socaution is required especially in the elderly. Many candidates answered the question sufficiently with regard to the cardiovascular and respiratory system, but provided minimal detail and clinical information about other systems.


Despite the question specifically requesting only information related to the pharmacodynamics, and how these influence clinical use, many candidates wasted time on descriptions of the general pharmacology, including its indications, dosage, mechanism of action and chemical structure.

## Model Answer

Structure:
- CVS
- Resp
- Other

### Cardiovascular


|Factor|Details|
| -- | -- |
|Mechanisms|<p>- ↓ L-Ca^2+^ activity in vascular smooth muscle</p><p>- ↑ NO release from endothelium</p><p>- ↑ GABA/glycine → ↓ SNS output from medulla</p>|
|Haemodynamics|<p>- ↓ Venous tone, ↓ MSFP, ↓ preload</p><p>- ↓ Heart rate, ↓ contractility</p><p>- ↓ Baroreceptor reflex (cf. volatiles</p><p>- ↓ SVR (most important cause of ↓ MAP)</p><p>- ↓ Cardiac output</p><p>- ↓ MAP</p>|
|Regional flow|<p>- ↓ Coronary blood flow → Risk ischaemia</p><p>- ↓ Cerebral blood flow (due to preserved metabolic autoregulation)</p><p>- ↓ Hepatic blood flow → Risk ischaemia</p><p>- ↓ Renal blood flow → Oliguria</p><p>- ↓ Uterine blood flow (cf. volatiles)</p>|
|Implications|<p>- Vasopressor, inotrope, chronotrope often needed</p><p>&emsp;- Especially at induction</p><p>&emsp;- Especially for high risk groups (unwell, shocked, elderly, LV failure)</p><p>- Rapid effective treatment of intra-op hypertension</p><p>- ↓ Risk PPH if Caesarean section under GA</p>|

### Respiratory


|Factor|Details|
| -- | -- |
|Mechanisms|<p>- ↑ GABA/glycine → Depression of respiratory centre, chemoreceptors</p><p>- ↓ Spinal cord a-motor neuron activity</p><p>- ↓ Presynaptic L-Ca^2+^ activity</p><p>- ↓ Post-synaptic nnAChR activity</p>|
|Clinical effects|<p>- ↓ RR, ↓ TV</p><p>- ↓ Response to ↑ PaCO~2~ and ↓ PaO~2~</p><p>- ↓ Pharyngeal dilator tone</p><p>- ↓ Airway reflexes</p><p>- Bronchodilation</p><p>- Relative preservation of HPV (cf. volatiles)</p>|
|Implications|<p>- Apnoea common after induction; risk hypoxia if not ventilated</p><p>- Airway obstruction common if no airway device, especially if OSA</p><p>- Allows airway instrumentation without paralysis</p><p>- Risk of aspiration</p><p>- Improved oxygenation during one lung ventilation</p>|

### Other


|Change|Cause|Implication|
| -- | -- | -- |
|Anti-emetic|<p>- 5-HT3 antagonist in CTZ</p>|<p>- Propofol TIVA preferred if PHx PONV++</p>|
|Pain on injection|<p>- ?Activation of endothelial TRPA1 receptors ?Other</p>|<p>- Mix with small dose lignocaine</p><p>- Use fast, free flowing IV</p>|
|Lipotoxicity|<p>- Lipid load: 20mg/mL soybean oil</p>|<p>- Avoid prolonged high dose infusion</p>|
|Propofol infusion syndrome|<p>- ?Lipid load</p>|<p>- Avoid prolonged use in unwell children</p>|


--- 

