# 2017B Question 10 

Describe the physiological processes that influence the rate of gastric emptying.


## Examiner Report

29.2% of candidates achieved a pass in this question
The main points expected are best organised into local, neural and humoral control of gastric emptying of chyme into the duodenum.Candidates with a clear understanding of the reason for the coordinated emptying scored better in this question, which had asked for a description of physiological processes. However, a number of candidates were also awarded marks for pathophysiological and pharmacological factors; if there was prior demonstration of knowledge of normal physiology. Only a few candidates correctly pointed out that pregnancy does not delay gastric emptying; but the stress of labour does.


Common mistakes were
* Answering in tabular format, which listed factors that increase or decrease gastric emptying without further discussion.
* Answering in a clinical approach (patient, surgical and anaesthetic factors), which led to omission of essential physiological facts.
* Confusion about the hormones that are involved and their exact effects on gastric emptying.
* Regurgitation of fasting guidelines for patients without explaining the physiological basis for these guidelines.
* Detailed discussion of gastric acid production or function of the lower oesophageal sphincter, which is not within the scope of this question.

## Model Answer

Structure:
- Introduction
- Physicochemical
- Neural: Extrinsic and intrinsic
- Hormonal factors

### Introduction


|Factor|Details|
| -- | -- |
|Significance|<p>- Gastric emptying rate (GER) varies to ensure chyme adequately digested</p><p>- Full stomach → ↑↑ Risk of aspiration under GA</p><p>- GER highly variable → Important to assess for pain, opioid use, sepsis</p>|
|Normal physiology|<p>- Antral waves, 3 per minute</p><p>- GER ∝ antral contraction freq and strength (AC) / pyloric resistance (PR)</p>|

### Physicochemical


|Factor|Details|
| -- | -- |
|Substrate|<p>- Starch meal: ~2-3 hours</p><p>- Proteinaceous meal: ~3-4 hours</p><p>- Fatty meal: 6 hours</p>|
|Form|<p>- Liquid faster than solid</p>|
|Concentration|<p>- ↑ Osmolality → ↓ GER</p>|

### Neural Factors


|Intrinsic Factor|Stimulus|Effect|
| -- | -- | -- |
|<p>Meissner’s plexus</p><p>(Submucosal)</p>|<p>- ?Distension</p><p>- ?CHO, protein, fat</p>|<p>- Controls local absorption, secretion, contraction</p>|
|<p>Auerbach’s plexus</p><p>(Between longitudinal and circular muscle layers)</p>|<p>- ?Distension</p>|<p>- Controls local contraction</p>|
|Myenteric reflex|<p>- Distension</p>|<p>- Peristalsis (↑ AC)</p>|
|Enterogastric reflex|<p>- Duodenal distension, irritation, acid, fat, protein, high osmo</p>|<p>- ↓ AC</p>|


|Extrinsic Factor|Stimulus|Effect|
| -- | -- | -- |
|PSNS: CNX via coeliac and superior mesenteric plexuses|<p>- ?Distension</p><p>- ?CHO, protein, fat</p>|<p>- ↑ Local ACh release</p><p>- ↑ AC, ↓ PR</p>|
|SNS: T5-L1 via same plexuses|<p>- Exercise, pain, anxiety/stress,</p><p>- Labour (not pregnancy)</p>|<p>- ↓ Local ACh release</p><p>- ↓ AC, ↑ PR</p>|
|Vago-vagal excitatory reflex: CNX only|<p>- Gastric distension</p>|<p>- Receptive relaxation</p><p>- ↑ AC</p>|

### Hormonal Factors


|Stimulate Antral Contraction|Source|Release stimulus|
| -- | -- | -- |
|Gastrin|<p>- Gastric G cells</p>|<p>- Duodenal protein</p><p>- Gastric distension</p>|
|Motilin|<p>- Duodenal M cells</p>|<p>- Duodenal fat, acid</p>|
|Insulin|<p>- Islet β cells</p>|<p>- Hyperglycaemia</p>|
|Serotonin|<p>- Duodenal wall?</p>||


|Inhibit antral contraction|Source|Release stimulus|
| -- | -- | -- |
|CCK|<p>- Duodenal I cells</p>|<p>- Duodenal fat, protein, acid</p>|
|Secretin (conflict)|<p>- Duodenal S cell</p>|<p>- Duodenal fat, acid</p>|
|GIP|<p>- Duodenal K cells</p>|<p>- Duodenal fat, protein, CHO</p>|


--- 

