# 2017B Question 04 


Describe the generation and features of a normal awake EEG (60%). Briefly discuss the processing performed by quantitative EEG monitors (such as BIS or entropy) to produce a single number from the EEG (40%).


## Examiner Report

23.4% of candidates achieved a pass in this question.


In the first part of the question, candidates’ answers should include that EEG is the summation of excitatory and inhibitory potentials of the cortical pyramidal cells. EEG is typically small with low voltage in the order of 0-200 μV. The EEG is characterized by its frequency and amplitude of the waveform.


A few candidates were able to recall the four main frequency bands (≤4 Hz, δ wave; 4–8 Hz, θ wave; 8–13 Hz, α wave; and >13 Hz, β wave), but many of the figures were often incorrectly cited. It should be noted that normal EEG in an awake individual is asynchronous, of low voltage and high frequency. The majority of candidates misinterpreted the second part of the question, and provided answers to highlight the utility of the processed EEG.


The question clearly asked for the methods that convert complex EEG waveform into a single number. This often includes a multiple techniques such as time-domain analysis (e.g. burst suppression), frequency analysis (e.g. β ratio, spectral edge frequency) and others like bicoherence or entropy (irregularity) analyses of the waveform.


## Model Answer

Structure:
- EEG principles
- EEG waves
- Basis of EEG depth monitoring
- BIS
- Entropy

### EEG Principles


|Factor|Detail|
| -- | -- |
|Definition| Recording of the brain’s electrical activity|
|Aetiology|<p>- From pyramidal cells with dendrites radiating toward cortical surface</p><p>- Summation of excitatory and inhibitory post-synaptic potentials</p>|
|Magnitude|<p>- Usually 0-200 microvolts or amplitude</p><p>- Usually 0-50 Hz frequency</p>|
|Waves|<p>- γ: 30-80Hz</p><p>- β: 12-30Hz</p><p>- α: 8-12Hz</p><p>- Θ: 4-8Hz</p><p>- δ: 0-4Hz</p>|


## Physiological basis


|State|Detail|
| -- | -- |
|Awake|<p>- Complex activity → Chaotic pattern</p><p>- High frequency (predominantly β, γ)</p><p>- Low amplitude (↓ synchrony = ↓ summation)</p>|
|Anaesthetised|<p>- Suppression of cortex and brainstem reticular activating system</p><p>- Disinhibition of thalamic pacemaker nuclei → Synchronised pattern</p><p>- Low frequency (predominantly α, Θ, δ)</p><p>- High amplitude (↑ synchrony = ↑ summation)</p>|

## Monitoring Device


|Factor|Detail|
| -- | -- |
|Components|<p>- Electrodes</p><p>1. Exploratory</p><p>2. Reference</p><p>3. EMG</p><p>4. Virtual ground</p><p>- Cabling</p><p>- Processor</p><p>- Display</p>|
|Function|<p>- Acquisition</p><p>- Amplification</p><p>- Filtration (removal of artifact)</p><p>- Processing</p><p>- Display</p>|

### Monitoring Principles


|Principle|Detail|
| -- | -- |
|Algorithms|<p>- Proprietary</p><p>- Empirical – i.e. observe EEG response to variable drug concentration</p><p>- Derived from statistical analysis, not biological models</p><p>- Designed for GABA-ergic anaesthetics</p>|
|Fourier transformation|<p>- EEG taken in short epochs</p><p>- Separation into component sine waves</p><p>- Represented as a spectral array (frequency, power (=amplitude2), ± time)</p><p>- Precursor to many types of analysis</p>|
|Types of analysis|<p>- Time domain analysis: E.g. Burst suppressions</p><p>- Frequency domain analysis: E.g. Beta ratio, spectral edge frequency 95%</p><p>- Both: Degree of entropy / phase coupling / synchrony / symmetry</p>|


### Bispectral Index (BIS)


|Principle|Detail|
| -- | -- |
|Algorithm|<p>1. Burst-suppression ratio (correlates with BIS 0-30)</p><p>- % per 63 seconds spent in burst-suppression pattern (not isoelectricity)</p><p>- Associated with depletion of intracellular calcium</p><br><p>2. QUAZI suppression index</p><p>- Detect burst suppression if wandering baseline</p><br><p>3. SynchFastSlow index (correlates with BIS 40-60)</p><p>- Index of relative synchrony of fast and slow waves</p><p>- Derived from bispectral analysis</p><p>- Processed to yield bicoherence number (0-1 scale of phase coupling)</p><p>- N.B. PowerFastSlow yields similar results</p><br><p>4. Beta ratio (correlates BIS 60-100)</p><p>- Ratio of higher to lower frequency beta waves</p><p>- Important due to paradoxical increase in SFS/SEF at low drug concentration</p><br><p>5. EMG</p><p>- Frontalis muscle activity</p><p>- High frequency (70-110Hz)</p><p>- ? Indicator of nociception or arousal</p>|
|Readouts|<p>- BIS: 40-60 general anaesthesia, 100 awake</p><p>- Suppression ratio (SR) – ideally zero</p><p>- Spectral edge frequency 95% - not included in published algorithm</p><p>- Electromyography (EMG) – 0-100 but no recommendation</p><p>- Signal quality index (SQI) – 0-100 but no recommendation</p>|

### Entropy


|Principle|Detail|
| -- | -- |
|Definition|<p>- Degree of disorder in a system</p><p>- In EEG: ↓ Chaos = ↑ synchrony = ↓ entropy = ↓ number</p>|
|Readouts|<p>(1) State entropy</p><p>- Scale 0-91</p><p>- Frequency 0.8-32Hz</p><p>- Longer epochs → Transient fluctuations eliminated</p><p>- Index of hypnotic component of anaesthesia</p><p>(2) Response entropy</p><p>- Scale 0-100</p><p>- Frequency 0.8-47Hz</p><p>- Includes EMG data</p><p>- Shorter epochs → Rapid response</p><p>- Sudden increase may indicate nociception or arousal</p>|

## SedLine


|Principle|Detail|
| -- | -- |
|Algorithm|<p>- Four EEG channels</p><p>- Linear and non-linear analysis</p><p>- Temporal and spatial frequency gradients</p><p>- Symmetry and synchronization</p><p>- Arousal observer sub-algorithm</p>|
|Readouts|<p>- Patient status index (0-100, aim 25-50)</p><p>- Four EEG waveforms</p><p>- Bilateral density spectral array</p><p>- Suppression ratio</p><p>- Spectral edge frequency</p><p>- Asymmetry graph</p><p>- Artifact</p><p>- EMG</p>|


--- 

