# 2017B Question 08 

Discuss the factors affecting duration of action of a local anaesthetic block to a major peripheral nerve.


## Examiner Report

42.6% of candidates achieved a pass in this question.


The candidates needed to cover drug and patient factors. Drug factors included: lipid solubility, protein binding, molecular size, dose, intrinsic vasoactive properties, additives, and metabolism. Patient factors included: site of administration, structure (connective tissue), and alternated states of physiology.


Marks were not awarded for discussions of pathology, mechanism of action or describing factors affecting the onset time of these drugs.

## Model Answer

Structure:
- Introduction
- Max concentration
- Rate of removal
- MLAC

### Introduction


|Key Term|Details|
| -- | -- |
|Local anaesthetic|- Antagonist at axonal voltage-gated Na^+^ channel (VDNaC)|
|Drug path|<p>- Axoplasm → Interstitium → Plasma</p><p>- Only unionised drug diffuses readily</p>|
|Determinants of rate of offset|<p>1. Maximum concentration in axoplasm</p><p>2. Rate of removal from axoplasm</p><p>3. Minimum local analgesic concentration (MLAC)</p>|

### Maximum Concentration

Increased with:
- ↑ Concentration of solution
- ↑ Volume injected

### Rate of Removal


|Factor|↓ Removal with:|
| -- | -- |
|Fick’s Law|$Q = (C_1 - C_2) \times {A \over T}  \times {Membrane \ Solubility \over \sqrt{Molecular Weight}}$|
|↓ C1|<p>- ↑ VDNaC affinity → ↓ Dwell time (e.g. Bupiv)</p><p>- ↑ Tissue protein binding (most important factor)</p>|
|↑ C2|<p>Drug:</p><p>- Intrinsic vasoconstriction (e.g. Ropiv constrict cf. lignocaine dilate)</p><p>- Added adrenaline</p><p>- Slow metabolism → Slow removal (e.g. Amidase cf. plasma cholinesterase)</p><br><p>Patient:</p><p>- Low intrinsic blood flow (decreasing order: Tracheal / intercostal / caudal / paracervical / epidural / plexus / peripheral nerve / subcut)</p><p>- Tissue hypoperfusion (↓ if heart failure, shock; ↑ if pregnancy, neonate)</p><p>- Slow metabolism (e.g. Neonate)</p>|
|↓ Area||
|↑ Thickness|<p>- ↑ Size of nerve (e.g. Sciatic cf. median) </p><p>- ↑ Connective tissue (e.g. Sciatic cf. median)</p><p>- ↓ Distance from centre of bundle (i.e. distal cf. proximal target)</p>|
|↓ Diffusion coefficient (minor)|<p>- ↓ Lipid solubility (e.g. Lignocaine 150x cf. bupiv 1000x procaine)</p><p>- ↑ Molecular weight</p><p>- ↓ % Unionised (e.g. Bupiv 15% cf. lignocaine 25%); or ↓ tissue pH</p>|

### Maximum Local Anaesthetic Concentration


|Factor|↓ MLAC/Sensitivity ↑ with:|
| -- | -- |
|Nerve sensitivity|<p>- Myelination (3 consecutive nodes of Ranvier ≈ 1cm)</p><p>- ↑ Frequency of action potential</p><p>- ↓ Nerve diameter → ↓ Ratio surface area : Axon unit volume</p><p>Order of decreasing sensitivity: B > C > Aδ > Aγ > Aβ > Aα (sensory 2x motor)</p>|
|Patient|<p>- ↑ Tissue pH</p><p>- Pregnancy</p>|
|Drug|<p>- ↑ Potency (ropiv 8x ligno 2x)</p><p>&emsp;(Correlates with ↑ lipid solubility)</p>|
|Additives|<p>- Opioid</p><p>- α~2~ agonist</p>|


--- 

