# 2018A Question 14 

Describe the mechanisms by which heat is transferred between the body and its environment (30%). Describe methods by which body heat may be conserved under anaesthesia (70%).


## Examiner Report

42% of candidates achieved a pass in this question.


Part A. Most candidates provided a list of heat transfer mechanisms but simply listing radiation, conduction, convection and evaporation gained few marks. Repeating the mechanism without explanation was common and inadequate eg heat loss due to radiation is due to radiation of heat from the body. Better candidates defined heat then provided precise descriptions of heat loss mechanisms using scientific terms. They also pointed out that the body can gain heat via these mechanisms (except evaporation).


Part B. Normal responses to a fall in body temperature are blunted during anaesthesia therefore external methods of conserving heat are required. Explanation of these methods (reducing loss / increasing gains) was required. Listing methods such as covering the patient with blankets, use of forced air warming, under patient insulation, theatre temperature control, overhead radiant heaters and others was important, but to demonstrate understanding reference to the heat loss/gain mechanisms in Part A was needed. Many candidates claimed that the rapid fall in temperature at the onset of anaesthesia is due to heat loss from the body. Few mentioned that this is actually due to redistribution of heat within the body and therefore is not strictly relevant to this question. Many candidates wrote extensively about the physiology of thermoregulation, the thermoneutral zone, interthreshold range and drew graphs of temperature versus time during anaesthesia - this simply wasted time.

## Model Answer

Structure:
- Definitions
- Radiation
- Convection
- Evaporation
- Respiration
- Conduction
- Heat production

### Definitions


|Factor|Details|
| -- | -- |
|Heat|<p>- Form of energy</p><p>- Transferred from higher temp object to lower temp object</p><p>- Unit Joule = kgm^2^s^-2^</p>|
|Temperature|<p>- Measure of the average kinetic energy of particles per degree of freedom</p><p>- Unit Kelvin</p>|
|Specific heat capacity|<p>- Ratio ↑ Heat:↑ Temp</p><p>- Unit kJ.K^-1^.kg^-1^)</p>|

### Radiation (40%)


|Factor|Details|
| -- | -- |
|Mechanism|<p>- Transfer of heat between bodies by EMR</p><p>- Bidirectional</p><p>- Contact not required</p><p>- $\propto T_1^4 - T_2^4$(T in Kelvin)</p><p>- e.g. Patient ↔ Wall</p>|
|Reduce loss|<p>- Vasoconstriction → ↓ Skin temp (↓ T~1~) (impaired under GA)</p><p>- Insulation e.g. Blanket</p><p>- Pre-warming of operating theatre (↑ T~2~)</p>|
|Increase gain|<p>- Radiator above the neonatal resuscitation trolley → Invert temperature gradient</p>|

### Convection (30%)


|Factor|Details|
| -- | -- |
|Mechanism|<p>- Transfer of heat away from a body by motion of a fluid</p><p>- $\propto T_1 - T_2$</p><p>- e.g. Patient → Surrounding air</p>|
|Reduce loss|<p>- Vasoconstriction → ↓ Skin temp (T~1~) (impaired under GA)</p><p>- Insulation e.g. Blanket traps a layer of air next to patient</p>|
|Increase gain|<p>- Forced air warmer</p>|

### Evaporation (15%)


|Factor|Details|
| -- | -- |
|Mechanism|<p>- Due to latent heat of vaporization, 2.24MJ/kg for water</p><p>- Both sweating and transepidermal diffusion = insensitive loss</p><p>- $\propto {Skin \ Temp \over Ambient \ Relative \ Humidity}$</p><p>- Does not require temperature gradient</p>|
|Reduce loss|<p>- Vasoconstriction → ↓ Skin temp (impaired under GA)</p><p>- ↑ Relative ambient humidity</p>|
|Increase gain|<p>- Cannot!</p>|

### Respiration (10%)


|Factor|Details|
| -- | -- |
|Mechanism|<p>- Cool, dry air inspired, warm moist air expired</p><p>-$\propto Minute \ Ventilation$</p>|
|Reduce loss|<p>- Heat and moisture exchanger (HME)</p><p>&emsp;- Expired air cooled by HME, water vapour condenses</p><p>&emsp;- Inspired air warmed by HME, water evaporates</p><p>&emsp;- Extends gradients for temp and humidity: Lung > HME > circuit</p><p>&emsp;- Hence extends countercurrent heat and moisture exchange</p><p>- CO~2~ absorber:</p><p>&emsp;- CO~2~ + sodalime reactions produce heat and water</p><p>&emsp;- Hence ↓ temperature gradient, ↓ humidity gradient</p><p>&emsp;- Hence ↓ latent heat loss</p>|

### Conduction (5%)


|Factor|Details|
| -- | -- |
|Mechanism|<p>- Transfer of heat between two objects in direct contact</p><p>- $\propto T_1 - T_2 \times Surface \ Area \times Thermal \ Conductivity$</p><p>- e.g. Patient → Cold operating table</p>|
|Reduce loss|<p>- Vasoconstriction → ↓ Skin temp (T~1~) (impaired under GA)</p><p>- Heated OT table → Reverse temp gradient</p><p>- Insulated material on table → ↓ Thermal conductivity</p>|

### Heat Production


|Factor|Details|
| -- | -- |
|Brown fat metabolism|<p>- Uncoupling protein inserted into inner membrane</p><p>- Free passage H+ into matrix without ATP synthesis</p><p>- ↑ BMR 2-3x</p><p>- Only significant in neonates</p>|
|Calorigenic hormones|<p>- Effects of catecholamine etc. on liver, skeletal muscle</p>|
|Shivering|<p>- Oscillating contraction/relaxation</p><p>- Especially truncal muscles</p><p>- ↑ BMR 2-3x</p><p>- Ablated under GA</p><p>- Ablated by neuraxial anaesthesia below block level</p>|


--- 

