# 2018A Question 08 

Outline the pharmacology of intravenous metoprolol.


## Examiner Report

50% of candidates achieved a pass in this question.


This question required an application of physiological and pharmacological knowledge, specific to metoprolol. The pass rate was 50% but there were few high-scoring answers.


Errors were often related to confusion about the effect of specific beta receptors, or incorrect information specific to metoprolol as a beta-blocker. Most candidates had a good system for answering a question on a medication, however many candidates wrote vague information under these headings. Candidates are not expected to know detailed pharmacokinetic values for a medication such as metoprolol, but they are expected to know important pharmacokinetic points.

## Model Answer

Structure:
- PC
- PK
- PD

### Physicochemical


|Factor|Details|
| -- | -- |
|Enantiomers|<p>R-metoprolol</p><p>S-metoprolol</p>|
|Presentation|<p>IV solution</p><p>Tablets as tartrate (quick) or succinate (slow)</p>|

### Pharmacokinetics


|Factor|Details|
| -- | -- |
|Administration|- IV: 1-2mg q2 mins, max 10mg|
|Time course|<p>- Onset 1-2 mins</p><p>- Duration 5-8 hours</p>|
|Absorption|<p>- Oral bioav 50% single dose, 70% if repeated (?)</p>|
|Distribution|<p>- Plasma protein binding 10%</p><p>- Moderate lipid solubility</p><p>- Crosses blood-brain barrier</p>|
|Metabolism|<p>- CYP2D6 O-demethylation > CYP3A4 α-hydroxylation</p><p>- t1/2β 3-7 hours</p>|
|Excretion|<p>- Metabolites → Urine</p>|

### Pharmacodynamics


|Factor|Details|
| -- | -- |
|Generation|<p>- 2nd </p>|
|Receptor activity|<p>- β adrenoceptor antagonist</p><p>- Fairly β~1~ selective</p><p>- No intrinsic sympathomimetic activity (ISA)</p><p>- Weak membrane stabilizing activity (MSA)</p>|
|Receptor activation|<p>- Gs G protein coupled receptor</p><p>- ↓ CAMP → ↓ PKA activation → ↓ Phosphorylation of intracellular targets</p>|
|Cardiac pacemaker cells|<p>- ↓ HCN channel activation → ↓ Slope phase 4 → ↓ HR</p>|
|Ventricular myocyte|<p>- ↓ Phosphorylation of:</p><p>&emsp;- Membrane L-Ca^2+^ and SR Ryanodine-sensitive Ca^2+^ channel (↓ Ca^2+^ influx)</p><p>&emsp;- Myosin (↓ rate at which cross-bridge cycling can occur)</p><p>&emsp;- Troponin I and phospholamban (↓ rate of relaxation)</p>|
|CVS effects|<p>- ↓ HR, ↓ atrial tachyarrhythmias, ↓ AV node conduction</p><p>- ↓ Contractility, ↓ remodelling in LV failure</p><p>- ↓ Cardiac output, ↓ MAP acutely (offset by ↑ SVR)</p><p>- +/- Worsen peripheral vascular disease (more a problem if non-selective)</p><p>- +/- rebound effects if abrupt cessation</p>|
|Resp effects|<p>- Risk bronchospasm (some β~2~ antagonism)</p>|
|CNS effects|<p>- ↓ Tremor, depression, fatigue, insomnia, sexual dysfunction, migraine prophylaxis</p>|
|Metabolic effects|<p>- ↑ Risk diabetes, ↓ autonomic response to ↓ BSL, ↓ symptoms of ↓ BSL (tremor, ↑ HR)</p>|
|Renal effects|<p>- ↓ Renin release → ↓ Na^+^/H~2~O retention → ↓ MAP long term</p>|
|Other|<p>- Hair loss<p>|
|Caution if|<p>- Severe LV failure</p><p>- Atrioventricular conduction delay</p><p>- Asthma, COPD</p><p>- Diabetes</p>|
|MSA toxicity|<p>As for local anaesthetic systemic toxicity:</p><p>- CNS: Excitation (seizures) then depression (coma)</p><p>- CVS: Hypotension, arrhythmia, death</p>|


--- 

