# Anticholinesterases


Anticholinesterases antagonise AChE, decreasing the breakdown of ACh and therefore increasing its availability at the:

* Nicotinic receptor\
Increases muscle strength.
    * Reversal of non-depolarising neuromuscular blockade
* Muscarinic receptor\
Increases parasympathetic tone.

Anticholinesterases can be:

* Reversible
* Form a carbamylated enzyme complex
* Irreversible
  \
|Property|Neostigmine|Organophosphates
|--|--|
|**Class**|Quaternary amine, forms carbamylated enzyme complex|Irreversible anticholinesterase
|**Uses**|Reversal of non-depolarising NMB, myasthenia gravis, analgesia|Insecticides, pesticides, chemical weapons
|**Presentation**|Clear, colourless, light stable solution at 2.5mg.ml^-1^||
|**Route of Administration**|PO, IV, intrathecal|Topical
|**Dosing**|0.05mg.kg^-1^ for reversal, 15-30mg PO for MG||
|**Absorption**|Low PO bioavailability|Rapid topical absorption due to high lipid solubility
|**Distribution**|Does not cross BBB, V~D~ 0.7L.kg^-1^|Crosses BBB
|**Metabolism**|Majority by plasma esterases to quaternary alcohol, with some hepatic metabolism|Not metabolised
|**Elimination**|55% unchanged in urine|t~1/2~α of weeks
|**Duration**|50 minutes|Until new AChE is synthesised
|**Resp**|Bronchospasm, ↑ secretion|Bronchospasm, ↑ secretion
|**CVS**|↓ HR (may be profound), ↓ CO|↓ HR, ↓ CO
|**CNS**| N/V and analgesic when administered intrathecally, cerebral vasoconstriction|Central cholinergic syndrome
|**MSK**| Reversal of NMB, ↑ fasciculations, ↑ sweating, may cause paralysis|Paralysis
|**GIT**|↑ Peristalsis, ↑ LoS tone, N/V|↑ Peristalsis, ↑ LoS tone, N/V
|**Other**|Muscarinic receptors affected at low dose, nicotinic receptors at high dose|May be reversed in initial stages (before organophosphate-AChE complex has 'aged') with pralidoxime

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. ANZCA 2007 Feb/April
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
4. Mahmoud, Ahmed Abdelaal Ahmed, Amr Zaki Mansour, Hany Mahmoud Yassin, Hazem Abdelwahab Hussein, Ahmed Moustafa Kamal, Mohamed Elayashy, Mohamed Farid Elemady, et al. ‘Addition of Neostigmine and Atropine to Conventional Management of Postdural Puncture Headache: A Randomized Controlled Trial’ 127, no. 6 (2018): 6.
