# Anticholinesterases


Anticholinesterases antagonise AChE, decreasing the breakdown of ACh and therefore increasing its availability at the:

* Nicotinic receptor\
Increases muscle strength.
    * Reversal of non-depolarising neuromuscular blockade
* Muscarinic receptor\
Increases parasympathetic tone.

Anticholinesterases can be:

* Reversible
* Form a carbamylated enzyme complex
* Irreversible

```{r}
source("scripts/drugtables.R")

DrugTable("neostigmine", caption = "Neostigmine")
```

: Effects of Organophosphate Anticholinesterases

|Property|Organophosphates|
|--|--|
|**Class**|Irreversible anticholinesterase|
|**Uses**|Insecticides, pesticides, chemical weapons|
|**Presentation**||
|**Route of Administration**|Topical|
|**Dosing**||
|**Absorption**|Rapid topical absorption due to high lipid solubility|
|**Distribution**|Crosses BBB|
|**Metabolism**|Not metabolised|
|**Elimination**|t~1/2~α of weeks|
|**Duration**|Until new AChE is synthesised|
|**Resp**|Bronchospasm, ↑ secretion|
|**CVS**|↓ HR, ↓ CO|
|**CNS**|Central cholinergic syndrome|
|**MSK**|Paralysis|
|**GIT**|↑ Peristalsis, ↑ LoS tone, N/V|
|**Other**|May be reversed in initial stages (before organophosphate-AChE complex has 'aged') with pralidoxime|

***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. ANZCA 2007 Feb/April
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
4. Mahmoud, Ahmed Abdelaal Ahmed, Amr Zaki Mansour, Hany Mahmoud Yassin, Hazem Abdelwahab Hussein, Ahmed Moustafa Kamal, Mohamed Elayashy, Mohamed Farid Elemady, et al. ‘Addition of Neostigmine and Atropine to Conventional Management of Postdural Puncture Headache: A Randomized Controlled Trial’ 127, no. 6 (2018): 6.
