# 2019A Question 13 

Outline the principles of antibiotic prophylaxis for surgical site infections using cefazolin in knee joint replacement surgery as an example.


## Examiner Report

59.7% of candidates achieved a pass in this question.

The appropriate use of antibiotics for surgical prophylaxis is fundamental to the provision of anaesthesia. As such it was expected that candidates would have a good knowledge of the principals around why cefazolin is used, the correct dose, timing and the risks and benefits of use. Knowledge about the use of alternative antibiotics and why / when this might be needed gained credit. The principals of prophylaxis did need to be related to the surgery asked in the question (knee replacement surgery) and it was expected that candidates would use this operation to support the use of cefazolin. It was very difficult to achieve a pass without using knee replacement surgery to support the answer.

Better answers used a structure that allowed the development of the concepts important to antibiotic prophylaxis such as correct timing, dosage and patient related factors (multi drug resistant organism colonisation), and included some pharmaceutical information that make cefazolin an appropriate choice such as a wide therapeutic index and a low prevalence of adverse drug reactions.

Answers that failed often did not give enough detail around the principals of prophylaxis in relation to joint replacement surgery, and the reason that cefazolin is a suitable choice. Also there was often correct but irrelevant detail to the question asked, including a detailed description of different types of surgery.

## Model Answer

Structure:
- Aims x 6
- Practical considerations x 7

### Aims


|Aim|Detail|
|--|--|
|<p>Indicated</p><p>(i.e. Not in all surgery at clean sites)</p>|<p>- Moderate risk</p><p>- Severe morbidity</p><p>- Use of implant</p>|
|Bactericidal preferably|Yes|
|Penetrates the relevant tissues|Good for skin, bone, joint|
|Targets the relevant microbes|<p>- First generation cephalosporins effective against skin commensal gram positive cocci</p><p>- (Note gram negative rods common in hospitalized patients)</p>|
|Low risk of encountering antimicrobial resistance|<p>- Low risk if from community</p><p>- But ineffective against MRSA, use vancomycin instead if in hospital several days</p>|
|Low risk of promoting microbial resistance|<p>- Minimal necessary duration: 24 hours total</p><p>- Minimal necessary spectrum: I.e. not piperacillin/tazobactam</p>|

### Considerations


|Consideration|Detail|
|--|--|
|Dose|25mg.kg^-1^ pre-induction|
|Route|IV ideal|
|Rapid onset|<p>- Ideally 30-60 mins pre-incision, to allow penetration of skin</p><p>- MUST be well before tourniquet if knee replacement</p>|
|Long duration: Ensure cover during long procedure|<p>- Repeat at 4 hours if surgery ongoing</p><p>- Repeat at 8 hours post-op</p>|
|Adjustment in organ dysfunction|Cefazolin is renally cleared. ↓ Frequency if CrCl reduced esp ≤30mL.min^-1^|
|Side effects|<p>- High therapeutic index</p><p>- Risk of anaphylaxis</p>|
|Cost|Cheap|


--- 

