# Depolarising NMBs


Succinylcholine binds to the nicotinic ACh receptor causing depolarisation. It cannot be hydrolysed by acetylcholinesterase in the NMJ, and so remains bound to the receptor. This:

* Produces a sustained depolarisation which keeps voltage-gated sodium channels in their inactive state
* Prevents the post-junctional membrane from responding to further ACh release


```{r}
source("scripts/drugtables.R")

DrugTable("suxamethonium")
```

## Adverse Effects

The adverse effects of suxamethonium can be remembered as **three major, three minor, and three pressures**:

  * **Major**
    * Anaphylaxis
    * Suxamethonium Apnoea
    * Malignant hyperthermia
  * **Minor**
    * Hyperkalaemia
    * Myalgias
    * Bradycardia
  * **Pressure**
    * IOP
    * ICP
    * Intragastric pressure

## Phase I and Phase II Blockade

Initial blockade is termed **Phase I**, which is a partial depolarising block. Sustained use of suxamethonium may causes a Phase II block which:

* Appears similar to a non-depolarising block
* May be due to:
  * Presynaptic inhibition of ACh synthesis and release
  * Desensitisation of the post-junctional receptor

Key differences include:

|Property|Phase I Block|Phase II Block
|--|--|--|
|**Block Amplitude**|Reduced|Reduced|
|**Train-of-four ratio**| >0.7|< 0.7
|**Post-tetanic potentiation**|No|Yes
|**Effect of anticholinesterases**|Block augmented|Block inhibited

## Malignant Hyperthermia

* Rare autosomal dominant genetic condition
* Triggered by suxamethonium and volatile anaesthetic agents
* Mutation of the ryanodine receptor causes excessive amounts of calcium to leave the sarcoplasmic reticulum, causing continual muscle contraction
  * Results in greatly increased carbon dioxide, lactate, and heat production
  * Cell lysis with myoglobulinaemia and hyperkalaemia results

## Suxamethonium Apnoea

* A deficiency of butylcholinesterase causes suxamethonium to not be metabolised
* May be congenital (genetic) or acquired (hepatic failure)
* Can be treated with fresh frozen plasma


***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. [Suxamethonium Chloride Injection BP PRODUCT INFORMATION](https://gp2u.com.au/static/pdf/S/SUXAMETHONIUM_CHLORIDE_INJECTION_BP-PI.pdf)
3. Appiah-Ankam J, Hunter JM. [Pharmacology of neuromuscular blocking drugs](https://academic.oup.com/bjaed/article/4/1/2/356873/Pharmacology-of-neuromuscular-blocking-drugs). Continuing Education in Anaesthesia Critical Care & Pain, Volume 4, Issue 1, 1 February 2004, Pages 2–7.
4. Cook T, Harper N. [Anaesthesia, Surgery, and Life-Threatening Allergic Reactions: Report and findings of the Royal College of Anaesthetists' 6th National Audit Project: Perioperative Anaphylaxis](https://niaa.org.uk/NAP6Report#pt). Royal College of Anaesthetists'. 2018.
