# Non-Depolarising Neuromuscular Blockers


Non-depolarising NMBs are muscle relaxants used to:

*  Facilitate laryngoscopy and tracheal intubation
*  Control ICP
*  Improve respiratory system compliance
*  Improve patient safety on transportation

Mechanism of action is by competitive antagonism of ACh at the NMJ, preventing generation of end-plate potentials. Effective pharmacodynamic response requires >70% receptor occupation.

: Common Features of Non-Depolarising Neuromuscular Blockers

|Property|Action|
|--|--|
|**Route of Administration**| IV/IM|
|**Distribution**|Small V~D~ as they are polar and unable to cross lipid membranes|
|**Elimination**|Reduced urinary clearance which prolongs the mechanism of action of aminosteroids in renal failure
|**Resp**|Apnoea|
|**MSK**|↑ Duration in hypothermia|
|**Renal**|↑ Duration in acidosis, ↑ duration in hypokalaemia, ↓ duration in hyperkalaemia, ↑ duration in hypermagnesaemia|
|**Metabolic**|Critical Illness Myopathy in patients with long-term relaxant use|

The ED~95~ is:

* The dose of a neuromuscular blocking drug required to produce a 95% reduction in twitch height in 50% of the population
* A commonly-used therapeutic end-point for neuromuscular blocking drugs\
Typically, induction doses used are 2-5x the ED~95~.

```{r}
source("scripts/drugtables.R")

DrugTable("rocuronium", "vecuronium", "pancuronium", "atracurium", "cisatracurium", caption = "Comparison of Non-Depolarising Neuromuscular Blockers")
```

***

## References


1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
3. Crilly H, Rose M. [Anaphylaxis and anaesthesia – can treating a cough kill?](https://www.nps.org.au/australian-prescriber/articles/anaphylaxis-and-anaesthesia-can-treating-a-cough-kill). Aust Prescr. 2014;37:74-6.
4. Lexicomp. Rocuronium: Drug information. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
5. Lexicomp. Vecuronium: Drug information. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
6. Lexicomp. Pancuronium: Drug information. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
7. Lexicomp. Atracurium: Drug information. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
8. Lexicomp. Cisatracurium: Drug information. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
9. Cook T, Harper N. [Anaesthesia, Surgery, and Life-Threatening Allergic Reactions: Report and findings of the Royal College of Anaesthetists' 6th National Audit Project: Perioperative Anaphylaxis](https://niaa.org.uk/NAP6Report#pt). Royal College of Anaesthetists'. 2018.
