# Sugammadex


|Property|Sugammadex
|--|--|
|**Class**|Gamma cyclodextrin.
|**Uses**| Reversal of neuromuscular block induced by rocuronium and vecuronium.
|**Presentation**|Clear colourless solution at 100mg.ml^-1^.
|**Pharmaceutics**|Store below 30°C.
|**Route of Administration**|IV only.
|**Dosing**| 2mg.kg^-1^ if ToF > 2. <br> 4mg.kg^-1^ if PTC > 2. <br> 16mg.kg^-1^ for reversal following RSI dose.
|**Distribution**|V~D~ of 11-14L.kg^-1^.
|**Metabolism**|Not metabolised.
|**Elimination**|Renal elimination of active drug and complex.
|**Mechanism of Action**|Forms a complex with rocuronium and vecuronium, causing reversal of neuromuscular blockade.
|**CVS**|Rarely may precipitate bradycardia - can result in cardiac arrest.
|**Immune**|Anaphylaxis.
|**Other**|Interacts with OCP - treat as missed pill <br> Shortened duration of rocuronium and vecuronium when used within 24 hours of sugammadex administration. Onset is delayed up to 5 minutes, and duration shortened by 10-15 minutes. This period may be extended in renal failure.


---

## References

1. [Sugammadex Full Prescribing Information](https://www.accessdata.fda.gov/drugsatfda_docs/label/2015/022225lbl.pdf). FDA.