---
level: 2
---

# (EMPTY) Cellular Physiology

# The Cell Membrane

:::CICM
Describe the cell membrane ~~and cellular organelles and their properties~~.
:::

:::ANZCA
Outline basic cellular physiology in particular: The structure of the cell membrane ~~and trans-membrane transport mechanisms, The composition and regulation of intracellular fluid,~~ The generation of the trans-membrane potential~~, Energy production by metabolic processes in cells~~
:::

Cell membranes are the layer that separates the interior of a cell from the outside environment (extracellular space). They are:

* Formed by a **phospholipid bilayer**
* **Semi-permeable**\
Leads to different ionic concentrations (and therefore electrical charge) on either side of the membrane.
    * Alteration in charge means the membrane acts as a **capacitor**, with most cells having a **resting potential 70-80mV lower** than extracellular fluid

## Ion Permeability

At rest, the cell is:

* Permeable to **potassium**\
Potassium flows out down its concentration gradient, which makes the resting potential becomes more negative.
    * This negative charge opposes the further movement of potassium and so an equilibrium is established between opposing electrical and chemical gradients
* Relatively **impermeable** to **other cations**\
The membrane is not perfectly impermeable to sodium, and Na^+^ will leak in down its concentration gradient.
    * The 3Na^+^-2K^+^ ATPase pumps **three sodium ions** outside in exchange for **two potassium ions** in order to maintain these gradients\
    As there is an unequal exchange of charge, this pump is **electrogenic**.

|  Ion  | [Intracellular] | [Extracellular] |
|-------+-----------------+-----------------|
| Na^+^ |              15 |             140 |
| K^+^  |             150 |             4.5 |
| Cl^-^ |              10 |             100 |

---

## References

1. Barrett KE, Barman SM, Boitano S, Brooks HL. Ganong's Review of Medical Physiology. 24th Ed. McGraw Hill. 2012.
2. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.