# Membrane Transport

:::CICM
Explain mechanisms of transport of substances across cell membranes, including an understanding of the Gibbs-Donnan effect.
:::

:::ANZCA
Outline basic cellular physiology in particular: The structure of the cell membrane and trans-membrane transport mechanisms~~, The composition and regulation of intracellular fluid, The generation of the trans-membrane potential, Energy production by metabolic processes in cells~~
:::

Substances can cross cell membranes by **three** mechanisms:

* **Diffusion**
* **Active transport**
* **Exo-** or **endocytosis**

## Diffusion

There are several types of diffusion:

* **Simple diffusion**\
Molecules pass through the cell membrane or via a channel. This process is **passive**, and occurs down a concentration gradient.
    * Only lipid soluble molecules (gases, steroids) can pass directly through the lipid bilayer without a specialised channel
    * Voltage-gated and ligand-gated channels facilitate simple diffusion


* **Facilitated diffusion** (uniporters)\
Molecules bind to a carrier protein, and move together through the lipid bilayer, before separating on the other side. Facilitated diffusion is **concentration gradient-dependent**, and **limited by** the amount of **carrier protein** available..


The rate and extent of diffusion is affected by:

* Hydrostatic pressure gradients
* Concentration gradients
* Electrical gradients

## Active Transport

Substances that are moved against a concentration gradient require active transport, and requires energy in the form of ATP. Active transport mechanisms may be:

* **Primary** active transport\
The substance itself is moved.
* **Secondary** active transport\
The substance moves against a concentration gradient with another molecule that had a gradient established by active transport.
    * The "other molecule" is typically sodium
* **Co-transporters** (symporters)\
Uses carrier proteins and moves two substances (e.g. sodium and an amino acid) across a membrane.
    * This process will be passive if the energy gained moving one substance down its concentration gradient is greater than the energy required to move the other substance up its concentration gradient
* **Counter-transporters** (antiporters)\
Use carrier proteins and moves two substances in opposite directions across the membrane.
    * May be active or passive

Key transporters include:

* The **Na^+^-K^+^ ATP-ase** pump\
This moves three sodium ions out of a cell and two potassium ions in, cleaving one ATP in the process. This pump has many functions:
    * Maintenance of cellular volume (which would otherwise burst from the influx of water with changing ECF tonicities) by net loss of osmoles
    * Maintenance of the potential difference across the membrane
    * Establishment of chemical gradients to be used in secondary active transport mechanism
        * e.g. Reabsorption of glucose in the kidney via the S-GLUT transporter

## Exo- and Endocytosis

These processes describe the formation of a vesicle (typically from membrane phospholipid) to transport substances:

* **Exocytosis**\
Vesicle containing a substance to be secreted fuses with the cell membrane when activated by calcium, depositing the substance outside the cell.
* **Endocytosis**\
The cell membrane invaginates around the substance, absorbing the substance into the cell. A vesicle (or vacuole) may or may not be created. Endocytosis may be subdivided into:
  * Phagocytosis, where leukocytes engulf bacteria into a vacuole
  * Pinocytosis, where substances are endocytosed but not into a vacuole


## Gibbs-Donnan Effect

::: column-margin
Remember: all ions are charged.
:::

The Gibbs-Donnan Effect describes the **tendency of permeable ions** to **distribute** themselves **such that the *ratios* of** the **concentrations are equal** when they are **in** the **presence of non-diffusable ions**.

The **consequence** is an uneven distribution of ions on either side of a semi-permeable membrane, and is important for:

* Maintenance of cell volume\
Na^+^ acts as an effective osmole, reducing cellular swelling.
* Plasma oncotic pressure\
Increased plasma ion concentration increases oncotic pressure.
* Resting Membrane Potential\


It occurs when:

* A semi-permeable membrane (e.g. a cell membrane) separates two solutions
* At least one of those solutions contains a non-diffusable ion\
The two main contributors to the Gibbs-Donnan effect in the body are sodium and protein, as the cell membrane is:
    * Impermeable to protein\
    Intracellular protein concentration is high.
    * Effectively impermeable to sodium\
    Due to the Na^+^-K^+^ ATP-ase pump.

The **distribution** of permeable ions will be **influenced by both**:

* **Valence**
* **Distribution of non-diffusable ions**  
Such that at equilibrium **the products of the concentrations of paired ions on each side of the membrane will be equal**:

$$[Na^+]_A \times [Cl^-]_A = [Na^+]_B \times [Cl^-]_B$$


### Gibbs-Donnan Equilibrium

Distribution of particles on either side of a membrane is a function of:

* Concentration gradients
* Electrostatic gradients
* Osmotic gradients


These gradients are dynamic and interdependent, and result in **no stable steady state**:

* As the distribution of charged ions changes, *tonicity* on either side of the cell membrane is altered
* This causes movement of water down the new osmotic gradient, which then alters *concentration* of substances on either side of the membrane
* Particles then move down their **concentration** gradient, and tonicity is altered
* etc


---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
2. Eaton DC, Pooler JP. Vander's Renal Physiology. 6th Ed (Revised). McGraw-Hill Education - Europe. 2004.