---
level: 2
---


# Cell Homeostasis

:::CICM
To describe the ~~composition and control of intracellular fluid and the~~ mechanisms by which cells maintain their homeostasis and integrity
:::


**Cellular respiration** describes the production of ATP through a series of redox reactions. Oxygen is used as the oxidising agent, whilst the catabolic fuel may be glucose, fat, or protein.

Cellular respiration can be broken down into:

* Glycolysis/Lipolysis/Proteolysis
* Citric Acid Cycle
* Electron Transport Chain

## Glycolysis

**Glycolysis**, or the **Embden-Meyerhof pathway**, describes the production of pyruvate from glucose. Glycolysis:

* Occurs in the cytoplasm
* Begins with the **phosphorylation of glucose** to glucose-6-phosphate
* Produces:
  * 2 ATP
  * 2 Pyruvate
  * 2 NADH


* Note that **oxygen is not consumed and carbon dioxide is not produced**
* In aerobic conditions:\
NADH exchanges electrons across the mitochondrial wall, regenerating NAD^+^ and allowing glycolysis to continue
* In anaerobic conditions:\
  NAD^+^ is regenerated through the production of lactate
    * When aerobic conditions are restored, lactate can be oxidised back to pyruvate and enter the CAC
    * Transported to the liver and converted back to pyruvate (and enter the CAC), or produce glucose (**Cori cycle**)

## Citric Acid Cycle/Kreb's Cycle

* Takes place in the mitochondria
* Complicated 
* Can take many various substrates:
  * Acetyl CoA\
  Produced by β-oxidation of fatty acids and pyruvate.
  * Pyruvate
  * Ketoacids
* Does **not consume oxygen** but also **doesn't function under anaerobic conditions**, due to its requirement on fresh NAD^+^ from the ETC
* Produces:
  * NADH
  * FADH~2~
  * CO~2~

## Electron Transport Chain

* Final stage of carbohydrate, fat, and protein catabolism
* ETC consists of five protein complexes
* Electrons are passed along the chain and combine with oxygen, releasing energy which stimulates the movement of hydrogen ions
* Each time a hydrogen ion crosses the mitochondrial matrix, an ATP is produced
  * This is called **coupled phosphorylation**
  * Uncoupled phosphorylation allows hydrogen ions to travel down their gradient without generating ATP, which produces excess heat instead
* 36-38 ATP are produced by aerobic glycolysis\
Sources disagree on exactly how much ATP is produced.
  * 2 from the Embden-Meyerhof pathway
  * 34-36 from the CAC and ETC


---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.