---
level: 2
---

# Fluid Compartments

:::CICM
To describe the composition and control of intracellular fluid ~and the mechanisms by which cells maintain their homeostasis and integrity~
:::

:::ANZCA
Outline basic cellular physiology in particular: ~~The structure of the cell membrane and trans-membrane transport mechanisms,~~ The composition and regulation of intracellular fluid~~, The generation of the trans-membrane potential, Energy production by metabolic processes in cells~~
:::

On average, the human body is **~60% water**. Distribution of water content can be divided conceptually into:

* Intracellular fluid
* Extracellular fluid

### Intracellular Fluid

Intracellular fluid:

* Composes 2/3^rds^ of total body water.
* Not a contiguous fluid space
* Useful conceptually as the composition of cellular contents is relatively uniform:
	* Potassium is the dominant intracellular cation\
	Sodium concentrations are low.
	* The dominant anion is protein\
	Chloride concentration is relatively low.
	* Low in magnesium

### Extracellular Fluid

Extracellular fluid:

* Composes the remaining 1/3^rd^ of total body water
* Is subdivided into:
	* Intravascular fluid
		* Composes ~20% of ECF
		* Refers solely to plasma volume (as the volume of blood from cellular components is ICF)
		* Is vital for transporting nutrients, waste, and chemical messengers between the plasma and cells
	* Transcellular fluid
		* Composes ~7% of ECF
		* Includes the volume of CSF, urine, synovial fluid, gastric secretions, and aqueous humor
	* Interstitial fluid
		* Composes the bulk of ECF volume
		* Refers to the fluid that occupies the volume between cells


## Variations

Actual total body water content varies predominantly with **fat content**. This leads to differences in TBW concentrations between:

* Neonates\
~75-80%.
* Elderly\
~50% by the age of 60, due to increased adiposity.
* Women\
Typically ~55%.


## Measuring Volumes of Fluid Compartments

All methods rely on the indicator-dilution method:

* A known amount (i.e. known volume of a known concentration) of indicator with affinity to a particular compartment is given and allowed to equilibrate
* The concentration of the indicator is then measured
* The difference between the measured concentration and the initial concentration is proportional to the volume of the compartment


Indicators used for calculation of:

* Plasma volume\
A colloid that will be retained in the vascular compartment; e.g. radio-labeled albumin.
* ECF volume\
A substance which can enter the interstitium but not cells; e.g. thiosulfate.
* Total body water\
A substance which can enter all compartments freely; e.g. heavy water ($^2H_2O$).
* ICF volume\
Can be measured by the difference between calculated ECF volume and TBW.


---

## References

1. Brandis, K. [Fluid Compartments](https://www.anaesthesiamcq.com/FluidBook/fl2_1.php). Anaesthesia MCQ.
2. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.