# Antimuscarinics (Respiratory)


*Antimuscarinics with predominantly cardiac effects are covered at [Antimuscarinics (Cardiac)](antimuscarinicsansmd.md), whilst [atropine](atropine.md) is covered separately.*

These agents competitively antagonise ACh at M~3~ receptors in bronchial smooth muscle, preventing parasympathetic mediated bronchoconstriction.


|Property|Ipratropium|Tiotropium|
|--|--|
|**Class**|Muscarinic antagonist|Muscarinic antagonist|
|**Uses**|Bronchodilatation|Bronchodilatation|
|**Presentation**|MDI or solution for nebulisation|MDI|
|**Route of Administration**|Inhaled|Inhaled|
|**Dosing**|18mcg MDI, 500µg nebuliser||
|**Absorption**|5% bioavailability via inhaled route||
|**Metabolism**|Hepatic to inactive metabolites||
|**Elimination**|Equal renal and faecal elimination|||
|**Resp**|Bronchodilation|Bronchodilation
|**GIT**|Decreased GI secretions in large doses|Decreased GI secretions in large doses
|**CNS**|Mydriasis if deposited in eye|Mydriasis if deposited in eye

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
