# Anti-Asthma Drugs

> Describe the pharmacology of anti-asthma drugs.

* **Oxygen**\
Increases FiO~2~ and improves saturation.
* **Heliox**\
Reduces specific gravity of inhaled gas mixtures, improving laminar flow.
* **β~2~-agonists**\
Acts on a G-protein coupled receptor to ↑ cellular levels of adenylyl cyclase, ↑ cAMP, which results in smooth muscle relaxation and bronchodilatation.
* **Corticosteroids**\
Glucocorticoids are steroid hormones that bind to specific intracellular receptors and translocate into the nucleus, where they regulate gene expression in a tissue-specific manner. They are used in asthma as they cause:
 * Bronchodilatation by increasing bronchial smooth muscle response to circulating catecholamines
 * Decreased airway oedema by decreasing inflammatory responses and transudate production
* **Muscarinic antagonists**\
Anti-muscarinics are synthetic quaternary ammonium compounds which competitively inhibit M3 muscarinic receptors on bronchial smooth muscle, antagonising the bronchoconstrictor action of vagal impulses.
* **Methylxanthines**\
Methylxanthines are phosphodiesterase inhibitors, reducing levels of cAMP hydrolysis and increased intracellular levels of cAMP (via a different mechanism, so they are synergistic with β~2~ agonists) and causing smooth muscle relaxation.
* **Ketamine**\
Increases sympathetic outflow and relaxes bronchial smooth muscle. 
* **Volatile Anaesthetic Agents**\
Volatile anaesthetic agents reduces bronchial smooth muscle constriction where this is preexisting (such as asthma).
* **Leukotriene Antagonists**\
Selectively inhibits the cysteinyl leukotriene receptor, increased activity of which is involved in airway oedema and bronchial smooth muscle constriction.

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
