# Beta Agonists


*This covers the inhaled β-agonists used for bronchodilation. Information on catecholamines and sympathomimetics with activity on β-receptors is covered under [adrenergic vasoactives](adrenergic_drugs.md).*

## Common Features

|Pharmacodynamic Effects|β-agonists|
|--|
|**Resp**|Bronchodilatation, ↓ HPV causing ↑ shunt and potential ↓ PaO~2~ if O~2~ is not co-administered.|
|**CVS**|↑ HR (β~1~ with higher doses), ↓ BP (β~2~ with lower doses) |
|**GU**|Tocolytic.|
|**Metabolic**|Hypokalaemia from β~2~ stimulation of Na^+^/K^+^ ATPase, hyperglycaemia.|
|**Other**|Potentiates non-depolarising muscle relaxants|

## Differences

|Property|Salbutamol|Salmeterol|
|--|--|--|
|**Class**|Synthetic sympathomimetic amine|Synthetic sympathomimetic amine|
|**Uses**|Acute asthma/bronchospasm, hyperkalaemia|Nocturnal and exercise-induced asthma|
|**Presentation**|MDI (100µg), solution at 2.5-5mg.ml^-1^ for nebulisation|MDI|
|**Route of Administration**|Inhaled, IV|Inhaled|
|**Dosing**|1-2 puffs via MDI, 5mg nebulised. 0.5mcg.kg^-1^.min^-1^ as IV infusion.||
|**Onset**|Rapid|Slow|
|**Distribution**|Low protein binding|
|**Metabolism**|High first pass hepatic to inactive metabolites, t~1/2~β 6 hours.|Extensive hepatic via CYP3A4|
|**Elimination**|Urinary elimination of active (30%) drug and inactive metabolites|Renal of metabolites|


---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.