# Corticosteroids


Glucocorticoids are endogenous (hydrocortisone) and synthetic (prednisolone, methylprednisolone, dexamethasone) steroid hormones with **metabolic**, **anti-inflammatory**, and **immunosuppressive** effects. They bind to specific intracellular receptors and translocate into the nucleus, where they regulate gene expression in a tissue-specific manner.

Corticosteroids have multiple indications including:

* Replacement in adrenal suppression or other cortisol-deficient states
* Autoimmune disorders
* Anaphylaxis and atopic disorders, including asthma
* Hypercalcaemia
* Chemotherapy
* Immunosuppression following transplantation

## Common Features

|System|Effect|
|--|--|
|**Resp**|↑ Bronchial smooth muscle response to circulating catecholamines, ↓ airway oedema|
|**CVS**|↑ Inotropy, ↑ vascular smooth muscle response to circulating catecholamines (↑ receptor expression), ↑ BP secondary to mineralocorticoid effects|
|**CNS**|Mood changes, sleep disturbance, psychosis|
|**MSK**|Atrophy, thinning of skin|
|**Renal**|Glycosuria, Na^+^ and fluid retention (mineralocorticoid effect), hypokalaemia|
|**GIT**|Gastric ulceration|
|**Metabolic**|↑ Gluconeogenesis, diabetes, ↑ protein catabolism, fat redistribution, adrenal suppression (negative feedback on ACTH), ↑ lipolytic response to circulating catecholamines|
|**Immune**|↓ Transudate production, ↓ production of inflammatory mediators, ↓ macrophage function, ↓ transport of lymphocytes, ↓ T-cell function, ↓ antibody production, ↑ susceptibility to infection, 
|**Toxic Effects**|Relative steroid deficiency in adrenal suppressed individuals with infection or surgery|

## Comparison of Corticosteroids

|Property|Hydrocortisone|Prednisolone|Methylprednisolone|Dexamethasone|
|--|--|
|**Route of Administration**|IV/PO|PO|PO/IV/IM|IV|
|**Relative Dose Equivalents**|100mg|25mg|20mg|4mg|
|**Absorption**|50% PO bioavailability|100% PO bioavailability||60% PO bioavailability|
|**Distribution**|Variable protein binding depending on concentration, V~D~ 0.5 L.kg^-1^|Variable protein binding depending on concentration, V~D~ 0.5 L.kg^-1^|V~D~ 1 L.kg^-1^||
|**Metabolism**|Hepatic|Hepatic|Hepatic|Hepatic|
|**Elimination**|Elimination t~0.5~ is 2 hours|Elimination t~0.5~ is 3 hours|Elimination t~0.5~ is 3 hours|Elimination t~0.5~ is 4 hours|
|**Relative mineralocorticoid effect**|+++|++|+|+

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
3. Nieman LK, Lacroix A, Martin KA. Pharmacologic use of glucocorticoids. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
4. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.