# Non-Adrenergic Vasoactives


Key non-adrenergic cardiovascular drugs include **vasopressin** (and its analogues, **terlipressin** and **ornipressin**), **phosphodiesterase III inhibitors** such as milrinone, and **calcium sensitisers** such as levosimendan.

|Property|Vasopressin (ADH)|Milrinone|Levosimendan|
|---|---|
|**Class**|Natural nonapeptide|Phosphodiesterase III inhibitor|Calcium sensitiser and phosphodiesterase inhibitor|
|**Uses**|Haemorrhage, DI, catecholamine-sparing vasopressor|Refractory CCF and low CO states|Severe acute heart failure|
|**Dosing**|5-10 units IV bolus, up to 4U/hr infusion|50μg/kg loading dose over 10 minutes (often omitted), followed by infusion titrated to haemodynamic effects, up to 75μg/kg/min|Load 12-24mcg/kg over 10min, then infusion at 0.05-2mcg/kg/min|
|**Route|**IV/SC/IM|IV|IV|
|**Presentation**|Clear solution|Yellow solution at 1mg/ml|2.5mg/mL in 5ml & 10ml vials|
|**Distribution**||70% protein bound|Very high protein binding >90%|
|**Metabolism**|t1/2 10 minutes. Metabolised by tissue peptidases and renal elimination.|t1/2 1-2.5 hours, prolonged in patients with cardiac or renal disease|t1/2 1 hour. Hepatic to active metabolite with a t1/2 ~70 hours|
|**Elimination**||80% of drug is excreted unchanged, making it highly dependent on renal blood flow||
|**Mechanism of action**|V2 receptors (kidney, platelets) are adenylate cyclase mediated. V1 (vascular smooth muscle) and V3 receptors (pituitary) are phospholipase C/inositol triphosphate mediated|Inhibits phosphodiesterase breakdown of cAMP, increasing intracellular Ca2+ levels. ↑ Speed of Ca2+ uptake into cardiac muscle, ↑ lusitropy.|Binds to troponin C increasing myofilament Ca2+ sensitivity. Also opens K+ channels causing vasodilation. It may also have some PD III inhibition effect.|
|**CVS**|↑ SVR through vasoconstriction|↑ Inotropy, ↑ lusitropy, ↓ SVR and PVR (PVR ↓ more than SVR). ↑ Dysrhythmias.|↑ CO without ↑ O2 demand, vasodilation, prolonged QTc with risk of arrhythmia|
|**GIT**|GIT smooth muscle contraction|||
|**Renal**|↑ Aquaporin insertion into the apical membrane of collecting ducts which ↑ water reabsorption|||
|**Haematological**|↑ Coagulation factor mobilisation and ↑ platelet aggregation|||
|**Metabolic**|Hyponatraemia|||


---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Smith S, Scarth E, Sasada M. Drugs in Anaesthesia and Intensive Care. 4th Ed. Oxford University Press. 2011.
3. Brunton L, Chabner BA, Knollman B. Goodman and Gilman's The Pharmacological Basis of Therapeutics. 12th Ed. McGraw-Hill Education - Europe. 2011.
