# Oxygen


|Property|Action|
|--|--|
|**Class**|Naturally occurring gas|
|**Uses**|Improve FiO~2~, CO poisoning, hyperbaric O~2~ therapy|
|**Pharmaceutics**|Clear, colourless, odourless gas at STP. Critical temperature **-119°C**, manufactured by fractional distillation. Highly flammable.|
|**Route of Administration**|Inhaled|
|**Dosing**|0.21-1.0 FiO~2~|
|**Absorption**|Diffusion across the alveolar capillary membrane in proportion to membrane area and partial pressure gradient, and inversely proportional to membrane thickness (Fick's Law)|
|**Distribution**|Bound to plasma Hb, and dissolved in plasma|
|**Metabolism**|Metabolised in mitochondria of cells during the citric acid cycle to produce ATP, creating CO~2~|
|**Elimination**|Exhalation as CO~2~, or combined with H~2~O to produce HCO~3~^-^ and eliminated in urine|
|**Resp**|↓ Respiratory drive in all individuals. May result in a fatal ↓ in those dependent on hypoxic drive. **Pulmonary toxicity** due to free radial formation when PiO~2~>0.6bar - pneumonitis/ARDS due to lipid peroxidation of the alveolar-capillary membrane. Absorption atelectasis.|
|**CVS**|Improvement in all CVS parameters in the setting of hypoxia. However, hyperoxia ↓ CO, ↓PVR, ↓PAP, and causes coronary vasoconstriction with prolonged administration|
|**CNS**|CNS O~2~ toxicity, typically at pressures >1.6 bar though this is variable. Presents with a variety of neurological symptoms, progressing to disorientation and seizure. Retrolental fibroplasia in neonates exposed to high FiO~2~.|
|**Other**|Fire risk|

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. RAH Advanced Diving Medicine Course Notes: Chapter 6 Oxygen and Carbon Dioxide Toxicity