# Phosphodiesterase Inhibitors / Methylxanthines


Methylxanthines non-selectively inhibit phosphodiesterase, which results in reduced levels of cAMP hydrolysis and therefore increased intracellular cAMP, and subsequent smooth muscle relaxation. This effect is synergistic with β~2~ agonists, which also increase cAMP by increasing production.

|Property|Theophylline|
|--|--|
|**Class**|Methylxanthine/Non-selective phosphodiesterase inhibitor|
|**Uses**|Asthma and COAD|
|**Route of Administration**|IV or PO|
|**Dosing**|4-6mg.kg^-1^ IV load, then at 0.4mg.kg^-1^.hr^-1^ targeting serum concentration of 10mcg.ml^-1^|
|**Absorption**|High oral bioavailability|
|**Distribution**|V~D~ 0.5L.kg^-1^, 40% protein binding.|
|**Metabolism**|Hepatic via CYP450 to active metabolites (caffeine and 3-methylxanthine), low hepatic extraction ratio|
|**Elimination**|Highly variable elimination affected by age, renal disease, hepatic disease|
|**Resp**|Bronchodilation, ↑ Diaphragmatic contractility|
|**CVS**|↑ Inotropy, ↑ chronotropy. Narrow therapeutic range due to arrhythmogenic (VF) properties|
|**CNS**|↓ Seizure threshold|
|**Renal**|Natriuresis and hypokalaemia|
|**Toxic Effects**|Low therapeutic index, with toxicity manifested as tachyarrhythmias including VF, tremor, insomnia and seizures|

---
## References

1. Lexicomp. Theophylline: Drug Information. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2017.
2. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
