# 2018B Question 13 

List the drugs which affect uterine tone and outline the adverse effects of these agents.


## Examiner Report

72% of candidates achieved a pass in this question.


These drugs are used or encountered commonly in obstetric anaesthesia and in obstetric patients. They can have profound effects on maternal and foetal physiology. A good knowledge of these drugs and their side effects is required by anaesthetists as their use is often indicated in, or are the cause of, emergency situations such as postpartum haemorrhage or delivery of a compromised baby.


To pass this question, answers needed to include classification of at least four drugs that increase or decrease uterine tone, along with at least one side effect for each drug included. An answer that did not include oxytocin, given it is used before, during or after virtually every delivery could not achieve a pass.


Better answers contained more detail such as differentiating the effects of the various prostaglandins, not all of which cause bronchoconstriction. Class-wide side effects such as PPH for tocolytics and foetal asphyxia for drugs increasing uterine tone demonstrated understanding and insight. Discussion of the minimal effect of ketamine at clinically used doses attracted marks.


The question did not ask for mechanisms of action or dosing and infusion regimens. These were commonly provided at length and wasted valuable time.


There were some more common errors. Nifedipine causing bradycardia is rare in this patient cohort; reflex tachycardia is much more common. The serious side effects of magnesium occur at quite high plasma concentrations and are different from those found at lower concentration. The haemodynamic effects of oxytocin and ergometrine were occasionally incorrect. Drugs used in the treatment of pre-eclampsia (labetolol and hydralazine) and other drugs without effects on uterine tone afforded no marks.

## Model Answer

Structure:
- Oxytocics table
- Tocolytic table

### Oxytocics


Note **all risk foetal asphyxia** if given **antepartum**.

||Mechanism of action (MoA) and adverse effects (AE)|
| -- | -- |
|Oxytocin|<p>- Bind oxytocin receptor, a Gq G protein coupled receptor (GPCR)</p><p>- ↑ IP3 → ↑ ICF [Ca^2+^] (also ↑ DAG)</p><p>- At low dose: Intermittent contraction</p><p>- At high dose: Tonic contraction</p><p>- Receptors upregulated from from 36/40</p><p>- AE: N&V, vasodilatation, slightly ADH effect on kidney (V2) → H~2~O reabsorption, hyponatraemia</p>|
|Carbetocin|<p>- Synthetic analogue of oxytocin</p>|
|Ergometrine|<p>- Oxytocic mechanism unclear</p><p>- Causes tonic contraction at any dose cf. oxytocin</p><p>- Known receptor effects:</p><p>&emsp;- α~1~: ↑ SVR, ↑ BP, Risk of APO (Contra-indicated in pre-eclampsia)</p><p>&emsp;- 5HT~2~ Agonist: N&V</p><p>&emsp;- DA Agonist: N&V</p>|
|Misoprostol|<p>- PGE1 analogue</p><p>- Binds PGE2-R → Multiple G protein-coupled receptor subtypes</p><p>- AE: Diarrhoea</p>|
|PGF2α|<p>- MoA: Binds Gq protein-coupled receptor → ↑ ICF Ca^2+^</p><p>- AE: Bronchoconstriction, hypertension, nausea</p>|

### Tocolytics


||Mechanism of action (MoA) and adverse effects (AE)|
| -- | -- |
|Terbutaline|<p>- β~2~ agonist / Gs GPCR → ↑ CAMP → ↑ Inhibition of MLCK</p><p>- AE: ↑ HR (cardiac B2) ↓ K^+^ (↑ Na^+^K^+^ATPase activity), lactic acidosis (β~2~ liver and skeletal muscle), tremor (β~2~ skeletal muscle)</p>|
|Nifedipine|<p>- Inhibit L-Ca^2+^ → ↓ ICF [Ca^2+^]</p><p>- AE: Reflex ↑ HR, peripheral oedema</p>|
|GTN|<p>- Prodrug</p><p>- Reacts with endothelial ICF sulfhydryl groups → NO → Activate GC → ↑ CGMP → ↑ MLCP activity, ↑ Ca^2+^ reuptake, ↑ K^+^ efflux</p><p>- AE: ↓ BP (vascular SM), reflex HR, flushing, headache, metHbaemia (bad in foetus)</p><p>- Note tachyphylaxis (depletion of sulfhydryl groups)</p>|
|Atosiban|<p>- Nonapeptide</p><p>- Competitive antagonist at oxytocin receptor</p><p>- AE: Headache, nausea&vomiting</p>|
|Volatile Anaesthetics|<p>- Inhibit L-Ca^2+^ → ↓ ICF [Ca^2+^]</p><p>- Note ↑ risk sedated neonate</p><p>- ↑ Risk PPH if GA Caesarean</p><p>- Supplement with N~2~O</p><p>- AE: Maternal and foetal anaesthesia, respiratory and cardiovascular depression, nausea and vomiting</p>|


--- 

