# 2018B Question 10 

Outline the mechanisms of action of the drugs, with examples, which increase myocardial contractility.


## Examiner Report

52 % of candidates achieved a pass in this question.


The wording of question points to the focus of the answer. The focus should be the mechanism of action of increasing myocardial contraction, or positive inotropy. Drug examples should then follow as the second part of the answer. Thus, while the breadth and depth of the question are both important, the depth of understanding of the mechanisms of action take precedence.


To pass, candidates were expected to provide 3 or more examples of positive inotropes, and included some discussion on the mechanisms of action. The better candidates were able to provide detailed mechanisms for increasing inotropy first, with some providing up to 6 – 7 examples. Candidates who could only provide a list of various drugs without giving correct mechanism of actions had difficulty passing.


A number of candidates were not able to define myocardial contractility correctly, which should be independent of heart rate, preload and afterload. Candidates who answered the question with purely symbols and/or non-conventional abbreviations to indicate directions of change and mechanisms of action were not able to attain very high marks.

## Model Answer

Structure:
- Intro: Contractility, adrenergic signaling
- Drug table: Class, example, mechanism of action

### Introduction


|Factor|Detail|
| -- | -- |
|Contractility|<p>- Those factors contributing to cardiac performance independent of preload, afterload and heart rate</p><p>- ∝ ICF [Ca^2+^]</p>|
|Adrenergic signaling|<p>- Adrenaline/noradrenaline binds β~1~ adrenoceptor, a Gs G protein coupled receptor (GPCR)</p><p>- Activation of adenylyl cyclase → ↑ CAMP</p><p>- Activation of PKA → Phosphorylation of:</p><p>&emsp;- Myosin: ↑ Rate at which cross-bridge cycling can occur</p><p>&emsp;- Membrane L-Ca^2+^ and sarcoplasmic reticular ryanodine-sensitive Ca^2+^ channel: ↑ Ca^2+^ influx upon activation</p><p>&emsp;- Troponin I and phospholamban: ↑ Rate of relaxation</p>|

### Drugs


|Group|Example|Effect|
| -- | -- | -- |
|Naturally occurring catecholamines|<p>Adrenaline</p><p>Noradrenaline</p><p>Dopamine</p>|Activate β~1~|
|Synthetic catecholamine|<p>Isoprenaline</p><p>Dobutamine</p>|Activate β~1~|
|Non-catecholamine β~2~ agonist|<p>Salbutamol</p><p>Terbutaline</p>|<p>Activate cardiac β~2~ (same cascade as cardiac β~1~)</p><p>More effect on chronotropy and dromotropy than inotropy</p>|
|Indirect β~1~ agonist|<p>Ephedrine</p><p>Metaraminol</p>|↑ NAD release at adrenoceptors|
|PDE3 inhibitors|<p>Milrinone</p><p>Amrinone</p><p>Aminophylline (non-selective)</p>|↓ cAMP breakdown|
|Ca^2+^ sensitizer|Levosimendan|<p>Ca^2+^ sensitization</p><p>Stabilises Ca^2+^/troponin C</p>|
|Other:|Calcium|↑ Gradient for Ca^2+^ into ICF|
||Glucagon|Glucagon R: Gs GPCR → ↑ CAMP|
||Thyroxine|Permissive effect on catecholamines|
||Digoxin|<p>Inhibit cardiac Na^+^K^+^ATPase</p><p>↑ ICF Na^+^</p><p>↑ Activity Na^+^/Ca^2+^ antiporter (3:1)</p><p>↑ ICF [Ca^2+^]</p>|
||Ketamine|<p>↑ SNS output from medulla → ↑ Adrenaline, noradrenaline release</p><p>But direct effect negative inotropy (R-ketamine)</p>|


--- 

