# 2018B Question 06 

Outline the adverse effects which could occur following the rapid transfusion of ten units of packed red cells.


## Examiner Report

80% of candidates achieved a pass in this question.


This question asks about a topic that is core to anaesthetic practice. Better answers included recognition that the rapid administration of ten units of blood constitutes a massive transfusion and were followed by a list of adverse effects with brief explanations of the cause and consequence of each effect. Adverse effects include storage lesion effects, immunological effects, coagulation sequelae, contamination risks and volume related problems. Also, better answers were well organized which reflected the necessary efficiency required to convey the maximal breadth and depth of the topic in 10 minutes. Parts of answers that did not attract any points included rephrasing the question and giving information that did not answer the question, such as detailed explanations of the blood collection process.


## Model Answer

Structure:
- Introduction
- Storage lesion
- Overload
- Dilution
- Metabolic
- Immune
- Infective

### Introduction


|Term|Detail|
| -- | -- |
|Red Cell Unit Contents|<p>- Red cells</p><p>- Small volume plasma</p><p>- Preservative: Sodium, adenine, glucose, mannitol</p>|
|Massive Transfusion|<p>- 50% blood volume in 4 hours, or 100% of BV in 24 hours</p><p>- 10 units = 2.5L = 50% blood volume</p>|
|Ideal ratio of RBC:FFP:platelet|<p>- 1:1:1</p><p>- May be situation-dependent</p>|
|Lethal Triad|<p>- Acidosis</p><p>- Hypothermia</p><p>- Coagulopathy</p>|

### Storage Lesion


|Factor|Detail|
| -- | -- |
|Definition|Adverse effects associated with storage of blood, that increase with the duration of red cell storage.|
|Cells|<p>- Red cells: Spheroidal, rigid, fragile; 25% loss at 4/52<br>  (free Hb 1 → 30μg/mL)</p><p>- White Cells: Inactivate but still antigenic</p><p>- Platelets: Inactivated at 48 hours?</p>|
|Coagulation Factors|<p>- Minimal since plasma removed</p><p>- FV 50% at 3/52</p><p>- FVIII 30% at 3/52</p>|
|Metabolic|<p>- Temp 4°C</p><p>- pH 7.4 → 6.7 (due to additives)</p><p>- K^+^ 4→30mM</p><p>- Ca^2+^ 2mmol.L^-1^ → ? (due to 3mg citrate)</p><p>- ATP 75%</p><p>- [2,3-DPG]: 50% at 2/52, 5% at 4/52 (due to low temp)</p><p>- ↑ Free haemoglobin</p>|

### Overload


|Of:|Detail|
| -- | -- |
|Fluid|<p>- ↑ Blood volume → ↑ Preload</p><p>- May cause heart failure</p><p>- High risk if LV impairment</p>|
|Iron|<p>- Haemolysis → Hb breakdown → ↑ Free haemoglobin</p><p>- Risk of haemochromatosis → Damage to liver, pancreas, heart, pituitary</p>|
|Microaggregates|<p>- Microvascular occlusion → Multi-organ dysfunction (especially lung)</p>|

### Dilution


|Of:|Detail|
| -- | -- |
|Coagulation Factors|<p>- Dilutional coagulopathy</p><p>&emsp;- Coagulation factors esp fibrinogen</p><p>&emsp;- Platelets</p>|
|Plasmas|<p>- Hyperviscosity</p><p>&emsp;- ↑ Risk thromboembolism</p><p>&emsp;- ↑ Resistance to flow, ↑ myocardial work</p>|

### Metabolic


|Factor|Detail|
| -- | -- |
|↓ Temperature|<p>- Arrest if rapid via CVC</p><p>- Coagulopathy</p>|
|↓ pH|<p>- Arrest if rapid via CVC</p><p>- Negative inotropy</p><p>- Generalized metabolic dysfunction</p>|
|↑ K^+^|<p>- Arrhythmia, arrest if rapid via CVC</p><p>- Most K^+^ taken up by RBC upon transfusion</p>|
|↓ Ca^2+^|<p>- Arrhythmia, muscle weakness</p><p>- (Note hypocalcaemia severe enough to cause coagulopathy would already have caused cardiac arrest)</p>|
|↓ 2,3-DPG|- Left shift oxy-haemoglobin dissociation curve → ↓ Tissue oxygenation|

### Immunological


|Reaction|Detail|
| -- | -- |
|Febrile non-haemolytic|- Donor WBC → Cytokine release, fever|
|Febrile haemolytic|<p>- i.e. Result if incompatible blood transfusion</p><p>- Donor RBC Ag + host RBC Ab → Haemolysis</p><p>&emsp;- ABO intravascular</p><p>&emsp;- RhD extravascular (reticuloendothelial system)</p>|
|Anaphylaxis|- Especially IgA deficient host|
|TRALI|- Donor Ab + host WBC → Non-cardiogenic APO within hours|
|Cancer recurrence|<p>- Increased risk</p><p>- Mechanism unknown</p>|

### Infective


|Disease|Detail|
| -- | -- |
|Bacteria|Septicaemia in 3% (certain pseudomonas species can multiply in the cold)|
|Viruses|HBV, HCV, HIV; CMV|
|Parasites|Malaria|
|CJD||


--- 

