# 2018B Question 09 

# Describe the autonomic innervation of the heart (60%), and the effects of autonomic stimulation on cardiac function (40%).


## Examiner Report

67% of candidates achieved a pass in this question.


To pass the first part of this question (60%), a description of the anatomy of cardiac autonomic supply was required. This was best done in a systematic manner starting from the origins of the cardiac sympathetic and parasympathetic fibres to the course that these nerves traverse to the heart. Answers that included a discussion of the differential cardiac distribution of the right and left branches of both divisions scored higher marks.


The second part of the question (40%) called for a discussion of the physiological effects of stimulation of these nerves on cardiac function. Better answers avoided the use of clichés such as “rest and digest” to describe the parasympathetic system since the beating heart performs neither of these functions. Although both divisions of the autonomic system function in a reciprocal manner, their actions are not merely the opposite of each other. An example is the effect of parasympathetic stimulation on contractility of the heart, which is not due to muscarinic stimulation but to interneuronal interactions at the level of nerve endings.


Candidates who gave correct reasons for the brief latency and rapid decay of vagal stimulation as well as the slow onset and gradual offset of sympathetic stimulation were awarded extra marks. Those who mentioned the different effects of right and left sided stimulation of both divisions on cardiac function were given bonus marks. Many candidates spent too much time on unnecessary biochemical details on receptor function. A full discussion of the baroreceptor reflex was not required for a pass in this section.

## Model Answer

Structure:
- General features
- Main actions
- Autonomic efferents
- General visceral afferents

### General Features


||SNS|PNS|
| -- | -- | -- |
|Resting tone|↓ |↑ |
|Exercise|↑ |↓ |
|Onset speed|<p>↓ </p><p>Effects via 2nd messenger cAMP</p>|<p>↑ </p><p>ACh directly activates special KACh channel</p>|
|Offset speed|Slower (Reuptake of NAD)|<p>↑ </p><p>(AChE +++ at synapse)</p>|
|Beat-to-beat regulation|No|Yes|
|Baroreceptor reflex effect|↓ MAP → ↓ Stretch → Disinhibited|↓ MAP → ↓ Stretch → Inhibited|

### Main Actions


||SNS|PNS|
| -- | -- | -- |
|Inotropy|↑ |↔ ↓ |
|Chronotropy|↑ |↓ |
|Dromotropy|↑ |↓ |
|Lusitropy|↑ |↔|

### Autonomic Efferents


||SNS|PNS|
| -- | -- | -- |
|Pre-motor|- Rostral ventrolateral medulla|-|
|Pre-ganglionic|<p>- Lateral horn </p><p>- C7-T6; mostly T1-4; bilateral</p><p>- (nicotinic)</p>|<p>- Nucleus ambiguus</p><p>- Dorsal motor nucleus of CNX</p><p>- (nicotinic)</p>|
|Post-ganglionic|<p>- Stellate and middle cervical ganglia</p><p>(adrenergic)</p>|<p>- Epicardial ganglion</p><p>(muscarinic)</p>|
|Cardiac Plexus|- After synapse|- Before synapse|
|Asymmetry|<p>- ?L SNS to myocardium</p><p>- ?R SNS to SA and AV nodes</p>|<p>- L CNX to AV node</p><p>- R CNX to SA node</p><p>- (mostly)</p>|
|Myocyte Effect|<p>- β~1~ adrenoceptor 85%, β~2~ 15%</p><p>- (Gs GPCR)</p><p>- Ventricules > atria</p><p>- ↑ CAMP</p><p>- ↑ PKA</p><p>- Phosphorylation of</p><p>- L-Ca^2+^ channel → ↑ Inotropy</p><p>- Myosin → ↑ Rate cross-bridge cycling</p><p>- Phospholamban, TNI → ↑ Rate relaxation</p>|<p>- m2AChR</p><p>- (Gi GPCR)</p><p>- Atria > ventricles</p><p>- Minimal direct mAChR effect</p><p>- ↓ Inotropy via interneuronal effect</p>|
|Pacemaker Cell|<p>- β~1~ and β~2~</p><p>- ↑ CAMP</p><p>- ↑ Activity HCN channel</p><p>- ↑ If = ↑ ICa > ↑ IK</p><p>- ↑ Slope all phases (mostly phase 4)</p>|<p>- m2AChR</p><p>- ↓ CAMP</p><p>- ↑ IK</p><p>- ↓ Slope phase 4</p><p>- ↑ Max negative potential</p>|
|Coronary Arteries|<p>- β~1~, α~1~</p><p>- Direct constrict</p><p>- Indirect ↑ work → Dilatation (autoregulation</p>|<p>- ?Receptor</p><p>- Direct dilatation</p><p>- Indirect ↓ work → Constriction (autoregulation)</p>|
|Adrenal Medulla|<p>- ~80% adrenaline</p><p>- ~20% noradrenaline</p>|- Nil|

### General Visceral Afferents


|Factor|Detail|
| -- | -- |
|Primary Afferent|<p>- Unmyelinated C fibre</p><p>- Piggybacks onto autonomic efferents</p><p>&emsp;- With SNS: Via white ramus communicans to spinal cord T1-L12</p><p>&emsp;- With PSNS: Via sacral nerves to S2-4 (also cranial)</p><p>- Direct synapse with wide dynamic range 2° afferents in deeper layers</p><p>- Convergence onto somatic nociceptive-specific 2° afferents in superficial layers<br>  (hence referred pain)</p>|
|Secondary Afferent|<p>- Decussation via anterior commissure</p><p>&emsp;- Incomplete for older pathways (hence bilateral pain but L>R)</p><p>- Ascent via multiple spinothalamic tracts</p>|


--- 

