# 2018B Question 08 

Briefly outline the functions of the kidney.


## Examiner Report

73% of candidates achieved a pass in this question.


Specialist anaesthetic practice requires a clear understanding of kidney function. Beyond homeostasis of water and electrolytes, many physiology and pharmacology references cover kidney functions in the context of broader topics. For example, metabolic processes, including drug and chemical biotransformation, may be better understood from pharmacokinetic chapters. Endocrine functions may be covered in a corresponding section of text; such as erythropoietin secretion which is typically described in red blood cell production.


To pass, candidates were required to give a broad list of functions including water and electrolyte homeostasis and excretion of metabolic waste products PLUS at least two other functions. It was further required that there was some discussion about the significance of these functions and underlying mechanisms.

## Model Answer

Structure:
- Salt and water
- Other electrolytes
- Metabolism
- Excretion
- Erythropoiesis


### Salt and Water


|Factor|Detail|
| -- | -- |
|Overall Function|<p>- Control water content</p><p>- Control water partitioning (ECF vs. ICF)</p><p>- Control osmolality</p>|
|Summary of Renal Handling|<p>- Free glomerular filtration water (180L.day^-1^) and electrolytes</p><p>- Selective tubular reabsorption</p><p>- Urine output only ~2L.day^-1^ and variably concentrated</p>|
|Autoregulation|<p>- Glomerular filtration rate:</p><p>&emsp;- Constant 125mL.min^-1^ at MAP 70-170mmHg</p><p>&emsp;- Mechanism: ↓ Stretch → ↓ Afferent arteriolar constriction</p><p>- Glomerulotubular balance:</p><p>&emsp;- Constant fraction of Na^+^/Cl-/H~2~O reabsorbed from proximal tubule</p><p>&emsp;- Mechanism: ? ↑ Glucose and amino acid absorption → ↑ Osmosis</p><p>- Tubuloglomerular feedback:</p><p>&emsp;- ↓ NaCl load to macula densa → Afferent arteriolar dilation → ↑ GFR</p><p>&emsp;- Mechanism: ↑ PGE2, ↓ adenosine</p>|
|Hormonal control|<p>- RAAS:</p><p>&emsp;- Renin source: Granular cells of juxtaglomerular apparatus</p><p>&emsp;- Renin release stimuli: A) hypoperfusion b) SNS stimulation c) low Na^+^Cl- load to distal tubule</p><p>&emsp;- End result: ↑ reabsorption of Na^+^, H~2~O → ↑ ECF volume</p><p>- ADH:</p><p>&emsp;- Source: Hypothalamus</p><p>&emsp;- Release stimuli: ↑ osmolality (∆2%) ↓ MAP, ↓ blood volume (∆10%), angiotensin 2</p><p>&emsp;- End result: ↑ H~2~O reabsorption only → ↑ Total body water and ↓ osmolality</p><p>- ANP:</p><p>&emsp;- Source: Right atrium</p><p>&emsp;- Release stimuli: Distension</p><p>&emsp;- End result: ↑ GFR, ↓ Na^+^/H~2~O reabsorption from distal nephron (natriuresis)</p>|

### Salt and Water: By location


|Region|Na^+^ reabsorption|H~2~O reabsorption|
| -- | -- | -- |
|Proximal tubule|65%|65%|
|Thin descending loop of Henle|-|10%|
|Thick ascending loop of Henle|25%|-|
|Distal convoluted tubule|5%|-|
|Collecting duct|4-5%|5-24.7%|

### Other Electrolytes


|Substance|Detail|
| -- | -- |
|Potassium|<p>- Free filtration: 180L.day^-1^ x 4mM = 720mmol per day</p><p>- Fixed reabsorption 95% (proximal tubule 65%, loop of Henle 30%)</p><p>- Compulsory excretion 5%</p><p>- Variable secretion (stimulated by aldosterone)</p>|
|Calcium|<p>- Proximal tubule: PO43- reabsorption</p><p>&emsp;- ↑ : Vit D</p><p>&emsp;- ↓ : PTH, calcitonin</p><p>- Distal tubule: Ca^2+^ reabsorption</p><p>&emsp;- ↑ : Vit D, PTH</p><p>&emsp;- ↓ : Calcitonin</p>|

### Acid-Base


|Factor|Detail|
| -- | -- |
|Reabsorption of HCO~3~^-^|<p>- 4000-5000mmoL.day^-1^</p><p>- 85% prox tubule, 10% thick ascending LOH, 5% distal tubule and collecting duct intercalated cells</p><p>- ↑ ECF HCO~3~^-^ → Shift in carbonic acid equilibrium (H~2~O + CO~2~ ↔ H+ + HCO~3~^-^)</p>|
|Excretion of titratable acid|<p>- Phosphoric acid 30mmoL.day^-1^ (up to 60mmoL.day^-1^)</p><p>- H~2~PO~4~ ↔ H^+^ + HPO~4~^-^ (pKa 6.8)</p>|
|Excretion of ammonia|<p>- 70mmmoL.day^-1^ (up to 300)</p><p>- 60% deamination of glutamine, 35% filtered by glomerulus, 5% deamination of other amino acids</p><p>- Glutamine → 2NH~4~^+^ + 2HCO~3~^-^ + oxoglutarate</p><p>- HCO~3~^-^ reabsorbed</p><p>- NH~4~^+^ secreted by Na^+^/NH~4~^+^ antiporter. 70% reabsorbed in LOH, recycled</p>|

### Metabolism


|Factor|Detail|
| -- | -- |
|Gluconeogenesis|<p>- Glutamine → Oxaloacetate → Glucose (?)</p><p>- Supplies obligate glucose users (brain, RBCs)</p><p>- Important in starvation</p>|
|Detoxification|<p>- CYP450 enzymes</p><p>- e.g. CYP2E1 metabolises 70% methoxyflurane</p>|

### Excretion


|Factor|Detail|
| -- | -- |
|Exogenous waste|<p>- Creatinine as creatinine</p><p>- Amino acids as urea</p>|
|Drug metabolites|<p>- Especially if large, water-soluble</p><p>- e.g. Morphine-6-glucuronide</p><p>- e.g. Pancuronium</p><p>(Accumulation in renal failure)</p>|

### Erythropoiesis


|Factor|Detail|
| -- | -- |
|In health|- ↓ PO~2~ in interstitium → ↑ EPO secretion by interstitial fibroblasts → ↑ Differentiation of pluripotent haem stem cells to erythroblasts|
|In renal failure|- ↓ Renal metabolic rate → ↑ PO~2~ in interstitium → ↓ EPO → Anaemia|


--- 

