# Erythrocytes

:::CICM
Outline the physiological production of blood and its constituents
:::

:::ANZCA
Describe the physiological consequences of acute and chronic anaemia~~, including iron deficiency~~.
:::

Erythrocytes:

* Are **7.5μm** in **diameter**\
* Are 2um thick
* Have a lifespan of **120 days**
* Have:
    * No nucleus\
    Maximises cell volume available for Hb.
    * No mitochondria\
    Cannot perform aerobic metabolism - all ATP is generated via glycolysis.
    * No ribosomes\
    Incapable of producing protein
* Have a **biconcave disc** shape\
This maximises surface area (optimising gas transfer) and makes the cells flexible enough to pass through capillary beds (which are narrower than the cell).
* Are important in:
    * Delivering O~2~ to the tissues and delivering CO~2~ to the lungs
    * Acid-Base balance
    * Metabolism of some drugs
* Carry ~29pg of haemoglobin
* Comprise 40-50% of blood volume


## Production

Erythrocytes have a **myeloid progenitor** which differentiates into the myeloid line. EPO stimulates myeloid progenitor cells to **differentiate** and then **proliferate**:

* Proerythroblasts begin synthesis of Hb, with ongoing production occurring until the cell is mature
* Further differentiation results in successive **loss of organelles**, **increasing Hb content**
* The loss of **ribosomes** and **nucleus** of the reticulocyte are the final stage of erythropoiesis
* The entire process takes ~7-10 days

:::column-margin
EPO is covered in detail under @sec-renal_endo.
:::


## Function

* Gas Carriage
* Acid-Base Buffering
    * Production of HCO~3~^-^
    * Binding of H^+^ to Hb
* Metabolism\
Esterases (and other -ases) in erythrocytes metabolise many drugs, including:
    * Remifentanil
    * SNP\
    Reacts with Hb to form NO, CN, and Met-Hb.
    * Esmolol


## Elimination

Old red cells are removed from circulation via:

* **Phagocytosis** by macrophages in:
    * Spleen\
    Major mechanism.
    * Liver
    * Bone marrow
* **Haemolysis**\
~10% of red cell breakdown occurs in circulation, where the Hb dimers are then bound to **haptoglobin** by haemopexin.
    * This is important to prevent glomerular filtration of haeme, and loss of iron


### Haemoglobin Metabolism

**Haemoglobin** is broken down into:

* **Globin**\
Broken down into constituent amino acids.
* **Iron**\
Re-enters haemoglobin synthetic pathway.
* **Haeme**\
Complex metabolic pathway, notable as it is the only metabolic process that produces **carbon monoxide**:
    * Metabolised to **biliverdin** by splenic macrophages in the reticuloendothelial system of the **spleen**
        * Circulating erythrocytes are phagocytosed by splenic macrophages
        * Haptoglobin binds circulating Hb, the Hb-Haptoglobin complex is then phagocytosed by splenic macrophages
    * **Biliverdin** is reduced **to unconjugated bilirubin**\
This is fat soluble, and binds to albumin.
    * **Unconjugated bilirubin** is conjugated in the liver to **conjugated bilirubin**
    * **Conjugated bilirubin** is **secreted in bile** by active transport\
    This is impaired during hepatic disease, leading to increased bilirubin levels in plasma.
    * Secreted **conjugated bilirubin** is metabolised **to urobilinogen** by gut bacteria
    * **Urobilinogen** may have a number of fates:
        * Enterohepatic recirculation and elimination in bile (again)
        * Further metabolism by gut bacteria to **stercobilinogen** and then to **stercobilin**
        * Enterohepatic recirculation and urinary excretion, where it is oxidised to **urobilin**


: Alterations to Bilirubin Metabolism in Disease

+--------------------------+--------------------------+-----------------------+---------+
|                          | Blood                    | Urine                 | Faeces  |
+==========================+==========================+=======================+=========+
| **Prehepatic disease**   | ↑ Unconjugated bilirubin | ↑ Urobilinogen\       | Normal  |
|                          |                          | Bilirubin not present |         |
+--------------------------+--------------------------+-----------------------+---------+
| **Intrahepatic disease** | ↑ Conjugated bilirubin\  | Bilirubin present     | Acholic |
|                          | ↑ Unconjugated bilirubin |                       |         |
+--------------------------+--------------------------+-----------------------+---------+
| **Posthepatic disease**  | ↑ Conjugated bilirubin   | ↓ Urobilinogen\       | Pale    |
|                          |                          | Bilirubin present     |         |
+--------------------------+--------------------------+-----------------------+---------+

:::column-margin
Acholic stools describes a pale or clay-coloured stool that occurs due to ↓ urobilinogen excretion in bile.
:::

---

## References

1. Barrett KE, Barman SM, Boitano S, Brooks HL. Ganong's Review of Medical Physiology. 24th Ed. McGraw Hill. 2012.
