# Transfusion Reactions

:::CICM
Understand the adverse consequences of blood transfusion, including that of massive blood transfusion ~~and storage lesions~~.
:::

:::ANZCA
Describe ~~blood groups and~~ the physiological basis of transfusion reactions.
:::


A transfusion reaction is an adverse event associated with the transfusion of whole blood or one of its components, and can be classified as either:

* Acute (< 24 hours) or delayed (> 24 hours)
* Immunological or non-immunological

## Immunological Acute Reactions

: Acute, Immunological Transfusion Reactions

| Reaction                | Incidence                      | Mechanism                                                                                                                                                                                              |
|-------------------------|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ABO Mismatch            | 1:40,000                       | ABO incompatibility causing rapid intravascular haemolysis, which may cause chest pain, jaundice, shock, and DIC. RhD-reactions tend to cause extravascular haemolysis.                                |
| Haemolytic (acute)      | 1:76,000 (1:1.8 million fatal) | Immunological destruction of transfused cells (Type II hypersensitivity). Presents with fever, tachycardia, pain, progressing to distributive shock                                                    |
| Febrile, non-haemolytic | ~1:100                         | Cytokine release from stored cells causing a mild inflammatory reaction, with temperature rising to ≥38ºC or ≥1ºC above baseline (if >37ºC). Benign - but requires exclusion of a haemolytic reaction. |
| Urticaria               | 1:100                          | Hypersensitivity to plasma proteins in the transfused unit                                                                                                                                             |
| Anaphylaxis             | 1:20,000                       | Type I hypersensitivity reaction to plasma protein in transfused unit                                                                                                                                  |
| TRALI                   | Variable                       | Donor plasma HLA activates recipient pulmonary neutrophils, causing fever, shock, and non-cardiogenic pulmonary oedema                                                                                 |


## Non-Immunological Acute Reactions

: Acute, non-Immunological Transfusion Reactions

| Reaction                                        | Incidence                             | Mechanism                                                                                                                                                              |
|-------------------------------------------------|---------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Massive Transfusion Complications               | Variable                              | See below                                                                                                                                                              |
| Non-immune mediated haemolysis                  | Rare                                  | Due to physicochemical damage to RBCs (freezing, device malfunction). May lead to haemoglobinuria, haemoglobinaemia, tachycardia and fevers.                           |
| Sepsis                                          | 1:75,000 (platelets), 1:500,000 (RBC) | Contamination during collection or processing. Most common organisms are those which use iron as a nutrient and reproduce at low temperatures, e.g. *Yersinia Pestis*. |
| Transfusion Related Circulatory Overload (TACO) | <1:100                                | Rapid increase in intravascular volume in patients with poor circulatory compliance or chronic anaemia. May result in pulmonary oedema and be confused with TRALI.     |


## Delayed Immunological Reaction

: Delayed, Immunological Transfusion Reactions

| Reaction                                | Incidence                                 | Mechanism                                                                                                                           |
|-----------------------------------------|-------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| Delayed haemolytic transfusion reaction | 1:2,500                                   | Development of sensitisation with the reaction occurring 2-14 days after a single exposure. Typically Kidd, Duffy, Kell antibodies. |
| Post-transfusion Purpura                | Rare                                      | Alloimmunisation to Human Platelet Antigen causing sudden self-limiting thrombocytopenia                                            |
| TA-GVHD                                 | Rare                                      | Transfused lymphocytes recognise host HLA as positive causing marrow aplasia, with mortality >90%                                   |
| Alloimmunisation                        | 1:100 (RBC antigens), 1:10 (HLA antigens) | Previous sensitisation leading to  antibody production on re-exposure.                                                              |
| Transfusion-related Immune Modulation   | Not known                                 | Transient immunosuppression following transfusion potentially due to cytokine release from leukocytes                               |

## Delayed Non-Immunological Reaction

: Delayed, non-Immunological Transfusion Reactions

| Reaction      | Incidence                                                   | Mechanism                                                                           |
|---------------|-------------------------------------------------------------|-------------------------------------------------------------------------------------|
| Iron Overload | Chelation after 10-20 units, organ dysfunction 50-100 units | Each unit of PRBC contains ~250mg of iron, whilst average excretion is 1mg.day^-1^. |


## Complications of Massive Transfusion

A **massive transfusion** is one where:

* Greater than **one-half** of **circulating volume** in **4 hours**
* Whole **circulating volume** in **24 hours**

:::column-margin
Risk of complication from a massive transfusion is influenced by:

* Number of units
* Rate of transfusion
* Patient factors
:::

: Complications of Massive Transfusion

| Complication     | Mechanism                                                                    |
|------------------|------------------------------------------------------------------------------|
| Air embolism     | Inadvertent infusion                                                         |
| Hypothermia      | Cooled products                                                              |
| Hypocalcaemia    | Consumption with coagulopathy and bound to citrate added to transfused units |
| Hypomagnesaemia  | Bound to citrate in transfused units                                         |
| Citrate toxicity | Citrate is added to stored units as an anticoagulant                         |
| Lactic acidosis  | Hyperlactataemia due to anaerobic metabolism in stored units                 |
| Hyperkalaemia    | Potassium migrates from stored erythrocytes into plasma whilst in storage    |

---

## References

1. Blood Service. [Classification & Incidence of Adverse Events](http://www.transfusion.com.au/adverse_transfusion_reactions/classification_and_incidence). Australian Red Cross.
2. National Blood Authority. [Patient Blood Management Guidelines](http://www.blood.gov.au/pbm-guidelines). Australian Red Cross.
3. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
