# Variations in Upper Airway Anatomy

:::CICM
Understand the differences encountered in the upper airway for neonates, children and adults.
:::

## Neonates and Children

Changes are most obvious below 1 year of age, and typically resolve by ~8 years of age.

* Head and neck changes
    * Obligate nose breathers\
    Nasal obstruction may significantly impair respiration.
    * Proportionally **enlarged head** and occiput\
    Optimal intubating position is neutral rather than ramped.
    * Proportionally **short neck**\
    Favours airway obstruction when flexed.
* Laryngeal changes
    * Disproportionately **large tongue** that complicates laryngoscopy
    * **Epiglottis** is **u-shaped**, **longer**, and **stiffer**
    * **Larynx lies at C4** (rather than C6 in adults)
    * Narrowest part of the upper airway is **the transverse diameter of the vocal cords**^[The cricoid used to be thought of the narrowest part of the child's airway, but this has been subsequently disproved.]\
* Intrathoracic changes
    * Intrathoracic trachea is also shorter\
    May be only 4cm long, so there is little margin for error in tube placement.
    * Left and right bronchi arise at similar angles, so endobronchial intubation may occur on either side
    * Airways themselves are narrower, and have a higher resistance to flow. 

---

## References

1. Nickson, C. [Paediatric Airway](http://lifeinthefastlane.com/ccc/paediatric-airway/). LITFL.
2. Anderson, C. [Anatomy of the Respiratory system.](https://icuprimaryprep.files.wordpress.com/2012/05/anatomy-of-the-respiratory-system-22.pdf). ICU Primary Prep.
3. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
4. Tobias JD. Pediatric airway anatomy may not be what we thought: implications for clinical practice and the use of cuffed endotracheal tubes. Paediatr Anaesth. 2015 Jan;25(1):9-19.