# Humidification

:::CICM
Define humidity and give an outline of the importance of humidification
:::

Humidification:

* Describes the amount of water vapour present in air^[**Moisture** is the water produced by condensation when relative humidity exceeds 100%.]:
    * **Absolute Humidity** is the amount of water vapour in a given volume of air (g.m^-3^)
    * **Relative Humidity** is the ratio between the amount of water vapour in a sample of air (absolute humidity) and the amount of water required to fully saturate that sample at its current pressure and temperature
* Of inspired air is important to avoid drying out mucosa and sputum, which leads to tissue damage and failure of the mucociliary elevator\
Optimal function requires a relative humidity of **greater than 75%**.

## Mechanism

The nose is:

* Optimised for humidification\
The **septum** and **turbinates** increase contact of air with mucosal surfaces by:
    * Increasing **surface area**
    * Generating **turbulent flow**
* The preferred orifice for breathing unless airways resistance becomes a significantly limiting factor\
This is relevant in:
    * Airway obstruction (e.g. polyps)
    * At high minute ventilations (> 35L.^-1^)
* Humidifies inspired gas to 90%, compared to **60%** for the mouth

Method of humidification:

* Fluid lining the airway acts as a heat and moisture exchanger
* In inspiration:
    * Relatively dry air is evaporates water from the airway lining
    * Relative humidity is increased to 90% in the nasopharynx and 100% BTPS by the second generation of bronchi\
    This gives a water vapour pressure of **47mmHg** at BTPS, with an absolute humidity of **44g.m^-3^**.
* In expiration:
    * Air cools in the upper airway\
 As cooler air has a lower saturated vapour pressure, moisture condenses on the airway.
    * Moisture is reabsorbed\
    This reduces potential water losses from the airway from **300ml.day^-1^** to **150ml.day^-1^**.

---

## References

1. Lumb A. Nunn's Applied Respiratory Physiology. 7th Edition. Elsevier. 2010.
2. WeatherFaqs. [Absolute and Relative Humidity](http://weatherfaqs.org.uk/node/29).
3. CICM September/November 2012