# Hypoxia

:::CICM
Explain the physiological effects of hyperoxia, **hypoxaemia**, hypercapnia, hypocapnia, and carbon monoxide poisoning.
:::

* **Hypoxaemia** is a low partial pressure of oxygen in blood
* **Hypoxia** is an oxygen deficiency at the **tissues**, due to:
    * Impaired **oxygen delivery**
    * Impaired **oxygen extraction**
 
 
Oxygen delivery is given by the equation:
$$DO_2 = HR \times SV \times (1.34 \times[Hb] \times SpO_2 + PaO_2 \times 0.03)$$

Where:

* 1.34 is Hüfner's constant\
  This is the oxygen carrying capacity of haemoglobin, in ml.g^-1^ (of Hb).
    * The theoretical maximum is 1.39
    * *In vivo* it is 1.34 due to the effect of carboxyhaemoglobin and methaemoglobin compounds, which limit O~2~ binding
* 0.03 is the solubility coefficient of O~2~ in water at 37ºC, in mls.L^-1^.mmHg^-1^\
Can also be expressed as 0.003 mls.dL^-1^.mmHg^-1^ (mls per deciliter per mmHg). Different texts use different values, depending on whether haemoglobin is reported in g.L^-1^ or g.100ml^-1^.

## Classifications and Causes of Hypoxia

Hypoxia can be categorised into four types:

* Hypoxic hypoxia
* Anaemic hypoxia
* Ischaemic hypoxia
* Histotoxic hypoxia

### Hypoxic Hypoxia

Hypoxic hypoxia, or **hypoxaemia**, is hypoxia due to low PaO~2~ (and therefore low SpO~2~), typically defined as a PaO~2~<60.

Causes of hypoxaemia can be further classified based on their A-a gradient:

* Causes of hypoxaemia with a **normal A-a gradient**:
    * Low PiO~2~
    * Decreased alveolar ventilation
* Causes of hypoxaemia with a **raised A-a gradient**:
    * Diffusion limitation
    * Shunt
    * (Increased oxygen extraction)


#### Low FiO~2~

Hypoxaemia occurs at high altitudes when the PO~2~ is decreased.

#### Decreased Alveolar Ventilation\

A fall in alveolar ventilation ($\dot{V_A} = Respiratory \ Rate \times (V_T - V_D)$) causes a rise in PACO~2~, and therefore decreases PAO~2~. Decreased V~A~ can occur with:

* Respiratory centre depression:
    * Drugs
    * Head injury (Raised ICP, closed head injury)
    * Encephalopathy
    * Fatigue
* Nerve dysfunction:
    * Spinal cord injury
    * GBS
    * MND
* NMJ dysfunction:
    * Paralysis
    * MG
* Muscular dysfunction:
    * Myopathy
    * Fatigue
    * Malnutrition
    * Dystrophy
* Chest wall abnormalities:
    * Kyphoscoliosis
    * Ankylosing Spondylitis
    * Pleural fibrosis

#### Diffusion Limitation\

Impaired diffusion of O~2~ across the membrane results in a lowered PaO~2~. Diffusion limitation occurs due to:

* Decreased alveolar surface area
* Increased alveolar capillary barrier thickness
  * Pulmonary fibrosis
  * ARDS

#### Shunt\

Shunt occurs when **blood reaches the systemic circulation without being oxygenated via passage through the lung**. With respect to shunt^[Shunt physiology is explored in more detail under [shunt](shunt.md)]:

* As the alveolus is **perfused** but **not ventilated**, thus the **V/Q ratio is 0**
* Administration of 100% O~2~ has less effect on PaO~2~ as shunt fraction increases
    * Oxygen content of shunted alveoli is identical to mixed venous content
    * Oxygen content of non-shunted alveoli does not increase appreciably at high partial partial pressures as haemoglobin is already fully saturated

#### Increased Oxygen Extraction

* Increased oxygen extraction (VO~2~) will not typically cause hypoxia
* This is because:
    * Normal VO~2~ is 250ml.min^-1^
    * Normal DO~2~ is 1L.min^-1^\
    * Maximal oxygen extraction ratio is ~70% (though it varies between organs)\
    Therefore VO~2~ can increase until it reaches 70% of the DO~2~, a point called critical DO~2~.
* However, it may worsen hypoxia in the presence of a supply-side (DO~2~) pathology


### Anaemic Hypoxia

* Impaired oxygen delivery due to low Hb
* Typically asymptomatic at rest but limits exercise tolerance

* Compensation occurs by increasing levels of 2,3-DPG, causing a right-shift in the Hb-O~2~ dissociation curve to favour oxygen off-loading at tissues

#### Carbon Monoxide Poisoning

* CO poisoning is classified as a subset of anaemic hypoxia as carboxyhaemoglobin **reduces** the **effective** amount of **haemoglobin** in solution
* CO has 210 times the affinity for Hb than O~2~
    * CO rapidly displaces O~2~ from Hb and is liberated slowly
* CO poisoning causes headache and nausea, but no increased respiratory drive since the PaO~2~ is unchanged

### Ischaemic Hypoxia

* Ischaemic hypoxia is due to impaired cardiac output resulting in impaired oxygen delivery

### Histotoxic Hypoxia

* Histotoxic hypoxia is due to impaired tissue oxidative processes, preventing utilisation of delivered oxygen
* Most common cause of histotoxic hypoxia is cyanide poisoning, which inhibits cytochrome oxidase and prevents oxidative phosphorylation
* Managed by using methylene blue or nitrites, which form methaemoglobin, in turn reacting with cyanide to form the non-toxic cyanmethaemoglobin

## Effects of Hypoxia

* With a normal PaCO~2~, PaO~2~ must fall to 50mmHg before an increase in ventilation occurs
* With a rising PaCO~2~, a fall in PaO~2~ below 100mmHg will stimulate ventilation via action on carotid and aortic body chemoreceptors
    * The effects of each stimuli are synergistic, and greater than what is seen with either effect alone
* Prolonged hypoxaemia will also lead to cerebral acidosis (via anaerobic metabolism), which will stimulate central pH receptors and stimulate ventilation

### Acid-Base Changes

* Hypoxia results in both fixed and volatile acid-base disturbances
* Anaerobic metabolism results in **lactate** production
* Production of fixed acid results in a **base deficit**, and a low bicarbonate
* Hypoxia and metabolic acidosis stimulate ventilation and hypocarbia

### CO~2~ retention

* In chronic hypercarbia the CSF pH normalises (as bicarbonate is secreted into CSF), with a raised CO~2~
* Fall in PaO~2~ becomes the predominant stimulus for ventilation

---

## References

1. West J. Respiratory Physiology: The Essentials. 9th Edition. Lippincott Williams and Wilkins. 2011.
2. Barrett KE, Barman SM, Boitano S, Brooks HL. Ganong's Review of Medical Physiology. 24th Ed. McGraw Hill. 2012.
3. CICM July/September 2007
4. ICU Basic Book.