# Non-Respiratory Functions

:::dual
Outline the non-ventilatory functions of the lungs
:::

The lungs are a unique organ as:

* The entire cardiac output passes though the pulmonary circulation
* They have a huge capillary bed which almost all of this blood volume
* They have a large interface with the external environment

Consequently they are adapted to a number of non-respiratory functions which include:

```{marginfigure}
An alternative mnemonic:
- **F**iltration\
- **I**mmune defence\
- Blood **r**esevoir\
- **M**etabolism\
- **T**aking up drugs\
- (**I**nhalational Anaesthetics)\
- **S**ynthetic\
- Endocrine
```

* Filtration
* Metabolism
* Blood resevoir
* Defence
* Drug delivery
* Endocrine

## Filtration

The entire cardiac output passes through the 7μm pulmonary capillaries, which act as an effective sieve for particulate matter. This function may be impaired by intra-cardiac shunting (e.g. PFO) or pre-capillary anastomoses.

Complementing this role, the lungs are able to clear thrombi more rapidly than other organs as pulmonary endothelium has a high concentration of plasmin activator and heparin.

## Metabolism

The pulmonary endothelium has a variety of effects on drugs and endogenous hormones:

|              Class               |        Activated        |     Inactivated      |
|----------------------------------+-------------------------+----------------------|
| **Amines**                       |                         | 5-HT, Noradrenaline  |
| **Peptides**                     | Angiotensin I (via ACE) | Bradykinin, ANP      |
| **Arachidonic acid derivatives** | Arachidonic acid        | Many prostaglandins  |
| **Other Drugs**                  |                         | Lignocaine, fentanyl |

## Blood Reservoir

The highly compliant pulmonary circulation contains a resevoir of ~500ml of blood which acts as a **volume reserve** for the LV.

## Defence

The large surface area required for gas exchange leaves the lung vulnerable to invasion by airborn substances. This is attentuated by:

* Mucous\
A mucous layer protects large airways, as large (>8μm) particles impact into the mucous. \
    * Mucous is exocytosed by goblet cells in response to noxious stimuli including chemical irritation as well as inflammatory and neuronal stimulation
    * The efficacy of the mucous-cilia system is enhanced by bronchoconstriction, which reduces flow velocity and causes particulate matter to settle
* Cilia\
  Cilia are projections from epithelium which beat rhythmically at ~12Hz to propel mucous out of the airway at a rate of ~4mm.min^-1^.
    * Ciliary function can be impeded by pollutants, smoke, and infection
    * Ciliary function is stimulated by anaesthetic agents
* Inhaled particles which reach the respiratory zone are not trapped by mucous, but instead phagocytosed by alveolar macrophages
* Bronchoconstriction reduces flow velocity and causes particulate particles to settle in the mucous

## Drug Delivery

The same properties that optimise the lung for gas exchange optimise it for delivery of inhaled agents. Drugs absorbed in the pulmonary circulation are:

* Lipophilic
* Alkaline (pKa >8)

## Endocrine

Important endocrine functions of the lung include:

* Release of inflammatory mediators such as histamine, endothelin, and eicosanoids
* Release of nitric oxide to regulate smooth muscle
* ACE metabolises angiotensin I to angiotensin II

---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
2. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.

