---
level: 3
---

# Obesity

:::CICM
Discuss the effect of morbid obesity on ventilation
:::

Obesity is a multisystem disorder defined by an elevated body mass index (BMI):

* Normal: BMI < 25
* Overweight: BMI 25 - 30
* Obese: BMI > 30
* Morbidly Obese:\
    * Obesity related disease and a BMI > 35
    * BMI > 40

## Effects of Obesity on the Respiratory System

Morbid obesity causes several changes to the respiratory system:

* **Airway**
    * Increased risk of OSA
    * Increased risk of GORD and aspiration
    * Increased risk of difficult bag-mask ventilation
    * Increased risk of difficulty laryngoscopy
* Changes to r**espiratory pattern**
    * Increased minute ventilation
        *  Secondary to increased VO~2~ and VCO~2~\
        Due to the increase in LBW and adiposity. 
        * Increased airway reactivity\
        Central adiposity increases circulating cytokines, including TNF-α, IL-6, leptin.
* Changes to **volumes and capacities**
    * Reduced respiratory system compliance
        * Decreased chest wall compliance\
        Due to abdominal and chest wall fat.
            * Fat distribution may be more important than absolute BMI
        * Decreased lung compliance\
        Basal atelectasis due to abdominal compression and reduced respiratory compliance.
    * Decreased ERV and FRC\
        * Note that RV is generally relatively unchanged
    * Increased airway resistance\
    Due to decreased airway radius at lower lung volumes. 
    * Increased work of breathing\
    Due to reduced respiratory compliance and increased airway resistance.
    * Closing capacity encroaches on FRC\
    As FRC falls, closing capacity becomes closer to FRC.
        * If closing volume exceeds expiratory reserve volume, then small airways will collapse during normal tidal breathing, causing shunt
* Changes to **blood gases**
    * Increased A-a gradient\
    Occurs when closing capacity exceeds FRC. 
* Changes to **pulmonary circulation**\
    * PVR increases due to reduced FRC causing increased HPV\
    May lead to secondary PHTN and right heart dysfunction.

---

## References


1. Alvarez A, Brodsky J, Lemmens H, Morton J. Morbid Obesity: Peri-operative Management. Cambridge: Cambridge University Press. 2010.
2. Lotia S, Bellamy MC. [Anaesthesia and morbid obesity](https://academic.oup.com/bjaed/article/8/5/151/268305/Anaesthesia-and-morbid-obesity). Contin Educ Anaesth Crit Care Pain 2008; 8 (5): 151-156.