# Positive Pressure Ventilation

:::CICM
Describe the physiological consequences of intermittent positive pressure ventilation and positive end-expiratory pressure.
:::

Physiological effects of positive pressure ventilation are mostly related to the **increase** in  **mean airway pressure**. This increase is a function of:

* Ventilation mode
* Tidal volume and peak (and plateau) airway pressure
* Respiratory rate
* I:E ratio
* **PEEP**\
PEEP has a much larger effect than the other factors.
    * PEEP is defined as a positive airway pressure at the end of expiration
    * PEEP is distinct from positive airway pressure (which is not confined to a phase of the respiratory cycle) and CPAP (which is a mode of ventilation)
    * iPEEP refers to **intrinsic PEEP**, auto PEEP or dynamic hyperinflation\
    iPEEP is PEEP generated by the patient, and occurs when expiration stops before the lung volume reaches FRC.
        * Application of external PEEP may limit the generation of iPEEP by maintaining airway patency in late expiration


## Respiratory Effects

* **Decreased work of breathing**
    * Decreased VO~2~\
    More important when work of breathing is high.
* **Alteration in** anatomical/apparatus **dead space**\
    * Intubation typically reduces dead space, as the additional apparatus dead space is of smaller volume than the anatomical dead space it replaces
    * Non-invasive ventilation masks cause a large increase in dead space
* **Increased lung volume** (**and FRC**, for PEEP) by an amount proportional to the compliance of the system
    * Improves oxygenation via alveolar recruitment
    * Improves lung compliance via alveolar recruitment, reducing work of breathing
    * Elevated airway pressures may increase the proportion of West Zone 1 physiology and alveolar dead space\
    In healthy lungs an increase in the $V_D \over V_T$ratio is seen when PEEP exceeds 10-15cmH~2~O.
* **Reduced airway resistance**\
Airway resistance decreases as lung volume increases.

## Cardiovascular Effects

* **Alteration in cardiac output**
    * PEEP and IPPV generally decrease CO via decreasing VR due to the increase in intrathoracic pressure.  \
    Leads to reduction in RV filling pressure, LV filling, and CO.
        * This is the predominant reason why CO falls with the application of PEEP\
        In a well patient, CO falls by:
            * 10% with IPPV and ZEEP
            * 18% with IPPV and 9cmH~2~O of PEEP
            * 36% with IPPV and 16cmH~2~O of PEEP
        * These changes are:
            * More marked in hypovolaemia\
            Changes are reversed with volume expansion.
            * Less severe with poor lung compliance\
            Reduced compliance greatly reduces the effect of PEEP and IPPV on the vasculature, as the change in intrapleural pressure is reduced.
    * LV preload may also be reduced due to increased RV afterload\
        * Increased RV afterload may increase RV EDV, displacing the interventricular septum into the LV
        * The bulging septum decreases LVEDV, causing LV diastolic function and reduced LV filling\
        This is an example of **ventricular interdependence**.
    * Reduced LV afterload due to reduced LV transmural pressure\
    In some cases, IPPV augments circulatory function by reducing LV afterload to a greater extent than preload. 
        * Effects in a well patient are minimal, as PEEP is relatively small in magnitude compared to systemic arterial pressures
        * In patients generating highly negative intrathoracic pressures, the LV transmural pressure can increase markedly, increasing LV afterload and reducing cardiac output
* **Reduction** in **MAP**\
MAP decreases as PEEP increases.
* **Changes** to **oxygen flux**\
PEEP will tend to improve PO~2~ whilst reducing CO.
* **Changes** to **pulmonary vascular resistance** and **RV afterload**
    * If lung volume is lower than FRC, then PVR will reduce as PEEP stretches open extra-alveolar vessels
        * Alveolar recruitment will reduce hypoxic-pulmonary vasoconstriction, further reducing PVR
    * If lung volume is higher than FRC, then PVR will increase as PEEP compresses alveolar vessels
    * Therefore, PEEP has *variable effects* on RV afterload depending on how it changes lung volume with respect to FRC


## End-Organ Effects

* **Reduced urine output** due to:
    * Reduced CO and renal blood flow
    * ADH release as a consequence of reduced atrial stretch and ANP release\
    May worsen oedema in patients with prolonged periods of ventilation.
* **Reduced hepatic blood flow** due to:
    * Increased CVP and decreased CO lowering the pressure gradient for hepatic flow
        * May result in circulation only intermittently throughout the cardiac cycle

---

## References

1. Lumb A. Nunn's Applied Respiratory Physiology. 7th Edition. Elsevier. 2010.
2. Luecke T, Pelosi P. [Clinical review: Positive end-expiratory pressure and cardiac output](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1414045/). Critical Care. 2005;9(6):607-621. doi:10.1186/cc3877.
3. Yartsev, A. [Positive End-Expiratory Pressure and it's consequences](http://derangedphysiology.com/files/PEEP%20positive%20end%20expiratory%20pressure%20and%20its%20consequences.pdf). Deranged Physiology.
4. Yartsev, A. [Positive Pressure and PEEP](http://www.derangedphysiology.com/main/core-topics-intensive-care/mechanical-ventilation-0/Chapter%202.1.1/positive-pressure-and-positive-end-expiratory-pressure-peep). Deranged Physiology.
5. Yartsev, A. [Indications and Contraindications for PEEP](http://www.derangedphysiology.com/main/core-topics-intensive-care/mechanical-ventilation-0/Chapter%206.1.2/indications-and-contraindications-peep). Deranged Physiology.
6. Yartsev, A. [Effects of Positive Pressure and PEEP on Alveolar Volume](http://www.derangedphysiology.com/main/core-topics-intensive-care/mechanical-ventilation-0/Chapter%202.1.3/effects-positive-pressure-and-peep-alveolar-volume). Deranged Physiology.
7. Yartsev, A. [PEEP and Intrinsic PEEP}(http://www.derangedphysiology.com/main/core-topics-intensive-care/mechanical-ventilation-0/Chapter%202.1.6/peep-and-intrinsic-peep). Deranged Physiology.

