---
level: 3
---

# Time Constants

:::CICM
Explain the concepts of time constants
:::

:::ANZCA
Discuss 'fast' and 'slow' alveoli, including the concept of 'time constants'
:::

```{marginfigure}
**A Brief Refresher on Time Constants**:\
A time constant is **time** that a **process would take to complete *if*** its **initial rate of change** remained constant.\
\
It is useful when modeling a process using exponential functions, as the **rate of change** of an **exponent** is **proportional to its current value**.\
\
For a curve that **decreases over time**, the general case is:\
$$y = y_0e^{-kt}$$
Where:\
- $y_0$ is the value of $y$ at $t=0$\
- $-k$ is the rate constant\
- $t$ is time\
\
A positive rate constant ($k$) indicates that the curve **increases** over time. $k$ is the **reciprocal of the time constant**, $\tau$)
```

The time-constant is used in respiratory physiology in:

* Timing inspiration and expiration
* Elimination of inhalational anaesthetics
* The change in PaO~2~ and PaCO~2~ after changes in ventilation

In ventilation:

* The time constant is affected by:
    * Compliance
    * Resistance
    * Inflation pressure\
    At a **constant inflation pressure**, the **time constant is equal to the product of resistance and compliance**, i.e. $\tau = C \times R$.
* For two lung units of **equal compliance and resistance**
    * Inflation will occur as per the exponential growth function
    * Time-constants of each lung unit will be equal
    * No redistribution of gas will occur at end-inspiration as the pressure and volume of each unit is the same
* For two lung units, where **one has half the compliance but twice the resistance**
    * The time constants are equal, therefore both reach peak filling at the same time
        * However, the poorly compliant unit will only reach half the volume
    * No redistribution of gas will occur at end-inspiration as the pressure and volume of each unit is the same
* For two lung units, where one has **twice the resistance** of the other
    * The time-constants are unequal
    * The resistant unit will fill at half the rate of the other\
        * If inspiration is prolonged both will reach the same volume
        * If inspiration his halted early, and expiration prevented, there will be a pressure gradient between the units (as compliance is the same), and gas will redistribute from the low-resistant unit to the high-resistant unit
* For two lung units where one has **half the compliance**
    * The time constants are unequal
    * The poorly compliant unit will fill at half the rate of the other
        * If inspiration is prolonged they will both reach the same pressure\
        The volume in the poorly compliant unit will be half that of the more compliant unit.
    * During inspiration, the pressure rises more rapidly in the poorly compliant unit, and if inspiration is stopped and expiration prevented, this will result in redistribution into the more compliant unit until pressures are equal

In general:

* **Rate of filling is determined by time constants**
    * **High-resistance** lung units have **longer time constants** and take longer to fill
* **Final volume** (assuming an indefinite inspiration) **is a function of compliance**
    * Poorly compliant units with **empty and fill rapidly**\
    This creates the concept of **fast** and **slow alveoli**, depending on their time constants.


* At a sustained inflation pressure:
    * A low-resistance unit shows initial greater volume change but rapidly approaches equilibrium volume
    * A high-compliance unit takes a greater overall volume over a longer period
* At end-inspiration:
    * Pressure in units with a shorter time-constant rises more rapidly and if a breath is held will result in redistribution to those units with a longer time-constant.


## Clinical Significance

If time-constants are equal:

* The pressure in each unit is identical throughout inspiration and distribution\
Therefore, dynamic compliance will be independent of respiratory rate.

If time-constants are unequal:

* Long-time constant units may still be inhaling whilst the rest of the lung has stopped, or begun exhalation\
This is called **pendelluft**.
* In pendelluft, distribution of inspired gas is dependent on respiratory rate
    * As respiratory rate increases, the proportion of the tidal volume that is delivered to the region with a long time-constant decreases\
    Fast alveoli are preferentially inflated, causing V/Q scatter or shunt in the unventilated slow alveoli.   \
    * Dynamic compliance will decrease as respiratory rate rises and be markedly different from static compliance


---

## References

1. Lumb A. Nunn's Applied Respiratory Physiology. 7th Edition. Elsevier. 2010.
