# Bile

:::CICM
Describe the physiology of bile.
:::

**Bile** is a dark green solution produced by the liver to facilitate absorption of fat and fat-soluble vitamins through emulsification. Bile is:

* Produced by the liver at the rate of 1L per day
* Concentrated in the gallbladder
* Formed from:
  * Water
  * Protein
  * Bilirubin
  * Bile salts\
  The sodium and potassium salts of bile acids. Bile acids:
    * Are are produced from cholesterol
    * Are amphipathic, and act as emulsifiers of lipid\
    Break up large fat globules into smaller micelles, which can then be absorbed.
    * Major bile acids include:
      * Cholic acid
      * Chenodeoxycholic acid
    * Are absorbed in the terminal ileum, and recycled by the portal circulation
  * Lipids
  * Electrolytes

:::column-margin
Fat-soluble vitamins include Vitamin A, D, E, and K.
:::

---

## References

1. Hall, JE, and Guyton AC. Guyton and Hall Textbook of Medical Physiology. 11th Edition. Philadelphia, PA: Saunders Elsevier. 2011.
2. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
