# Control of Gastric Emptying

:::CICM
Describe the control of gastrointestinal motility, including (oesophageal) sphincter function.
:::

Gastric emptying is a neurally and hormonally mediated process which aims to present food to the small bowel in a controlled manner. Different drugs, hormones, and physiological states can either encourage or inhibit gastric emptying.

## Determinants of Gastric Emptying

**Rate of gastric emptying** is a function of:

* **Antral pressure**\
Primary determinant (pyloric resistance tends to be low), and is affected by:
    * Stomach
    * Duodenum
    * Systemic factors
    * Drugs
* **Pyloric resistance**

### Stomach Factors

* Gastric **distension**\
Vagal excitation from gastric stretch causes release of **gastrin**, increasing peristaltic frequency.
* Composition of chyme:
    * **Liquids** empty **faster** than **solids**
        * Liquids have a half-time of ~20 minutes, and empty in an exponential fashion
        * Solids have a half-time of ~2 hours, with a dwell time of ~30 minutes, and empty in a linear fashion
    * Protein independently stimulates gastrin release


### Duodenal Factors

The duodenum has hormonal mechanisms which have a **negative feedback** on gastric emptying. These include:

* **Duodenal distension**
* **Hypoosmolar and hyperosmolar** chyme
* **Acid**ic chyme\
  In response to acid the duodenum releases **secretin** and **somatostatin**:\
  * Secretin directly inhibits gastric smooth muscle
  * Somatostatin inhibits gastrin release
* **Fat** and **protein**\
  Fat and protein breakdown products stimulate release of **cholecystokinin**, which **inhibits gastrin**.

:::column-margin
Carbohydrate-rich meals empty faster than protein, which empty faster than fat.
:::


### Systemic Factors

* **Motilin**\
Released by the small bowel and enhances the strength of the **migrating motor complex**, a peristaltic wave of contraction through the whole GIT which occurs every 60-90 minutes.
* **Sympathetic** input
Occurs via the coeliac plexus, and **inhibits** gastric emptying.
* **Parasympathetic** input\
Enhances gastric motility.
* **Pregnancy**\
Has a number of effects on gastric emptying:
    * Progesterone relaxes smooth muscle and inhibits gastric smooth muscle response to ACh and gastrin, as well as creating incompetence of the LoS leading to GORD
    * Gastrin production increases\
    Some gastrin is produced by the placenta.
    * Gastric acid production is increased during the the third trimester


### Drug Factors

Drugs which ↑ gastric emptying include:

* Metoclopramide
* Erythromycin

Drugs which ↓ gastric emptying include:

* Opioids
* Alcohol
* Anticholinergic agents

---

## References

1. CICM July/September 2007
2. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.