# Gastric Secretions

> Describe the composition, volumes and regulation of gastrointestinal secretions

The GIT produces a number of substances which can be classified by region and function:

* Saliva
    * H~2~O (98%)
    * Digestive proteins
        * Amylase
        * Lipase
        * Mucin
        * Haptocorrin\
        Binds Vitamin B12.
    * Immunological proteins
        * Lysozyme
        * Lactoferrin
        * IgA


* Gastric
    * Digestive
        * HCl
        * Gastrin
        * Pepsin
        * Intrinsic Factor
    * Mucosal Protection
        * Mucous
        * HCO~3~^-^


* Small Bowel
    * Digestive
        * Pancreatic
            * Lipase
            * Amylase
            * Trypsinogen
        * Endocrine
            * Secretin
            * Somatostatin

## Control of Secretions

Secretion occurs in three phases:

* Cephalic\
  Thought/sight/taste/smell of food, resulting in vagal-mediated stimulus to release gastrin. Accounts for ~30% of production.
* Gastric\
  Stretch of the stomach stimulates HCl secretion and gastrin release. Accounts for ~50% of production.
* Intestinal\
  A drop in pH of the proximal duodenum releases **secretin** to stimulate the exocrine pancreas.

## Salivary Secretions

Approximately **1L** of saliva is produced by the parotid, submandibular, and sublingual glands each day.

Saliva has four main functions:

* **Lubrication**\
    * Mucin
* **Digestion**\
    * Amylase
    * Lipase\
    Particularly important in neonates who produce little pancreatic lipase.
* **Neutralisation of acid**\
For protection prior to vomiting.
* **Antibacterial**

## Gastric Secretions

The stomach produces **~2L** of secretions **per day**:

* **Acid secretion**\
**Parietal cells** contain an H^+^-K^+^ exchange pump.
    * H^+^ is produced by carbonic anhydrase on CO~2~ and water, with 'waste' HCO~3~^-^ removed from the cell in exchange for Cl^-^.
        * High levels of acid production result in large amounts of bicarbonate being secreted into blood
            * This creates an **alkaline tide** as portal venous pH increases dramatically
            * Respiratory quotient of the stomach may become negative due to **consumption of CO~2~**
    * This pump is activated in response to increased levels of intracellular Ca^2+^ from stimulation by:
        * **ACh**
        * **Histamine** (H~2~)
        * **Gastrin**
    * Inhibited by:
        * Low gastric pH
        * Somatostatin


* **Gastrin**\
Gastrin is a peptide family secreted from antral **G cells**.
    * Secretion is stimulated by:
        * Neural (vagal) stimulation in the cephalic phase of digestion\
        Main mechanism.
        * Protein and amino acids in the stomach
        * Drugs\
            * Alcohol
            * Caffeine
    * Secretion is inhibited by:
        * Low pH
        * Secretin
        * Glucagon
    * Gastrin has a number of pro-digestive effects:
        * Stimulates gastric acid secretion
        * Stimulates pancreatic secretion
        * Stimulates biliary secretion
        * Increases gastric and intestinal motility


* **Pepsinogens**\
**Chief cells** secrete pepsinogen which is released by ACh or β stimulation. 
Pepsinogen is cleaved by hydrochloric acid in the stomach to become pepsin. Pepsin breaks down protein.


* **Intrinsic Factor**\
**Parietal cells** produce intrinsic factor, which forms a complex with B~12~ which facilitates its later absorption in the terminal ileum.


* **Mucous**\
**Neck cells** produce mucopolysaccharide, glycoprotein, and HCO~3~^-^ in response to stimulus by prostaglandins, which protects mucosa and lubricates food.


* **Pancreatic Secretions**\
Exocrine pancreatic secretions are produced by the **acinar** and **ductal cells**, at the rate of **1.5L per day**.
    * Release is stimulated by:
        * CCK
        * Secretin
        * ACh\
        Via vagal stimulation.
    * Consist of:
        * HCO~3~^-^\
         To alkalinise gastric contents.
             * Pancreatic bicarbonate production lowers venous pH, and neutralises the alkaline tide of the stomach.
        * Water
        * Enzymes
            * Trypsinogen: activated to **trypsin** by duodenal enteropeptidases. \
              Proteolysis.
            * Amylase\
              Hydrolysis of glycogen, starch, and complex carbohydrate.
            * Lipase\
              Hydrolysis of dietary triglycerides.


## Endocrine Function

* Cholecystokinin (**CCK**) is a peptide family secreted by intestinal enteroendocrine cells (I cells) in the mucosa of the duodenum and jejunum. Cholecystokinin:
    * Regulates satiety
    * Regulates leptin release from fat
    * Stimulates secretions from the gallbladder and duodenum 
* Secretin stimulates pancreatic release. Secretin is:
    * Released by the proximal duodenum in response to low pH
* Motilin stimulates the migrating motor complex. Motilin is:
    * Released **cyclically** from M cells in the small bowel


---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
