# Liver Function Assessment

:::CICM
Describe the laboratory assessment of liver function.
:::

:::ANZCA
Describe the laboratory assessment of liver function and hepatic failure.
:::

## Synthetic Function

Measures of synthetic function include:

*  **Albumin**\
Main plasma protein.
    * Normal range 28-58g.L^-1^
    * Half-life ~20 days
    * Important in:
        * Maintenance of plasma oncotic pressure
        * Binding
            * Calcium
            * Drugs
    * ↓ In liver dysfunction and malnutrition

* **Coagulation Assays**\
Clotting factors are produced by the liver. Hepatic impairment may result in reduced production and abnormality of clotting assays, although functional clotting function may be normal (as pro-coagulant proteins are affected to a similar extent).
    * INR\
    Test of the extrinsic pathway.
    * APTT\
    Test of intrinsic pathway.


## Metabolic Function

Transaminases are released when liver parenchyma is damaged, and are used to evaluate metabolic function:

* ALT\
Normal range < 54 U.L^-1^.
* AST\
Normal range < 35 U.L^-1^.

## Obstructive Tests

* ALP (Alkaline Phosphatase)\
Enzyme involved in dephosphorylation of many compounds. ALP is found in all cells, but particularly in the liver, bile duct, bone, kidney, and placenta.
    * Normal range is 30-120 U.L^-1^
    * May be ↑ in isolation in bone disease
* GGT\
Enzyme found in biliary duct.
    * Normal range:
        * Males: 11-50 U.L^-1^
        * Females: 7-30 U.L^-1^
* Bilirubin\
Byproduct of haemoglobin metabolism. May be measured as total, or as conjugated and unconjugated bilirubin.

---

## References

1. Diaz, A. [Outline the clinical laboratory assessment of liver function](https://primarysaqs.files.wordpress.com/2009/12/2010b16outline-the-clinical-laboratory-assessment-of-liver-function.pdf). Primary SAQs.
