# Functions of the Liver

:::CICM
Describe the functions of the liver.
:::

:::ANZCA
Outline the functions of the liver.
:::

Key liver functions include:

* Storage
* Synthesis
* Metabolic
* Immune
* Acid-base


## Storage

The liver is important in storage and release of:

* Carbohydrates as glycogen\
The adult liver stores ~100g of glycogen.
* Fat as triglycerides
* All fat-soluble vitamins (A, D, E, K)
* Many water soluble vitamins including folic acid and B~12~
* Iron
* Copper

## Synthetic

The liver is critical for synthesis of:

* **Bile**
* Plasma proteins:
    * Clotting factors
    * Albumin production\
    120-300mg.kg^-1^ of albumin is produced per day, dependent on nutritional status, plasma oncotic pressure, and endocrine function. 

## Metabolic

Metabolic functions include:

* Carbohydrate
* Fat
* Protein
* Bilirubin metabolism
* Drugs and Toxins


### Carbohydrate Metabolism

The liver is critical for the production and storage of glucose: 

* Monosaccharides and disaccharides passively diffuse into hepatocytes\
Gradient is maintained by converting glucose to glucose-6-phosphate which is used to produce glycogen. This maintains the gradient for diffusion.
* Glycogen is either synthesised (glycogenesis) or broken down (glycogenolysis) depending on plasma glucose and insulin:
    * Increased blood glucose stimulates insulin release, increasing the formation of glycogen through activation of glycogen synthetase
    * Decreased blood glucose stimulates glycogenolysis and gluconeogenesis from amino acids.


### Lipid Metabolism

The liver is involved in both the production and consumption of fat, including:

* Storage of triglycerides
* Hydrolysis of fat to glycerol and fatty acids, which is used for ATP production


### Protein Metabolism

Amino acids are absorbed from blood to be used for gluconeogenesis and for protein synthesis. In order to produce substrates for the CAC, Amino acids may be:

* Transaminated
* Deaminated
* Decarboxylated

The nitrogenous scrap of these reactions is urea, which is produced in several stages:

* A variety of metabolic processes convert amino acids to **glutamate**
* Glutamate is converted to **ammonia** by glutamate dehydrogenase
* Ammonia then enters the urea cycle to produce (surprisingly) urea, at the cost of **3 ATP**
  * A normal diet of 100g protein per day produces ~30g of urea, and 1000mmol of hydrogen ions


## Endocrine

The liver:

* Produces angiotensinogen
* Produces IGF-1
* Converts T4 to T3


## Immune Function

The liver contains **Kupffer** cells, which are the tissue macrophages of the hepatic reticuloendothelial system. Kupffer cells phagocytose harmful substances including:

* Endotoxins
* Bacteria
* Viruses
* Immune complexes
* Thrombin
* Fibrin complexes
* Tumour cells

## Acid-Base Balance

The liver may produce or consume large numbers of hydrogen ions:

* Carbon dioxide production
* Metabolism of organic acid anions
  * Lactate
  * Ketones
  * Amino acids
* Ammonium
* Production of plasma proteins\
Notably albumin


---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
2. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
3. Brandis K. [The Physiology Viva: Questions & Answers](http://www.anaesthesiamcq.com/vivabook.php). 2003.
