# Swallowing

:::CICM
Describe the control of gastrointestinal motility, including (oesophageal) sphincter function.
:::

:::ANZCA
Explain the physiology of swallowing.
:::

**Swallowing** is divided into **three phases**:

* **Oral Phase**\
    * Voluntary
    * Food is pushed against hard palate by tongue
* **Pharyngeal Phase**\
    * Involuntary\
    Coordinated by medulla.
    * Closure of nasopharynx
    * Adduction of vocal cords
    * Hyoid elevation and deflection of epiglottis
    * Pharyngeal contraction\
    Propels food bolus towards oesophagus
* **Oesophageal phase**\
    * Involuntary
    * Closure of UoS\
    Resting **barrier pressure 100mmHg**.
    * Relaxation of LoS\
    Resting **barrier pressure 20mmHg**, which is a balance between:
        * LoS pressure (30mmHg)
        * Antral pressure (10mmHg)
    * Oesophageal peristalsis


:::column-margin
Impairment of any of these processes ↑ risk of aspiration. These include:

* Obtundation\
Reduced cough reflex.
* Muscular weakness
* Impaired medullary coordination
:::

---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.