# Hypersensitivity

:::CICM
Explain the immunological basis and pathophysiological effects of hypersensitivity, including anaphylaxis.
:::

:::ANZCA
Describe the immunology and pathophysiology of hypersensitivity reactions
\
\
Describe the immunology and pathophysiology of anaphylaxis
:::

Hypersensitivity reactions are:

* **Exaggerated immune responses** that cause host injury.
* Classified by mechanism using the **Gel and Coombs system**\
Common used but fails to classify more complex disease states.

| Type                                     | Timing             | Mediator      | Pathophysiology                                                                                                                            | Disease example(s)                                     |
|------------------------------------------|--------------------|---------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------|
| **Type I** - Immediate hypersensitivity  | Seconds to minutes | IgE           | Basophil and mast cell degranulation                                                                                                       | Anaphylaxis (systemic), Atopy (local)                  |
| **Type II** - Cellular hypersensitivity  | 5-8 hours          | IgM, IgG      | Antibody binding to cell surface antigen, resulting in cell death via complement membrane attack complexes, or phagocytosis by macrophages | Transfusion reactions, hyperacute allograft rejection  |
| **Type III** - Immune-complex deposition | 2-8 hours          | IgM, IgG, IgA | Tissue deposition of Ab-Ag complexes. Accumulation of PMNs, macrophages, and complement.                                                   | SLE, necrotising vasculitis, post-Strep GN             |
| **Type IV** - Delayed hypersensitivity   | 24-72 hours        | T-cell        | T-cell induced mononuclear cell accumulation. Release of monokines and lymphokines.                                                        | TB, Wegener's Granulomatosis, Granulomatous vasculitis |

## Type I Hypersensitivity

Mechanism of Type I hypersensitivity reactions:

* Antigen simulates a B lymphocyte to produce a specific IgE against it
* This IgE then binds to Fc receptors on mast cells, sensitising them to this exposure
* On re-exposure the antigen binds (**cross-links**) IgE on mast cells, causing degranulation:
    * Histamine, leukotrienes, and prostaglandins are released
    * This may cause local or systemic effects, depending on method of exposure:
        * A systemic reaction is called **anaphylaxis**, and manifests as a combination of:
            * Hypotension
            * Bronchospasm
            * Laryngeal oedema
            * Rashes
        * Local reactions depend on the route of exposure, and include
            * Asthma\
            Inhaled. 
            * Allergic rhinitis\
            Nasopharyngeal mucosa.

:::column-margin
**Non-immune anaphylaxis** (also known as anaphylactoid) reactions are characterised by a immediate generalised reaction clinically indistinguishable from true anaphylaxis, but the immune nature is unknown, or not due to a type I hypersensitivity reaction.
:::

## Type II Hypersensitivity

Mechanism of Type II hypersensitivity reactions:

* Antibodies bind to cell surface antigen
* Antibody-Antigen complex **activates complement**
* Complement generates an inflammatory response
* Cell death occurs via:
    * Complement membrane attack complex
    * Phagocytosis

:::column-margin
The clinical picture of type II hypersensitivity reactions depends on affected organs. Examples include:

* Hyperacute allograft rejection
* Transfusion reactions and haemolytic disease of the newborn
* Goodpasture's syndrome
* Autoimmune cytopaenias
* Myasthenia Gravis
:::

## Type III Hypersensitivity

Mechanism of Type III hypersensitivity reactions:

* Immune-complex reaction where Ab-Ag complexes are formed and deposited in tissues
* Subsequent complement activation causes inflammation and neutrophils activation, leading to tissue damage
* There are two subtypes of type III reactions:
    * Formation of complexes in circulation and subsequent deposition in tissues
            * e.g. Serum sickness
    * Formation of complexes in tissues\
    Small amounts are typically removed by the reticuloendothelial system, but in this case there are too many, or they are too small, to be cleared effectively.

:::column-margin
Examples of type III hypersensitivity reactions include:

* The Arthus reaction\
Form of localised vasculitis.
:::

## Type IV Hypersensitivity

Mechanism of Type IB hypersensitivity reactions:

* Antigen is presented to T lymphocytes which proliferate and become sensitised
* T-cells then release cytokines, attracting macrophages and leading to local inflammation
* During prolonged exposure, macrophages may fuse to form giant cells and form a granuloma.

:::column-margin
Examples of type IV hypersensitivity reactions include:

* TB
* Granulomatous vasculitis
:::

---

## References

1. CICM July/September 2007
2. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
