# Clinical Trial Design

::: dual
Describe the stages in design of a clinical trial
:::

1. Determine research question
	* Literature review
		* Current evidence on topic
		* Unanswered questions
	* Define the question
		* Aim
		* Significance\
		Is the outcome of interest, and is the result implementable?
		* Endpoint\
			* Hard endpoints
			* Patient-centered
			* Surrogate
			* Composite
2. Determine target population\
Inclusion and exclusion criteria, and justifications for each.
4. Study methodology
	* Protocol\
	Should be strict and highly prescriptive to minimise number of protocol violations.
	* Statistical analysis
		* Randomisation
			* Need for control group
			* Treatment allocation and concealment
		* Missing data analysis plan
		* Sensitivity analysis
		* Adverse event reporting method
		* Sample size estimation\
		Should be powered adequately for desired outcome.
		* Identify sources of:
			* Confounding
			* Bias
		* Pre-specify analysis plan
	* Data collection and storage\
		* Issue with multi-centre, international trials
		* National Privacy Principles compliance
 	* Funding
 	* Ethics committee review and approval
5. Register study in an online database
6. Perform pilot study
7. Refine methodology based on pilot study\
Determine if doing the definitive study is feasible. Potential issues:
	* Patient recruitment
	* Event rate as predicted
	* Group separation
	* Feasibility of methodology
8. Perform definitive study
9. Publish\
CONSORT methodology or similar.

---

## References

1. PS Myles, T Gin. Statistical methods for anaesthesia and intensive care. 1st ed. Oxford: Butterworth-Heinemann, 2001.