# Evidence-Based Medicine

::: dual
Describe the features of evidence-based medicine, including levels of evidence (e.g. NHMRC), ~~meta-analysis, and systematic review~~
:::

## What is Evidence-Based Medicine?

Evidence-based Medicine (EBM):

* Is **"the conscientious, explicit, and judicious use and appraisal of current best evidence in making decisions about the care of individual patients."**
* Aims to provide a framework for acquiring knowledge and making optimal decisions around medical care
* Includes "*integrating* **individual clinical expertise with the best available external clinical evidence** from systematic research."
* Has **five stages**:
	1. Ask an answerable question
	2. Search
	3. Critically appraise the evidence
	4. **Integrate the evidence with the patients unique circumstances** and values
	5. Evaluate the result

## Levels of Evidence

Grade studies on likelihood of bias and internal validity.

::: column-margin
Other organisations and institutions have different grading systems, most are broadly similar.
:::

The NHMRC defines 6 levels of evidence, graded from I-IV:

* Level I is evidence from a **systematic review** of RCTs
* Level II is evidence from **at least one good RCT**
* Level III-1 is evidence from a **pseudo-RCT**
* Level III-2 is evidence from a **comparative study *with* concurrent controls**, such as a cohort or case-control study
* Level III-3 is evidence from a **comparative study *without* concurrent controls**, such as a cohort study with historical controls
* Level IV is evidence from a case-series

::: column-margin
Note that expert opinion is **not** part of NHMRC levels of evidence, though it is included on the Oxford Centre for Evidence Based Medicine system, used by the NHS.
:::


| Level |                           Intervention                           |                                                                            Diagnostic Accuracy                                                                            |                                            Prognostic                                           |                Aetiology                |                    Screening                    |
|-------+------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------+-----------------------------------------+-------------------------------------------------|
| I     | A systematic review of level II studies                          | A systematic review of level II studies                                                                                                                                   | A systematic review of level II studies                                                         | A systematic review of level II studies | A systematic review of level II studies         |
| II    | A randomised controlled trial                                    | A study of test accuracy with: an independent, blinded comparison with a valid reference standard, among **consecutive persons** with a defined clinical presentation     | A prospective cohort study                                                                      | A prospective cohort study              | A randomised controlled trial                   |
| III-1 | A pseudorandomised controlled trial                              | A study of test accuracy with: an independent, blinded comparison with a valid reference standard, among **non-consecutive** persons with a defined clinical presentation | All or none                                                                                     | All or none                             | A pseudorandomised controlled trial             |
| III-2 | A comparative study with concurrent controls                     | A comparison with reference standard that does not meet the criteria required for Level II and III-1 evidence                                                             | Analysis of prognostic factors amongst persons in a single arm of a randomised controlled trial | A retrospective cohort study            | A comparative study with concurrent controls    |
| III-3 | A comparative study without concurrent controls                  | Diagnostic case-control study                                                                                                                                             | A retrospective cohort study                                                                    | A case-control study                    | A comparative study without concurrent controls |
| IV    | Case series with either post-test or pre-test/post-test outcomes | Study of diagnostic yield (no reference standard)                                                                                                                         | Case series, or cohort study of persons at different stages of disease                          | A cross-sectional study or case series  | Case series                                     |

## Grades of Evidence

Evidence is graded to "indicate the strength of the body of evidence underpinning a recommendation" (e.g. in a clinical guideline). The NHMRC grades recommendations from A to D as follows:

* **A**: Body of evidence can be trusted to guide practice
* **B**: Body of evidence can be trusted to guide practice, in most situations
* **C**: Body of evidence provides some support, but care should be taken in its application
* **D**: Body of evidence is weak and recommendation must be applied with caution

---