# Aminoglycosides


Bactericidal antimicrobials that prevent protein synthesis by irreversible binding to the 30S ribosomal subunit, preventing mRNA transcription.

* As they are large, polar molecules, they must be actively transported into the cell
    * This occurs with an oxygen dependent transporter\
    Therefore they are **not effective against anaerobes**.
* Transport is inhibited by increased Ca^2+^, Mg^2+^, low pH, and low O~2~
* Aminoglycoside killing is dependent on the peak concentration over MIC\
Typically peak concentration must be 8-10x MIC.
    * Exposure to aminoglycosides causes bacteria to down-regulate aminoglycoside uptake, and therefore increases MIC\
    This effect disappears after ~24 hours, and is one justification for daily dosing of aminoglycosides. Additional justifications include:
        * Allows larger single doses to be used, increasing bactericidal effect
        * Aminoglycosides exhibit a post-antibiotic effect\
        Ongoing bactericidal activity even after concentration falls.


```{r}
source("scripts/drugtables.R")

DrugTable("gentamicin", caption = "Gentamicin")
```

***

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014. 
2. Stubbings W, Bostock J, Ingham E, Chopra I [Mechanisms of the post-antibiotic 
effects induced by rifampicin and gentamicin in Escherichia coli](https://www.ncbi.nlm.nih.gov/pubmed/16735423). J Antimicrob
Chemother. 2006 Aug;58(2):444-8.
3. Deranged Physiology - [Kill Characteristics of Antibiotic Agents](http://www.derangedphysiology.com/main/required-reading/infectious-diseases-antibiotics-and-sepsis/Chapter%202.1.4/kill-characteristics-antibiotic-agents)
