# Antifungals


Antimicrobial agents targeting eukaryotic and heterotrophic microbes. Can be divided by class into:

* Azoles\
Inhibit ergosterol synthesis.
Subdivided into:
	* Triazoles
		* Fluconazole
		* Itraconazole
		* Voriconazole
		* Posaconazole
	* Imidazoles
		* Ketoconazole
* Echinocandins\
Inhibit glucan synthesis.
	* Caspofungin
	* Micafungin
	* Anidulafungin
* Polyenes\
Disrupt cell membrane.
	* Amphotericin B
	* Nystatin

## Mechanisms of Antifungal Resistance

Three broad mechanisms:

* Increased efflux\
Increased expression of transport proteins removing drug from cell.
* Alteration of target enzyme\
Changes to protein target prevent drug binding or inactivation.
	* Typically only requires changes in a few amino acids
* Alteration of drug metabolism\
Reduced enzyme activity prevents accumulation of toxic product.


Amphotericin resistance is rare *in vivo*, and is typically via different mechanisms:

* Decreased ergosterol content
* Altered sterol:phospholipid ratio

## Comparison of Antifungals


```{r}
source("scripts/drugtables.R")

DrugTable("fluconazole", "voriconazole", "caspofungin", "amphotericin_b")
```


***

## References

1. Anderson JB. [Evolution of antifungal-drug resistance: mechanisms and pathogen 
fitness](https://www.nature.com/articles/nrmicro1179). Nat Rev Microbiol. 2005 Jul;3(7):547-56.
2. Drew RH. Pharmacology of Amphotericin B. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2018.
3. Ashley ED, Perfect JR. Pharmacology of azoles. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2018.
4. Lewis RE. Pharmacology of echinocandins. In: UpToDate, Post, TW (Ed), UpToDate, Waltham, MA, 2018.
5. Bekersky I, Fielding RM, Dressler DE, Lee JW, Buell DN, Walsh TJ. [Pharmacokinetics, excretion, and mass balance of liposomal amphotericin B (AmBisome) and amphotericin B deoxycholate in humans](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC127462/). Antimicrob Agents Chemother. 2002 Mar;46(3):828-33.
