# Glycopeptides


Non-β-lactam agents that inhibit cell wall synthesis. They are:

* Active against gram-positive anaerobes and aerobes
* Bacteriostatic against enterococci and streptococci
* Bacteriocidal against staphylococci


|Property|Vancomycin|
|--|--|
|**Uses**|MRSA, C. difficile
|**Presentation**|Powder for reconstitution
|**Route of Administration**|PO, IV, Intrathecal| 
|**Dosing**|Peak levels determined by dose, trough levels by dose and interval
|**Absorption**|No oral bioavailability. Poor CSF penetration|
|**Distribution**|V~D~ 0.4-1 L.kg^-1^. Poor CSF penetration even with inflamed meninges - higher levels are required for CNS penetration. ~50% protein bound.
|**Metabolism**|Minimal hepatic metabolism|
|**Elimination**|90% secreted unchanged in urine - significantly prolonged in renal impairment|
|**CVS**|Phlebitis, red man syndrome (profound non-anaphylactic histamine release with rapid injection)
|**CNS**|Ototoxicity
|**Renal**|Nephrotoxicity, typically temporary and resolves on cessation
|**Haematological**|Thrombocytopenia
|**Immunological**|'Red man syndrome' due to histamine release with rapid injection, with accompanying ↑ HR ↓ BP. Neutropenia.
|**Other**|Synergistic action with cephalosporins, aminoglycosides, and rifampicin

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. [Wellington ICU Drug Manual](http://drug.wellingtonicu.com/)
3. Rybak MJ. [The pharmacokinetic and pharmacodynamic properties of vancomycin](https://academic.oup.com/cid/article/42/Supplement_1/S35/275535). Clin Infect Dis. 2006 Jan 1;42 Suppl 1:S35-9.