# Respiratory Changes of Pregnancy

:::CICM
Explain the physiological changes during pregnancy and parturition.
:::

:::ANZCA
Describe the physiological changes and their implications for anaesthesia that occur during pregnancy, labour and delivery, in particular the respiratory~~, cardiovascular, haematological and gastrointestinal~~ changes.
:::

Respiratory changes in pregnancy are a function of:

* Anatomical compression of the chest
* ↑ VO~2~ and VCO~2~

## Anatomical Changes

Key anatomical changes include:

* Superior displacement of the diaphragm by ~**4cm**
* ↑ AP and transverse diameter of the chest wall (~2-3cm)
* Large airway dilation, ↓ airway resistance by ~35%


### Volumes and Capacities

From conception until term:

* V~T~ increases by 40%
* Inspiratory capacity increases by 10%
* Expiratory capacity decreases by 30%
* Total lung capacity decreases by 5%
* Vital capacity is unchanged
 
From ~20 weeks until term:

* ERV decreases
* RV decreases
* FRC decreases
    * By 20% erect
    * By 30% supine

## Ventilation

**Progesterone** stimulates respiratory centres, shifting the O~2~ and CO~2~ response curves to the left which causes hyperventilation and a **respiratory alkalosis**. From conception until term:

* MV ↑ by 50%
    * 10% ↑ in RR
    * 40% ↑ in V~T~
* PCO~2~ ↓ to ~26-32mmHg, with a compensatory drop in plasma [HCO~3~^-^] to 18-21mmol.L^-1^


## Labour and Postpartum

During labour:

* MV ↑ 70% due to pain and ↑ O~2~ demand
* This causes hypocapnea, so cessation of uterine contractions (and the associated pain and oxygen demand) are followed by a hypoventilatory period producing desaturation

FRC and RV return to normal within 48 hours of delivery.


---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
