# 2016B Question 04 


Outline the physiology of blood groupings that allows O negative packed red cells to be safely transfused to most patients.


## Examiner Report

75% of candidates achieved a pass in this question.


Main points expected for a pass:
- Neg status is determined by the ABO and Rhesus blood groups
- A classification of ABO system according to antigens expressed on the RBCs
- Recognition that antibodies (Abs) develop in the plasma against non-self ABO antigens (and to delineate these)
- Classification of the Rhesus system based on the presence or absence of the Rhesus antigen
- Recognition that ABO incompatibility results when donor RBCs expressing an antigen (A &/or B) which recipient does not possess are transfused. The recipient will have antibodies to the foreign antigen in their plasma, resulting in an immune reaction.
- Recognition that O Neg blood cells express no A or B antigens and no Rhesus antigen and hence will not provoke an immune response when transfused to most.


Additional credit was gained for discussion of:
- The ABO system as the most antigenic
- How the ABO Abs are formed after birth and their nature
- The Rhesus system having multiple alleles, but the D allele as the most important
- The need for prior exposure to the D antigen to produce anti-D antibodies (unlike ABO Abs) and the importance of avoiding this sensitization esp in women of childbearing age (hence the use of Rh – blood)
- Rare blood groups eg the Bombay blood group where O neg blood may cause an immune reaction
- Other more minor blood antigens which may cause reaction in sensitized patients
- The importance of removing plasma from the donated RBCs (as O plasma contains both anti-A and anti-B antibodies)
- The utility of O Neg blood in emergency situations with critical time pressures


The most common error was the description of antibodies against the ABO antigens as “A Abs & B Abs” when they are actually anti-A Abs and Anti-B Abs.

## Model Answer

Structure:
- Introduction
- ABO system: Ag, Ab
- Rhesus system: Ag, Ab
- O-ve

### Introduction

- RBC membranes express antigens (Ag)
- Antibodies (Ab) are produced against non-self RBC Ag following exposure
- Transfusion safe only if recipient won’t produce Ab against donor Ag

### ABO System


|Factor|Properties|
| -- | -- |
|Antigens|<p>- Carbohydrate Ag</p><p>- Also present in diet</p><p>- Common oligosaccharide foundation = “O antigen”</p><p>- Type A adds N-acetylgalactosamine</p><p>- Type B adds galactose</p><p>- Type AB adds both</p>|
|Antibodies|<p>- Non-self anti-A, Anti-B developed in first year of life if type O blood (diet exposure)</p><p>- (Anti-O = Bombay is rare)</p><p>- More pentameric IgM</p><p>- More antigenic</p><p>- Doesn’t cross placenta</p><p>- Incompatibility → Intravascular haemolysis (worse)</p><p>- Note no plasma in donor packed RBCs, hence donor’s antibodies unimportant</p>|

### Rhesus System


|Factor|Properties|
| -- | -- |
|Antigen|<p>- Protein Ag</p><p>- Many types (A, a, B, b etc); D most important</p><p>- Non-self Anti-RhD only developed after exposure to RhD+ blood (no diet exposure)</p>|
|Antibodies|<p>- More monomeric IgG</p><p>- Less antigenic</p><p>- Incompatibility → Extravascular haemolysis (not quite as bad)</p><p>- Does cross placenta (hydrops foetalis)</p><p>- Important to avoid sensitization in females of childbearing potential:</p><p>- First time: Rh- mother, Rh+ neonate → Sensitization</p><p>- Second time: Rh+ neonate, maternal Anti-RhD IgG causes hydrops foetalis, haemolytic Dx of newborn</p>|

### O Negative Red Cells


|Factor|Properties|
| -- | -- |
|Properties|<p>- RBCs: “O Ag” but no A, B or RhD Ag</p><p>- Plasma has anti-A, anti-B, +/- anti-RhD but these are washed from RBC unit</p>|
|Universality|<p>- Safe for A,B,O whether D+ or D-</p><p>- Useful in emergency when no time for crossmatch</p>|
|Exceptions|<p>- Bombay group: Anti-O antibody</p><p>- Other groups: Kell, Kidd, Duffy</p><p>- Importance variable</p><p>- May cause reaction if sensitised</p>|


--- 

