# 2016B Question 10 

Describe the effects of giving an unopposed dose of neostigmine.


## Examiner Report

28.5% of candidates achieved a pass in this question.


This was a question of two parts.


The majority of candidates answered this question as a ‘side-effects of neostigmine’ question, but did not include any information about the effects of neostigmine at the nicotinic receptors. It was possible to pass the question with only information about the muscarinic receptor effects, but it required a high level of detail to do this.


Outside of bradycardia, the cardiac effects were generally poorly-covered. Non-specific comments such as “urination” did not attract marks, whereas a point such as “increases ureteric peristalsis may 
lead to urination” did.


Good candidates were able to explain how neostigmine works, why neostigmine is given, when it is appropriate to give neostigmine, discuss the effects at both the nicotinic and muscarinic receptors and apply clinical relevance to both. Extra marks were awarded for applying clinical relevance to the question, particularly if candidates explained why an antimuscarinic medication is usually co-administered when neostigmine is used to reverse non-depolarising muscle blockade.

## Model Answer

Structure:
- Summary: PC, PK, PD
- Nicotinic
- Muscarinic

### Summary


|Pharmacological Property|Effect|
| -- | -- |
|Physicochemical|- Quaternary ammonium charged drug, doesn’t cross BBB|
|Pharmacokinetic|<p>- 0.05mg.kg^-1^ IV, ceiling 0.07mg.kg^-1^</p><p>- Onset 3 mins, peak 10 mins, duration 30-60 mins</p><p>- 50% metabolized (PChE, CYPs)</p><p>- 50% excreted unchanged in urine</p><p>- t1/2β 75 mins</p>|
|Pharmacodynamic|<p>- Mechanism:</p><p>&emsp;- Forms reversible carbamylate complex with esteratic site of AChE</p><p>&emsp;- ↑ [ACh] at cholinergic synapses</p><p>&emsp;- Muscarinic effects at low dose, nicotinic at high dose</p><p>&emsp;- (Also inhibits PChE → Augment suxamethonium and mivacurium)</p><br><p>- Use:</p><p>&emsp;- Reverse non-depolarising relaxant e.g. Atracurium</p><p>&emsp;- Myasthaenia gravis</p><p>&emsp;- Bladder atonia</p><p>&emsp;- Pseudo-obstruction</p><p>&emsp;- Glaucoma</p>|

### Nicotinic Effects


|Effect|Mechanism|
| -- | -- |
|Muscle type|<p>- ↑ [ACh] → ↑ Na^+^ influx > K^+^ efflux = Ca^2+^ influx → End-plate potential ± action potential → Contraction</p><p>- Displace and reverse non-depolarising relaxant</p><p>&emsp;- Starting TOF count 3-4: Adequate reversal</p><p>&emsp;- Starting TOF count 1-2: Inadequate</p><p>- Augment and prolong depolarizing relaxant (↑ ACh at NMJ, also inhibits PChE!)</p><p>- Weakness if high dose (ceiling 0.07mg.kg^-1^)</p>|
|Neuronal type|<p>- Autonomic ganglia (α~3~β~4~): Stimulation then depression (see BJA-Education)</p><p>- Brain (α~4~β~2~): Nil (quaternary amine, doesn’t cross BBB)</p>|

### Muscarinic Effects


|Site|Effect|
| -- | -- |
|PSNS post-ganglionic|<p>- Receptor effects:</p><p>&emsp;- M~1,3,5~: Gq GPCR (↑ IP3/↑ Ca^2+^, ↑ DAG)</p><p>&emsp;- M~2,4~: Gi GPCR (↓ cAMP)</p><p>- Clinical effects:</p><p>&emsp;- Bradycardia, AV block, ↓ cardiac output (cardiac plexus M~2~).</p><p>&emsp;- Constriction of airway smooth muscle → Obstruction (airway smooth muscle M~3~)</p><p>&emsp;- -↑ Tracheobronchial secretion → Cough, aspiration (M~3~)</p><p>&emsp;- ↑ Salivation (M~3~)</p><p>&emsp;- ↑ Lacrimation (M~3~)</p><p>&emsp;- ↑ Ureteric peristalsis → Urination (treats bladder atony)</p><p>&emsp;- ↑ GIT peristalsis → Defecation, nausea/vomiting, abdo pain; treats pseudo-obstruction</p>|
|SNS post-ganglionic|<p>- ↑ Sweating</p><p>- ↑ Skin vasodilatation</p><p>- ↑ Skeletal muscle vasodilatation</p>|


--- 

