# 2017A Question 02 


Compare and contrast O~2~ delivery via nasal cannulae, simple facemask and Venturi mask


## Examiner Report

39.3 % of candidates achieved a pass in this question.


This can be answered either in tabular form or under separate headings.


A good answer included most of the following: performance type (variable or fixed), oxygen
reservoir, physical principle utilised, gas flow rates, range of FiO2 possible, risk of rebreathing,
advantages/disadvantages and factors affecting performance.


Better candidates demonstrated understanding of the relationship between peak inspiratory
flow and FiO2 in each device, and the effect of ventilatory pattern. Stating those conditions that
favour higher FiO2 is a concise way to show such knowledge.


Additional marks were awarded for explaining the Bernoulli effect, Venturi effect and
application of jet entrainment. A diagram of such often provided valuable clarification.


Extensive lists of advantages were not alone sufficient to pass.

## Model Answer

For each device:
- Describe device, fixed vs variable, max FiO~2~, flow rate
- Reservoir, dead space, humidification
- Sources of error, pros and cons

### Nasal Cannulae


|Property|Detail|
| -- | -- |
|Features|<p>- One short prong in either nostril</p><p>- Tubing connects to cylinder or wall</p><p>- Variable performance device</p><p>- Gas flow rate 1-4L/min</p><p>- FiO~2~ ≤ 0.4</p><p>- Reservoir in nasopharynx but not device</p><p>- No dead space</p><p>- No humidification</p>|
|Pros|<p>- Simple</p><p>- Comfortable at low flow rate</p><p>- No risk of rebreathing</p><p>- Patient can eat</p>|
|Cons|<p>- Drying and epistaxis at high flow rate or prolonged use</p>|
|Factors affecting FiO~2~|<p>- ↑ Peak inspiratory flow rate (PIFR) → ↑ Air entrainment → ↓ FiO~2~</p><p>- ↑ VT → ↑ Air entrainment</p><p>- Hence most effective if the cause of hypoxia is hypoventilation</p>|

### Face Mask


|Property|Detail|
| -- | -- |
|Features|<p>- Mask with ~100mL volume inside</p><p>- Holes on the size (sometimes expiratory-opening flap valves)</p><p>- Tubing from the bottom (sometimes with reservoir bag)</p><p>- Variable performance</p><p>- Gas flow rate up to 10L/min</p><p>- FiO~2~: Up to 0.6 (up to 0.8 if reservoir bag)</p><p>- Mask is both O~2~ reservoir and dead space 100mL</p><p>- ± Extra reservoir in bag ~500mL?</p><p>- No humidification</p>|
|Pros|<p>- Easy to use</p><p>- Comfortable</p><p>- Can deliver nebulized medicines e.g. Salbutamol</p>|
|Cons|<p>- Less comfortable</p><p>- Can’t eat, can’t talk much</p>|
|Factors affecting FiO~2~|<p>- As for nasal cannulae, but less affected due to reservoir</p>|

### Venturi Mask


|Property|Detail|
| -- | -- |
|Features|<p>- Well-fitting face mask</p><p>- Exhalation pores</p><p>- O~2~ supply at the bottom, larger bore tubing</p><p>- Venturi device within the tubing (see pic)</p><p>- 100% O~2~ flows through a constriction</p><p>- Mechanism:</p>&emsp;- ?Bernoulli Principle: ↑ Kinetic energy → ↓ Potential (pressure) energy → Room air entrained due to pressure gradient</p><p>&emsp;- ?Coanda Effect: Air drawn in due to friction and surface tension forces (probably this)</p><p>- Fixed performance device; specified entrainment ratio for each attachment</p><p>- FiO~2~ up to 0.7 (but less accurate >0.5)</p><p>- Mask is both O~2~ reservoir and dead space ~100mL</p><p>- Humidifier present</p>|
|Pros|<p>- Fixed performance → Can calculate PAO~2~, A-a gradient</p><p>- Can be humidified</p>|
|Cons|<p>- Uncomfortable</p><p>- Can’t be sure of fixed performance due to leak</p>|
|Factors affecting FiO~2~|<p>- ↑↑ PIFR → Air entrainment around the sides of the mask, becomes a variable performance device</p><p>- Water → Obstruction → ↓ Entrainment</p>|


--- 

