# 2017A Question 08 

Compare and contrast low molecular weight heparin and unfractionated heparin.


## Examiner Report

51.2% of candidates achieved a pass in this question.


Considerations in answering this question include dosing, monitoring, reversibility, effect of
renal impairment and adverse effect profile.


Marks were available for descriptions of their mechanisms of action and pharmacokinetic
profile. Although most candidates were aware that LMWH principally acts via factor Xa and UFH
via both Xa and IIa, very few could explain why. Many did not appreciate that all heparins act
via inducing a conformational change in Antithrombin (AT). The inhibitory effect on thrombin
requires the formation of a triple complex of AT/ heparin/ thrombin and this is only achieved
with long chained heparins which are found predominantly in larger UFH preparations. The
different pharmacokinetic profiles were poorly described and understood. UFH is highly protein
bound and subject to extensive metabolism by heparinases. At high doses this pathway is
saturated and UFH exhibits zero order kinetics. LMWHs are less protein bound, have better
bioavailabilityailability and predictable linear kinetics as they are principally eliminated renally.


Better candidates mentioned timing implications with regard to neuraxial blockade; cost
considerations; heparin resistance and the effect of high doses of UFH on platelet function.

## Model Answer

Structure:
- PC
- PK
- PD

### Physicochemical


||Unfractionated heparin (UFH)|Low molecular weight heparin (LMWH)|
| -- | -- | -- |
|MW|5-25kDa|~4.5kDa|
|Derivation|<p>Pig intestine</p><p>Cow lung</p>|Same|
|Aqueous solution|Y|Y|

### Pharmacokinetic


||UFH|LMWH|
| -- | -- | -- |
|Admin|<p>- S/C BD prophylaxis</p><p>- IV infusion therapeutic</p>|<p>- S/C prophylaxis daily</p><p>- S/C therapeutic 1mg.kg^-1^ bd or 1.5mg.kg^-1^ daily<br>  (more convenient)</p>|
|Time course|<p>- Onset IV ≤5 min</p><p>- Onset S/C 2 hours</p><p>- Offset therapeutic IV infusion: 6 hours</p>|<p>- Peak: 2-4 hours</p><p>- Offset prophylactic: 12 hours</p><p>- Offset therapeutic: 24 hours (↑ if renal impairment)</p>|
|Absorption|<p>- Good S/C bioavailability</p>|<p>- Good S/C bioavailability</p>|
|Distribution|<p>- V~D~ 0.1L/kg</p><p>- Plasma protein binding >95%</p><p>&emsp;- 1/3 AT3</p><p>&emsp;- 2/3 other (albumin etc.)</p><p>- Doesn’t cross placenta as much</p>|<p>- V~D~ 0.1L/kg</p><p>- Plasma protein binding >95% (almost all AT3)</p><p>- Does cross placenta</p>|
|Metabolism / excretion|<p>- Variable rate</p><p>- Zero order kinetics at high doses.</p><p>- Heparinase: Desulfation, depolymerisation</p><p>- Small amount urine unchanged</p><p>- t1/2β 90 mins</p>|<p>- Less variable rate</p><p>- ?First order</p><p>- Some by heparinase</p><p>- Most in urine unchanged</p><p>- t1/2β ~5 hours</p><p>- ↓ Dose in renal impairment</p>|

### Pharmacodynamic


|Therapeutic|UFH|LMWH|
| -- | -- | -- |
|MoA|<p>- Binds AT3 → Change shape<br>&emsp;(30% of heparins have a pentasaccharide sequence that binds AT3)</p>|<p>- Same</p>|
|Factors inhibited|<p>- II:X ratio = 1:1 (Only saccharides >18 long can bridge AT3 and II)</p><p>- Also 11, 9, VIIa:TF complex</p>|<p>- IIa:Xa ratio = 1: 2-3</p>|
|Platelet activation|<p>- Yes</p>|<p>- Minimal</p>|
|Reversibility with protamine|<p>- Near 100%</p><p>- Risk rebound anticoag as t1/2β longer than protamines (90 cf. 60)</p>|<p>- ~60%</p><p>- Note risk re-bound anticoag as more is absorbed from S/C fat</p>|
|Monitoring|<p>- aPTT (titrate to 1.5-2.5x control)</p><p>- Mandatory if infusion (↑ variable response due to many binding sites)</p>|<p>- FXa (less available)</p><p>- Usually not needed (bound to AT3 only, less variable)</p>|


|Side Effects|UFH|LMWH|
| -- | -- | -- |
|Heparin-induced thrombocytopaenia|<p>- 1/200 therapeutic dose</p><p>- 1/1000 prophylactic dose</p>|<p>- ↓ Risk</p>|
|Bleeding|<p>- ↑ Risk (1-5%)</p><p>- But can reverse</p>|<p>- ↓ Risk</p><p>- But can’t fully reverse</p>|
|Other side effects|<p>- Deranged LFTs</p><p>- Osteoporosis</p><p>- Skin necrosis</p><p>- Alopecia</p><p>- IV bolus: Hypotension</p>|<p>- Similar to UFH but lower risk</p>|


--- 

