# Absorption

:::dual
Describe absorption and factors that will influence it with reference to clinically utilised sites of administration.
:::

Absorption is dependent on the route of administration. Routes of administration are selected based on:

* Effect site of the drug
* Drug factors
    * Bioavailability
    * Available preparations
* Patient factors
    * Ability to take or absorb oral medications
    * Preference


## Bioavailability

**Bioavailability** is the **proportion of drug given which reaches the systemic circulation unchanged**, compared to the IV form. Bioavailability is affected by:

* Formulation
* Physicochemical Interactions\
Interactions with other drugs and food.
* Patient Factors
    * Malabsorption syndrome
    * Gastric stasis
* First-pass metabolism


### Significance of Bioavailability

Bioavailability indicates how the dose-exposure relationship is affected by:

* Drug factors
    * Formulation
    * Solubility
* Patient factors
    * Comorbidities
    * Diet
    * Critical illness


## Enteric Administration

Enteric administration is affected by:

* Gastric pH
* Gastric emptying and intestinal motility
* First pass metabolism


### Gastric pH

Gastric pH affects absorption as it alters the proportion of drug that is in an unionised form, and therefore available to cross the gastric mucosa:

* ↓ Gastric pH ↑ absorption of alkaline drugs
* ↑ Gastric pH ↓ absorption of acidic drugs
* Gastric pH is:
    * Neutral at birth
    * Becomes briefly acidic (pH 1-3) a few hours after birth, but returns to neutral after 24 hours
    * Adult values for gastric acidity are reached at ~2 years


## First-pass Metabolism

**First-pass** (pre-systemic) **metabolism** is the extent to which drug concentration is reduced after its first passage through an organ, prior to reaching the systemic circulation. First pass metabolism is:

* Typically used when referring to passage of orally-administered drugs through the liver\
May also refer to metabolism by the:
    * Lungs\
    First pass of intravenously injected drugs prior to entering the arterial side of the circulation, e.g. fentanyl.
    * Vascular endothelium
* Relevant in:
    * Understanding differences between PO and IV dosing
        * Alternative routes of administration for drugs with low PO bioavailability
    * Delivery of prodrugs via PO mechanisms\
    Increases active drug concentration.
    * Understanding enzyme interactions 
    * Understanding the effects of hepatic disease
        * Porto-systemic shunts decrease first pass metabolism
        * Altered bioavailability of drugs with high hepatic extraction ratios

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
1. [Chong CA, Denny NM. Local anaesthetic and additive drugs.](http://www.frca.co.uk/documents/anaes.5.5.158.pdf)
1. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
1. Starkey ES, Sammons HM. [Practical pharmacokinetics: what do you really need to know?](https://ep.bmj.com/content/100/1/37) Arch Dis Child Educ Pract Ed. 2015 Feb;100(1):37–43. 
