---
level: 3
---

# Routes of Administration

:::dual
Describe absorption and factors that will influence it with reference to clinically utilised sites of administration.
\
Describe the pharmacokinetics of drugs in the epidural and subarachnoid space.
:::

## Intravenous

Intravenous administration is characterised by:

* Rapid Onset
* 100% bioavailability\
Some drugs may still undergo metabolism in the pulmonary circulation, such as fentanyl, lignocaine, propofol, and catecholamines.

## Oral

Oral absorption is through gut mucosa, through either:

* Transport mechanisms
* Diffusion of unionised (lipid soluble) molecules
    * Acidic drugs are absorbed more rapidly in the stomach
    Note that the small bowel absorbs both acid (despite being ionised) and alkaline drugs due to high surface area.
* Lowest bioavailability of any route due to:
  * First-pass metabolism
  * Gut metabolism of drugs
  * Bacterial metabolism of drugs
* Drugs must be lipid soluble enough to cross cell-membranes and water soluble enough to cross interstitium

Factors affecting GIT Absorption:

* Drug Factors
    * Molecular Weight
    * Concentration Gradient
    * Lipid Solubility
       * pH and pKa
    * Pharmaceutical Preparation
    * Physiochemical Interactions
        * Food
        * Other drugs
* Patient Factors
    * GIT blood flow
    * Surface Area\
    Small bowel has the largest surface area of any GIT organ.
    * pH
    * Motility
    * Digestive Enzymes
    * GIT bacteria and subsequent metabolism
    * Disease
        * Critical Illness
        * Bowel Obstruction
        * Emesis/Diarrhoea


## Epidural

Factors affecting epidural absorption include:

* Dose given
* Volume given\
Increased volume increases area of subarachnoid that the drug is in contact with, increasing rate of diffusion.
* Rate of administration\
May be via bolus or infusion.
* Solubility\
Affected by:
    * pKa and pH\
    Determines unionised portion available to cross into CSF. Lignocaine has a more rapid epidural onset than bupivacaine as it has a pKa of 7.9 (compared to 8.4) and therefore a greater unionised portion at physiologic pH.
    * Protein binding\
    Determines free drug portion able to cross into CSF.
    * Lipid solubility
* CSF flow\
Alters concentration gradient between epidural and subarachnoid space.
* Intrinsic vasoactive properties of the delivered drug
* Additives


## Subarachnoid/Intrathecal

Intrathecal administration is characterised by:

* Very small dosing
* Minimal systemic spread

Extent of subarachnoid spread is dependent on:

* Volume and total dose\
And concentration - these three factors are interdependent.
* Baricity\
Iso-, hypo-, and hyperbaric preparations are available and affect direction of spread:
    * Hyperbaric solutions will sink with gravity\
    e.g. Heavy bupivacaine (0.5% bupivacaine with 8% dextrose)
    * Hypobaric solutions will rise against gravity
* Patient position\
The combination of a supine or Trendelenburg patient position with high-specific gravity solutions increases cranial spread of the block.
* Intrinsic vasoactive properties of the delivered drug
* Additives


## Inhalation

Inhalational administration characterised by:

* Rapid diffusion to circulation due to high surface area and no first-pass metabolism
* Variable systemic absorption; dependent on particle size
    * Large particles reach the bronchioles
    * <1 micron diameter particles may reach the alveolus

## Transdermal

Transdermal absorption is determined by the **Fick Principle**:

* Concentration gradient
    * Amount of drug given
    * Amount of drug in skin
* Regional blood flow
    * Histamine release
* Surface Area
* Skin thickness
* Lipid solubility
    * pH of skin and emulsion
    * pKa of drug
* Molecular weight


Advantages:

* Convenient
* Painless
* No first pass metabolism
* Steady plasma concentration once established


Disadvantages:

* Slow onset
* Variable plasma concentration initially
* Overdose and abuse potentials
* Dose requirement\
Large dose requirements cannot be effectively given transdermally.

## Subcutaneous

* Absorption dependent on regional blood flow

## Sublingual

* Rapid onset
* Bypass portal circulation \(drains into SVC\)

## Rectal

* Variable absorption
    * Distal rectal absorption bypasses portal circulation
    * Proximal rectal absorption does not and may result in hepatic first pass metabolism
    * Small surface area for absorption


## Intramuscular

* Bioavailability close to 1
* Absorption dependent on regional blood flow
* Potential local complications:
    * Abscess
    * Haematoma

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. [Chong CA, Denny NM. Local anaesthetic and additive drugs.](http://www.frca.co.uk/documents/anaes.5.5.158.pdf)
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
4. ANZCA February/April 2007
5. [Factors influencing distribution of bupivacaine after epidural injection](https://primarysaqs.files.wordpress.com/2009/12/2007a2after-epidural-injection-discuss-factors-influencing-dist-of-bup.pdf). Diaz Notes.
