# Isomerism

:::CICM
Describe the pharmaceutics and formulation of drugs including ~~packaging, formulation,~~ isomerism, ~~compatibility and excipients (additives)~~ as they pertain to drugs.
:::

:::ANZCA
Describe and give examples of the clinical importance of isomerism
:::

**Isomerism**:

* Describes groups of **compounds which have the same chemical formula but different chemical structures**
* Has relevance because **different isomers may have different** enzymatic and receptor affinities, altering their pharmacokinetic and pharmacodynamic **properties**

## Types of Isomerism

Isomers can be divided into:

* Structural Isomers
* Stereoisomers

### Structural Isomers

Have an **identical** chemical **formula** but **different arrangement** of atoms. Structural isomerism is subdivided into:

* **Static**\
Further subdivided into:
    * Chain isomer\
    The carbon skeleton varies, but position of functional groups is static.
    * Position isomer\
    The carbon skeleton is static, but the position of functional groups varies.
        * e.g. Isoflurane vs. enflurane
* **Dynamic** (also known as tautomer)\
The molecule exists in a different molecular structures depending on the environment.
    * e.g. Midazolam has pH dependent imidazole ring opening. When the pH is less than 4 the ring remains open, maintaining water solubility. Midazolam is supplied at pH of 3.5, and so is water soluble on injection but (due to its pKa of 6.5) becomes 89% unionised at physiological pH therefore able to cross lipid membranes.


### Stereoisomers

Have the **same order of connections** between atoms, but a **different orientation of functional groups**. Stereoisomers are **not super-imposable**, meaning the different isomers can't be rotated so that they look the same. Stereoisomers are divided into:

* **Geometric Isomers**\
Have a chemical structure (e.g. a carbon-carbon double-bond) prevents free rotation of groups, so different locations of chemical groups will create an isomer. Geometric isomers are known as **cis-** or **trans-** depending on whether the subgroups are on the same or opposite sides (respectively) of the chemical structure.
    * e.g. Atracurium
* **Optical Isomers**\
Optical isomers are **chiral**. This means they have **no plane of symmetry**. Optical isomers:
    * Were initially named based on how they rotated under polarised light^[(Note the d- and l- nomenclature is *different* to D- and L-; the D-isomer refers to the molecule synthesised from (+)glyceraldehyde.)]:
        * **Dextrorotatory**\
        (d- or (+) isomers) molecules rotate **clockwise** under polarised light.
        * **Levorotatory**\
        (l- or (-) isomers) molecules rotate **counter-clockwise** under polarised light.
    * Unfortunately, some molecules were found to rotate in different directions depending on the temperature  
    Therefore, **another classification scheme** (**R/S**) is also used:
        * Based on chemical structure
        * "Priority" is assigned to each atom in the structure
        * Highest priority is usually those with the highest molecular weight, but other rules exist for ambiguous or very large molecules
        * The molecule is arranged in space such that the lowest priority atom is facing "away"
        * An arrow is then drawn from the highest priority to the lower priority atoms:
            * If this arrow travels **clockwise** it is the **R (Rectus)** isomer
            * If this arrow travels **counter-clockwise** it is the **S (Sinister)** isomer
    * Optical isomers are divided into:
        * **Enantiomers**\
        Possess one chiral centre.
            * e.g. levobupivacaine is less cardiotoxic than racemic bupivacaine.
        * **Diastereoisomers**\
        Possess multiple chiral centres, and may have multiple stereoisomers. Since not all are mirror images, these are not *enantiomers*.
            * For a molecule with *n* chiral centres up to *n^2^* isomers are possible, though some of these may be duplicates.

## Preparations

Drugs can be provided as:

* **Racemic solutions**\
A **racemic** solution is one which where the different enantiomers are present in equal proportions.
* **Enantiopure preparations**\
A drug produced with a single isomer, which may be **more efficacious** or **less toxic** (and definitely more expensive) than the racemic preparation.


---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. CICM. [The Mock Exam](http://www.cicm.org.au/CICM_Media/CICMSite/CICM-Website/Trainees/Assessments%20and%20Examinations/First%20Part%20Exam/Mock-Exam-First-Part-Examination.pdf). 
2. ChemGuide. [Geometric isomerism](http://www.chemguide.co.uk/basicorg/isomerism/geometric.html)
3. ChEBI. [Misoprostol](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:63610). European Molecular Biology Laboratory.
4. ANZCA July/August 2000
5. Day J, Thomson A, McAllister T. Get Through Primary FRCA: MTFs. 2014. Taylor & Francis Ltd.