# Mechanisms of Action

:::dual
To explain the concept of drug action with respect to: receptor theory, enzyme interactions, and physicochemical interactions.\
:::

Drugs can act in four major ways:

::: column-margin
Receptors and ion channels are discussed in detail under @sec-receptortheory.
:::

* **Receptors**
    * GPCR
    * Intracellular
        * Cytoplasmic
        * Intranuclear\
        e.g. Steroids, which alter RNA expression.
* **Ion Channels**
* **Enzyme interaction**
    * Antagonism
    * False substrates
* **Physicochemical**
    * Osmotic
    * Acid-base
    * Chelation
    * Redox reactions

## Enzyme Interaction

An enzyme is a biological catalyst, increasing the speed of reaction. Drugs can interact with enzymes by:

* Antagonism
* False substrate

### Enzyme Antagonism

Most drugs which interact with enzymes inhibit their activity. This results in:

* Increased concentration of enzymatic substrate
* Decreased concentration of the product of the reaction

Drugs can be competitive::: column-margin
Ramipril is a competitive inhibitor of angiotensin-converting enzyme.], non-competitive, or irreversible inhibitors^[Aspirin is an irreversible inhibitor of cyclo-oxygenase.
::: of enzymatic activity.

### False Substrates

False substrates compete with the enzymatic binding site, and produce a product::: column-margin
Methyldopa is a false substrate of the enzyme dopamine decarboxylase.
:::.


## Physicochemical

Drugs whose mechanism of action is due to their physicochemical properties, such as:

* Tonicity::: column-margin
Mannitol reduces ICP because it increases tonicity of the extracellular compartment (and is unable to cross the BBB), drawing free water from the intracellular compartment as a consequence.
:::
* Chemical reactions::: column-margin
Aluminium hydroxide reacts with gastric acid to form aluminium chloride and water, reducing stomach pH.
:::
* Surface tension


---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.

