---
level: 3
---

# Metabolism

:::dual
Describe the mechanisms of non-hepatic and hepatic metabolism of drugs including: Phase one and phase two reactions, Hepatic extraction ratio and its significance, First pass effect, enzyme induction and inhibition
:::

Metabolism refers to the transformation of a drug to a new (often inactive) form by a living organism, usually via an enzymatic pathway. Metabolism may occur:

* Hepatically
* Non-hepatically
    * Organ-dependent
    * Organ-independent


## Hepatic Metabolism

The principal organ of drug metabolism is the liver. Hepatic metabolism:

* Usually decreases the function of a drug, though:
  * **Prodrugs** have increased pharmacologically activity after liver metabolism
  * Some drugs have active or toxic metabolites
* Can be divided into **two phases**:
    * Phase I
    * Phase II

### Phase I

Phase one reactions:

* Occur in the **endoplasmic reticulum**
* Improve water solubility by exposing a functional chemical group
* Typically occur prior to phase II reactions for most drugs
* Include three key processes^[The mnemonic **OIL RIG: Oxidation Is Loss, Reduction Is Gain** can be used to remember the direction of electron transfer in oxidation and reduction reactions.]:
  * **Oxidation**\
    Loss of electrons.
    * Main phase I reaction
    * CYP450 driven
  * **Reduction**\
    Gain of electrons.
    * CYP450 driven
  * **Hydrolysis**\
    Addition of a water molecule, which may result in two new compounds.
    * Esterase driven\
    Therefore rapid, high capacity, organ-independent elimination.
      * Butylcholinesterase
      * Non-specific plasma cholinesterase
      * RBC esterase


### CYP450 System

The CYP450 family of enzymes are:

* A *super*family of enzymes vital in drug metabolism  
Over 1000 enzymes, with ~50 functionally active.
* Named after the wavelength of light they absorb when reduced and combined with carbon monoxide
* Located in:
    * Liver\
    Endoplasmic reticulum of hepatocytes.
    * Lungs
    * Kidney
    * Gut
    * Brain
* Classified by the degree of shared amino-acid sequence into:
     * Families\
     CYP1, CYP2, CYP3...
    * Subfamilies\
    CYP1A, CYP1B...
    * Isoforms\
    CYP1A1, CYP1A2...


### Key CYP450 Enzymes


|  CYP2B6  |             CYP2C9            |                   CYP2C19                    |              CYP2D6             |                  CYP2E1                  |                                CYP3A4                                |  CYP3A5  |
|----------+-------------------------------+----------------------------------------------+---------------------------------+------------------------------------------+----------------------------------------------------------------------+----------|
| Propofol | Propofol, Parecoxib, Warfarin | Diazepam, Omeprazole, Clopidogrel, Phenytoin | Codeine, Metoprolol, Flecainide | Volatile anaesthetic agents, paracetamol | Common benzodiazepines, Fentanyl, Alfentanil, Lignocaine, Vecuronium | Diazepam |

**CYP2D6**:

* Important because genetic polymorphism leads to significant inter-patient variability\
May result in significant over- or under-metabolism of drugs, and therefore significant inter-individual variability in response.
    * 5-10% of the population are poor metabolisers
    * 2-10% are intermediate metabolisers
    * 1-2% are ultra-rapid metabolisers
    * Bulk of the population (70-90%) are extensive metabolisers
* Clinical effect will depend on the type of drug
    * Pro-drugs\
        * Extensive/ultra-rapid metabolisers will convert more drug to the active form, and see a greater effect\
        May lead to overdose.
        * Poor metabolisers will excrete more pro-drug prior to metabolism, and see a reduced clinical effect
    * Active drug
        * Extensive/ultra-rapid metabolisers will inactivate more drug, and see a reduced effect
        * Poor metabolisers will see a prolonged clinical effect
    * Clinical effect may be altered by enzyme interactions\
    e.g. Oxycodone use by an ultra-fast metaboliser, in combination with a CYP3A4 inhibitor (e.g. diltiazem) will result in a significant increase in the clinical effect of oxycodone.
* Drugs metabolised by CYP2D6 include:
    * Analgesics
        * Codeine (prodrug)
        * Oxycodone (metabolised to the significantly more potent oxymorphone)
        * Methadone
        * Tramadol (metabolised to form with greater MOP selectivity)
    * Psychiatric drugs
        * SSRIs
        * TCAs
        * Haloperidol
    * Cardiovascular drugs
        * Amiodarone
        * Flecainide
        * Mexiletine

### Phase II

Phase II reactions:

* Involve conjugation with another compound, producing a highly polar metabolite\
This increases water solubility and therefore renal elimination.
* Typically occur in the hepatic endoplasmic reticulum
* Include:
    * **Glucuronidation**\
    Addition of glucuronic acid.
    * **Sulfation**\
    Addition of a sulfa group.
    * **Acetylation**\
    Addition of an acetyl group.
    * Also occurs in the **lung** and **spleen**.
    * **Methylation**\
    Addition of a methyl group.

### Extraction Ratio

The **extraction ratio** is the proportion of a drug that is cleared from circulation during each pass through the organ, typically the liver:

$ER = { Drug \ Absorbed - Drug \ reaching \ systemic \ circulation \over Drug \ Absorbed }$

Extraction ratio is dependent on:

* Blood flow
* Hepatocyte uptake
* Enzyme capacity\
Described by the **Michaelis Constant**: The concentration of a substrate which causes an enzyme to work at 50% of its maximum capacity.

Drugs can have either a high or low extraction ratio:

* **High extraction ratio**\
These drugs have a rapid uptake and high capacity, so elimination is **perfusion dependent**.
  * Free drug is rapidly removed from plasma, bound drug is released from plasma proteins and a concentration gradient is maintained
  * Metabolism of drugs with a high extraction ratio is:
    * **Independent of protein binding**
    * **Dependent on liver flow**\
    Typically doubling liver blood flow will double hepatic clearance.
  * There is a **high variability** in plasma concentration between individuals due to the variation in liver blood flow
  * Drugs with high extraction ratios are generally independent of enzyme activity - decreasing enzyme activity from 99% to 95% has a minimal effect on hepatic clearance
    * The **key exception** is **first pass metabolism**, as the above change will result in a five-fold difference in dose reaching the systemic circulation\
    Therefore drugs with a high extraction ratio have low PO bioavailability.
* **Low extraction ratio**\
Elimination is **capacity-dependent**.
  * Amount of free drug available for metabolism is greatly affected by the degree of protein binding
  * Metabolism is:
    * Largely **independent of flow**\
    Drugs have good PO bioavailability.
    * **Dependent on hepatocyte function and protein binding**

### Factors Affecting Hepatic Metabolism

|Drug Factors|Patient Factors|
|--|--|
|Lipid solubility|Age|
|Ionisation|Obesity|
|Protein binding|Pregnancy|
|Enzyme competition|Genetics: Slow vs. fast acetylators|
||Hepatic flow/Extraction Ratio|
||Enzyme Inhibition/Induction|
||Hepatic disease|
||Smoking, ETOH|

## Organ Independent Metabolism

Mechanisms of organ independent metabolism include:

* **Hofmann Degradation**\
Spontaneous degradation or metabolism of substances occurring in plasma.
  * e.g. Cisatracurium undergoes Hofmann degradation
* **Plasma Esterases**\
Plasma esterases are non-microsomal enzymes which hydrolyse ester bonds. They:
  * Are typically synthesised in the liver and erythrocytes
  * Have a **high capacity**\
  This, combined with the organ-independent elimination, means drugs metabolised by plasma esterases have a reliable offset.
    * e.g. Suxamethonium hydrolysis by plasma esterases.

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Essential pharmacology for the ANZCA primary exam
3. Birkett, DJ. [Pharmacokinetics made easy 9: Non-linear pharmacokinetics](https://www.nps.org.au/australian-prescriber/articles/pharmacokinetics-made-easy-9-non-linear-pharmacokinetics). 1994. Australian Prescriber.
