# Diuretics

> An understanding of the pharmacology of diuretics.

Diuretics are drugs that act on the kidney to increase urine production. They can be classified by their mechanism of action into:

* Thiazides
* Loop diuretics
* Potassium sparing
* Aldosterone antagonists
* Osmotic
* Carbonic Anhydrase inhibitors

## Common Features of Diuretics

|Property|Diuretics
|--|--|
|**Absorption**|Typically poor bioavailability (exception: **acetazolamide**)
|**Distribution**|Variable protein binding
|**Metabolism**|Generally not metabolised. Key exceptions: Spironolactone is extensively metabolised with active metabolites, and a small amount of **frusemide** is metabolised to glucuronide.
|**Elimination**|Renal elimination of unchanged drug
|**CVS**|Reduced intra and extravascular volume
|**Renal**|Any diuretic which inhibits sodium reabsorption can precipitate hypokalaemia (as a greater intra-luminal concentration of sodium results in exchange of sodium for potassium ions), hyponatraemia (as there is still a net loss of sodium), and alkalosis (from loss of hydrogen ions exchanged for sodium, or the overall raised strong ion difference). 


## Comparison of Diuretics

||Thiazides|Loop Diuretics|Potassium Sparing|Aldosterone antagonists|Osmotic|Carbonic anhydrase inhibitors|
|--|--|-----------|--|--|--|
|**Example**|Hydrochlorothiazide|Frusemide|Amiloride|Spironolactone|Mannitol|Acetazolamide|
| **Site**|Distal tubule|Loop of Henle|Distal tubule|Distal tubule|Glomerulus|Proximal tubule|
|**Mechanism of action**|Inhibit Na^+^ and Cl^-^ reabsorption, and increase Ca^2+^ reabsorption in the DCT|Inhibit NKCC2, the Na^+^/K^+^/2.Cl^-^ transport protein in the thick ascending limb, impeding the counter-current multiplier. This reduces the hypertonicity of the medulla, and subsequent water reabsorption in the collecting system.|Inhibits Na^+^/K^+^ exchange pump. Weak effect.|Competitive aldosterone antagonist. Aldosterone stimulates Na^+^ reabsorption, which in turn stimulates K^+^ secretion.|Filtered at the glomerulus and not reabsorbed, increasing filtrate osmolarity and increases water excretion.|Non-competitive carbonic anhydrase inhibition, causing a bicarbonate diuresis. There is a loss of Na^+^, urinary HCO~3~^-^, and a retention of H^+^ |
|**Resp**||||||↑ RR due to metabolic acidosis
|**Cardiac** |Antihypertensive due to reduced plasma volume and SVR|Arteriolar vasodilation, reducing SVR and preload|||Increases intravascular volume, increasing preload. May increase CO or result in cardiac failure.||
|**CNS**|||||↓ ICP|↓ IOP, ↓ ICP|
|**Renal**| Reduced renal blood flow and GFR|Increased renal blood flow and GFR|||Increased renal blood flow|Urinary alkalinisation and diuresis. In the tubule, prevents conversion of HCO~3~^-^ and H^+^ to CO~2~, causing HCO~3~^-^ elimination. In the tubular epithelium, prevents conversion of CO~2~ to HCO~3~^-^ and H^+^, which supplies hydrogen ions usually secreted into the proximal tubule in exchange for Na^+^. This causes both a retention of acid and loss of Na^+^ and H~2~O.|
|**Metabolic**|Hypokalaemic, hypochloraemic alkalosis. Hyperglycaemia. |Hypochloraemia, hyponatraemia, hypokalaemia, hypomagnesaemia. Occasional **hyper**uricaemia precipitating gout.|Hyperkalaemia.|Hyperkalaemia, hyponatraemia.||Hyperchloraemic acidosis|
|**Miscellaneous**|Blood dyscrasias|Deafness, typically following large doses. More common in kidney impairment and with aminoglycoside use.||Gynaecomastia and menstrual irregularity due to anti-androgynism from aldosterone antagonism|||| 

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.
2. Rang HP, Dale MM, Ritter JM, Flower RJ. Rang and Dale's Pharmacology. 6th Ed. Churchill Livingstone.
3. Auerbach. Wilderness Medicine. Sixth Edition.