---
level: 2
---

# Buffers

:::CICM
Describe the chemistry of buffer mechanisms and explain their relevant roles in the body
:::

A **buffer** is a solution which consists of a **weak acid and its conjugate base**, that can **resist a change in pH** when a stronger acid or base is added.

$Buffer + H^+ \Leftrightarrow H.Buffer$

Buffering:

* Is a key part of acid-base homeostasis
* Allows compensation for large changes in acid or alkali load with minimal change in hydrogen ion concentration\
    * In one experiment, dogs were infused with 14,000,000 nmol.L^-1^ of H^+^, with a corresponding rise in H^+^ of only 36 nmol.L^-1^

Efficacy of a buffer system is determined by:

* **pKa** of the buffer\
80% of buffering occurs within 1 pH unit of the pKa of the system.
* pH of the solution
* **Amount of buffer**
* Whether it is an **open or closed system**\
An open buffer system can have the amount of chemical at one (or both) ends adjusted by physiological means.
    * This alters the concentration of reactants at either end of the equation, thus altering the speed of the reaction via the Law of Mass Action

## Buffer Systems

Important buffer systems include:

* Bicarbonate buffer system
* Protein buffer system
    * Haemoglobin buffer system
* Phosphate buffer system

All buffer systems are in equilibrium with the same amount of H^+^. This is known as the **isohydric principle**.


### Bicarbonate Buffer System

The bicarbonate buffer system is:

* The most important ECF buffer system
    * Bicarbonate is formed in the erythrocyte and then secreted into plasma
    * Bicarbonate diffuses into the interstitium and is also the dominant fluid buffer in interstitial space
* Formed in the erythrocyte
* A **buffer pair** consisting of bicarbonate and carbonic acid\
Carbonic acid is exceedingly short lived in any environment even remotely compatible with life and it rapidly dissociates to HCO~3~^-^ and H^+^.

Hydrogen ions are consumed or released by the following reaction:

* $H_2CO_3 \Leftrightarrow H CO_3^- + H^+  \Leftrightarrow  CO_3^{2-} + 2H^+$
* Carbonic anhydrase (present in erythrocytes) is an enzyme which allows rapid conversion of H~2~O and CO~2~ to H~2~CO~3~ (and back again)
* Each stage of the reaction has an individual pKa:
    * As the pKa of the $H_2CO_3 \Leftrightarrow H CO_3^- + H^+ $system is 6.1, these substances predominate at physiological pH
    * The pKa for the second stage of the reaction is 9.3 and so essentially no CO~3~^2-^ exists in blood\
    Clincically this reaction can be ignored.
* In clinical conditions, the reaction becomes:\
$H_2O + CO_2 \Leftrightarrow H_2CO_3 \Leftrightarrow H CO_3^- + H^+ $
    * Addition of a strong acid drives the above reaction to the left, forming (briefly) H~2~CO~3~ before it dissociates to CO~2~ and H~2~O
        * CO~2~ is then able to be exhaled, which prevents equilibration and allows the system to buffer more acid


Bicarbonate is an effective buffer because it is:

* Present in large amounts
* **Open at both ends**\
    * CO~2~ can be adjusted by changing ventilation
    * Bicarbonate can be adjusted by changing renal elimination
    * This prevents the bicarbonate buffer system from equilibrating and allows it to resist large changes in pH despite its low pKa\
    However, because it relies heavily on changes in pulmonary ventilation it is **unable to effectively buffer respiratory acid-base disturbances**.


### Protein Buffer System

* All proteins contain potential buffer groups\
However, the useful one at physiological pH is the **imidazole groups** of the **histidine residues**.
* Extracellularly, proteins have a small contribution which is entirely due to their low pKa
* Intracellularly proteins have a much greater contribution because:
    * Intracellular protein concentration is much greater than extracellular concentration
    * Intracellular pH is much lower (~6.8) and closer to their pKa


### Haemoglobin Buffer System

Haemoglobin is:

* A protein buffer system
* Quantitatively the most important non-bicarbonate buffer system of blood\
This is because haemoglobin:
    * Exists in greater amounts than plasma proteins (150g.L^-1^ compared to 70g.L^-1^)
    * Each molecule contains 38 histidine residues\
    This results in 1g of Hb ~3x the buffering capacity of 1g of plasma protein.

In the cell:

* Haemoglobin exists as a weak acid ($HHb$) as well as its potassium salt ($KHb$)
* In acidosis:
    * Additional H^+^ ions are bound to Hb molecules
    * HCO~3~^-^ diffuses down its concentration gradient into plasma\
    Electroneutrality is maintained through the inwards movement of Cl^-^.
    * Dissolved CO~2~ will also form carbamino compounds by binding to the terminal amino groups
* The **pKa** of Hb is **variable** depending on whether it has bound oxygen:
    * **Deoxyhaemoglobin** has a **pKa of 8.2**\
    Because of its higher pKa, deoxyhaemoglobin will more readily accept H^+^ ions which makes it a better buffer of acidic solutions.
    * **Oxyhaemoglobin** has a **pKa of 6.6**
    * Both are essentially equidistant from normal pH, and are equally effective buffers
    * Quantitatively, **per mmol of oxyhaemoglobin reduced, ~0.7mmol of H^+^ can be buffered**\
    Therefore 0.7mmol of CO~2~ can enter blood **without a change in pH**.
    * This is the mechanism behind the **Haldane effect**, and why venous blood is only slightly more acidic than arterial blood

### Phosphate Buffer System

Phosphoric acid is:

* Tribasic and can therefore potentially donate three hydrogen ions
* However, only one of these reactions is relevant at physiological pH, with a pKa of 6.8:\
$H_2PO_4^- \Leftrightarrow H^+ + HPO_4^-$
* The quantitative effect is low despite the optimal pKa due to the low plasma concentration of phosphate
* At higher concentrations, such as intracellularly and in urine, it is a significant contributor
* In prolonged acidosis, CaPO~4~ can be mobilised from bones and can be considered as an alkali reserve

---

## Further Reading

1. Alex Yartsev offers an excellent discussion on [buffering](http://www.derangedphysiology.com/main/core-topics-intensive-care/acid-base-disturbances/Chapter%202.0.3/buffering-acute-respiratory-acid-base-disturbances) in his excellent trademark prose at [Deranged Physiology](http://www.derangedphysiology.com)
2. Brandis's [anaesthesia MCQ](http://www.anaesthesiamcq.com/AcidBaseBook/ab2_2.php) is required reading

---

## References

1. Barrett KE, Barman SM, Boitano S, Brooks HL. Ganong's Review of Medical Physiology. 24th Ed. McGraw Hill. 2012.
2. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.