# Antiseptics

> Outline the pharmacology of antiseptics and disinfectants

## Key Definitions

Relevant definitions for antiseptics include:

* Cleaning\
Physical removal of foreign material.
    * Used for **non-critical items**, which come into contact with healthy skin but not mucous membranes (e.g. blood pressure cuff)
* Decontamination\
Destruction of contaminants such that they cannot reach a susceptible site in sufficient number to cause harm.
* Disinfection\
Elimination of all pathological organisms, excluding spores.
    * Used for **semi-critical items**, which are those that contact mucous membranes but do not break the blood barrier (e.g. endoscopes, laryngoscopes)
* Sterilisation\
Elimination of all forms of microbial life, including spores.
    * Used for **critical items**, which are those that enter sterile or vascular tissue and pose a high risk of infection (e.g. surgical instruments, vascular and urinary catheters)

## Antiseptic Agents

|Drug|Isopropyl Alcohol|Chlorhexidine|Povidone iodine|
|--|--|
|**Pharmaceutics**|Typically 60-90% - requires some water to denature protein. Flammable.| May be aqueous or combined with isopropyl alcohol.|Iodine combined with a polymer (povidone) to enhance water solubility
|**Antiviral Properties**|Poor antiviral|Poor antiviral|Good antiviral|
|**Antibacterial Properties**|Broad spectrum antibacterial|Broad spectrum antibacterial and antifungal|Broad spectrum including fungi, spores (unlike iodine), and tuberculosis
|**Toxic**|Irritant on mucous membranes and open wounds|Hypersensitivity|Hypersensitivity
|**Other**||Persistent antiseptic effect|Requires continual release of iodine to achieve effect. Inactivated by organic substances. Stains.

---

## References

1. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.
2. Sabir N, Ramachandra V. [Decontamination of anaesthetic equipment](ceaccp.oxfordjournals.org/content/4/4/103.full.pdf). Continuing Education in Anaesthesia, Critical Care and Pain. (2004). 4(4), 103–106. 