# COX Inhibitors


Cyclo-oxygenase inhibitors are typically **used** to treat **mild to moderate pain**. Oral COX inhibitors typically have:

* **Rapid absorption**
* **High protein binding**
* **Low V~D~**

## Mechanism of Action


There are two(ish) **isoenzymes** of COX:

* **COX-1**\
Important for homeostatic function. 
* **COX-2**\
**Induced** with tissue damage and contributes to inflammation. COX-2:
  * Exists in the vascular endothelium where it synthesises prostacyclin (which opposes the action of thromboxanes)
  * Inhibition may result in a relative abundance of thromboxane, causing platelet aggregation and vasoconstriction
* **COX-3**\
Variant of COX-1 which exists centrally and mediates the analgesic and antipyretic effects of paracetamol.
 
Effects occur due to:

* Decrease in endoperoxidases\
Inhibited by COX.
* Increase in other arachidonic-acid derived factors\
Due to the diversion of arachidonic acid down other pathways.

COX inhibition has different effects in different tissues:

* Prevents subsequent conversion of prostaglandins to thromboxane A~2~ and PGI~2~\
* Peripherally, inhibition of prostaglandin synthesis is anti-inflammatory
* Centrally, it is anti-pyretic
* In the stomach, it decreases mucous production and leads to mucosal ulceration


* Aspirin (a non-specific COX inhibitor), prevents production of both thromboxane A~2~ and PGI~2~
  * As platelets **have no nucleus**, the COX inhibition remains for the entirety of the platelet lifespan
  * Endothelial cells will produce new COX within hours, and so its anti-inflammatory effects are temporary


### Adverse Effects

* **Asthma/Bronchospasm**\
Secondary to increased leukotriene synthesis due to increased arachidonic acid levels. Occurs in 20% of asthmatics with NSAID use.

* **Platelet dysfunction**\
A consequence of COX-1 inhibition only, and may result in increased perioperative bleeding risk (though decreased AMI and CVA risk).

* **Thrombotic events**, including MI and CVA\
Risk is greater with **COX-2** inhibitors, due to **selective inhibition of prostacyclin**. with NNH for non-fatal MI being 500 patient-years, and NNH for fatal MI being 1000 patient-years.

* **Impaired GFR**\
Occurs as a consequence of uninhibited afferent arteriolar constriction. Worse with concurrent hypovolaemia, renal artery stenosis, or concurrent ACE-I use.

* **Gastric erosion**\
A consequence of impaired mucosal secretion through COX-1 inhibition. This can result in pain, anaemia, or fatal bleed. In general, risk of gastric erosion is (from highest to lowest risk):
  * Ketorolac
  * Diclofenac/naproxen
  * Ibuprofen (<1.2g/day)
  * COX-2 Inhibitors


* **Transaminitis** may occur following NSAID use

```{r}
source("scripts/drugtables.R")

DrugTable("aspirin", "diclofenac", "ketorolac", "ibuprofen", "celecoxib", "parecoxib", caption = "Comparison of COX Inhibitors")
```


***

## References

Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
