# Opioids

Key definitions:

* **Opiates** are all naturally-occurring substances with morphine-like properties
* **Opioids** is a general term for substances with an affinity for opioid receptors
* **Opium** is a mixture of alkaloids from the poppy plant

## Classification of Opioids

* **Naturally occurring**\
    * Endogenous opioids
        * Endorphins
        * Enkephalins
        * Dynorphins
    * Opium derivatives
    * Phenanthrenes
        * Morphine
        * Codeine
* **Semisynthetic**\
Simple modifications to morphine.
    * Diacetylmorphine
    * Buprenorphine
    * Oxycodone
* **Synthetic**
    * Phenylpiperidines
        * Fentanyl
        * Alfentanil
        * Remifentanil
        * Pethidine
    * Diphenylpropylamines
        * Methadone

## Opioid Receptor Classification

All opioid receptors are Gi receptors. Activation:

* Inhibits adenylyl cyclase, reducing cAMP
    * Pre-synaptically inhibits voltage-gated Ca^2+^ channels
        * Decreases Ca^2+^ influx
        * Reduces neurotransmitter release
    * Post-synaptically stimulates activates K^+^ channels
        * Causes K^+^ efflux
        * Leads to membrane hyperpolarisation

|Receptor|Actions|Notable Properties
|--|--|
|MOP|Analgesia (spinal and brain), euphoria, meiosis (via stimulation of the Edinger-Westphal nucleus), nausea and vomiting (via CTZ), sedation, bradycardia, inhibition of gut motility, urinary retention, physical dependence|Only opioid receptor to cause nausea/vomiting
|KOP|Analgesia (predominantly spinal), sedation, meiosis, dysphoria|Less respiratory depression
|DOP|Analgesia, respiratory depression, urinary retention, physical dependence|Minimal constipation
|NOP|Anxiety, depression, change in appetite|Hyperalgesia at low doses, analgesic at high doses

Mechanism of effects:

* **Respiratory depression**\
Decreases central chemoreceptor sensitivity to CO~2~.
* **Constipation**\
Stimulation of opioid receptors in the gut.
    * Normally activated by local endogenous opioids (used as neurotransmitters)
    * Agonism of these receptors (µ, k, and to a smaller extent, δ) reduces GIT secretions and peristalsis

---

## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
2. Katzung BG, Trevor AJ. Basic and Clinical Pharmacology. 13th Ed. McGraw-Hill Education Europe. 2015.
3. Petkov V. Essential Pharmacology For The ANZCA Primary Examination. Vesselin Petkov. 2012.