# Tramadol


Tramadol is an analgesic agent with a complicated mechanism of action:

* Action at all opioid receptors, but particularly MOP, causing analgesia as well as nausea and vomiting
* Inhibits 5-HT reuptake which provides descending inhibitory analgesia 
* Inhibits NA reuptake descending inhibitory analgesia
* NMDA receptor antagonist

| Properties | Tramadol |
| -- | -- |
| **Class** | Cyclohexanol derivative. Racemic mixture of (+)Tramadol which has greater MOP and 5HT reuptake effects, and (-)Tramadol, which mediates NA reuptake inhibition|
| **Uses** | Analgesia |
|**Presentation**| Racemic mixture - each isomer has complementary effects. IV solution is clear at 50mg.ml^-1^|
| **Route of Administration** | PO/IV/Topical |
| **Dosing** | 50-100mg QID. Potency 1/5^th^ that of morphine. |
| **Absorption** | Bioavailability 70% |
|**Distribution**| V~D~ 4L.kg^-1^ |
|**Metabolism**|Hepatic to active and inactive metabolites|
|**Excretion** |Urinary of predominantly inactive metabolites, t~1/2~β 300 minutes|
|**Respiratory**|Minimal respiratory depression|
|**CVS**|Avoid concomitant MAO-I use given NA reuptake inhibition|
|**CNS**|Increased seizure risk in those with epilepsy or concurrent SSRI/SNRI/TCA use. Minimal addiction potential|
|**GIT**|N/V|

---
## References

1. Peck TE, Hill SA. Pharmacology for Anaesthesia and Intensive Care. 4th Ed. Cambridge University Press. 2014.\
