# Hormones


A **hormone** is a chemical messenger produced by a **ductless gland** which has its action at a distant target cell via a specific receptor. Hormones can be classified by composition into:


* **Lipid hormones**\
Further divided into:
    * **Steroids**\
    Steroids are synthesised from cholesterol, and are released as they are produced (they are not stored). They are highly lipid soluble and act on cytoplasmic and intra-nucleic receptors.
        * Aldosterone
        * Testosterone
        * Oestrogen
        * Cortisol
    * **Eicosanoids**\
    Eicosanoids are formed from cell membrane phospholipid.
        * Prostaglandins
        * Thromboxanes
        * Leukotrienes
* **Peptide hormones**\
Peptide hormones are store in granules and released by exocytosis. Further divided into:
    * **Short-chain**
        * Insulin
        * ADH
        * Oxytocin
        * ACTH
    * **Long-chain**\
        * GH
        * Prolactin
    * **Glycopeptides**\
    Proteins with carbohydrate groups.
        * LH
        * FSH
        * TSH
* **Monoamine derivatives**\
Derived from a single amino acid. Further divided into:
    * Serotonin
    * Thyroxine
    * Catecholamines\
    Stored in granules and act at membrane receptors.
        * Adrenaline
        * Noradrenaline

---

## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
