# Hypothalamus and Pituitary


> Describe the control, secretions and functions of the pituitary and the hypothalamus

## Hypothalamus


The hypothalamus is a circumventricular organ that regulates a large number of autonomic processes:

* **Thermoregulatory**\
Integrates thermoreceptor input and controls activity of heat loss and heat gain mechanisms.
* **Satiety**\
Feelings of hunger are modulated by glucose, CCK, glucagon, and leptin.
* **Water balance**\
    * Contains osmoreceptors which control ADH release from the posterior pituitary
    * Angiotensin II stimulates thirst and ADH release via the subfornical organ and organum vasculosum
* **Circadian rhythms**\
Balance between anterior and posterior hypothalamic stimulation controls sleep-wake cycle.
* **Pituitary control** 
    * Anterior pituitary by hormone secretion into the long portal vein. Secreted hormones include:
        * GnRH, stimulates FSH and LH release
        * CRH, stimulates ACTH release
        * GHRH, stimulates GH release
        * TRH, stimulates TSH release
        * Somatostatin, inhibits GH and TSH release
        * Dopamine, inhibits prolactin release
    * Posterior pituitary by neuronal innervation
* **Behaviour**\
Punishment and reward centres.
* **Sexual function**

## Pituitary

The **hypothalamic-pituitary axis** describes the complex feedback loops between these endocrine organs:

* **Short-loop feedback** describes negative feedback from the pituitary on the hypothalamus, e.g. GH inhibiting GHRH release
* **Long-loop feedback** describes negative feedback from a pituitary target gland (i.e. thyroid, adrenal, gonads) on the hypothalamus, e.g. cortisol inhibiting CRH (as well as ACTH) release.
    * These axes are also named with target gland, e.g. hypothalamic-pituitary-adrenal axis

### Pituitary Hormones{#pit}

The pituitary gland secretes **eight hormones** from **two lobes**:

* **Anterior Pituitary**\
Secretes **six** hormones in response to hypothalamic endocrine stimulus. These are classified as:
    * **Stimulating** hormones, which act at another gland:
        * **ACTH**\
        Short-chain peptide that stimulates cortisol release from the zona fasciculata. Release is stimulated by CRH, and inhibited by cortisol.
        * **TSH**\
        Glycoprotein that stimulates synthesis and release of T~3~ and T~4~. Release is stimulated by TRH, and inhibited by T~3~.
        * **FSH**\
        Glycoprotein gonadotropin. Release is stimulated by GnRH, and inhibited by circulating sex steroids. Has different effects depending on sex:
            * Females: Stimulates oestrogen synthesis and ovarian follicle development.
            * Males: Stimulates sperm maturation.
        * **LH**\
        Glycoprotein gonadotropin with different effects depending on sex:\
            * Females: Rapid increase stimulates ovulation and corpus luteum development.
            * Males: Stimulates testosterone synthesis.
    * **Direct acting** hormones:
        * **GH**\
        Long-chain peptide released in a pulsatile fashion. Release is stimulated by GHRH and is typically high with exercise, hypoglycaemia, and stress. Release is inhibited by somatostatin and IGF-1. GH has generally anabolic effects:
            * Directly stimulates lipolysis, increasing circulating FFA
            * Indirectly stimulates IGF-1 release, promoting cell growth and development
        * **Prolactin**\
        Long-chain peptide which promotes breast development during gestation, and lactation after delivery.


* **Posterior pituitary**\
Secretes **two** hormones:
    * **ADH**\
    Short-chain peptide which is:
        * Released in response to osmoreceptors in the circumventricular organs detecting a change in osmolality\
        ADH release is:
            * Reduced when osmolality is <275 mOsm.L^-1^
            * Increased when osmolality is >290 mOsm.L^-1^
        * Effective at:
            * V~1~ receptors in vascular smooth muscle, causing vasoconstriction
            * V~2~ receptors in kidney collecting ducts to increase water reabsorption, and on endothelium to increase vWF and factor VIII release
            * V~3~ receptors in the pituitary to stimulate ACTH release
    * **Oxytocin**\
    Short-chain peptide, structurally similar to ADH, which causes:
        * Uterine contraction
        * Let-down reflex\
        Stimulates milk release on suckling.
        * Psychological\
        Pair bonding.

---
## References

1. Chambers D, Huang C, Matthews G. Basic Physiology for Anaesthetists. Cambridge University Press. 2015.
2. Nickson, C. [Vasopressin](http://lifeinthefastlane.com/ccc/vasopressin/). LITFL.