# Thyroid

:::dual
Describe the control, secretions and functions of the thyroid.
:::

The thyroid gland:

* Produces and secretes two hormones in response to TSH:
  * T~4~ (thyroxine, 93%)
  * T~3~ (tri-iodothyronine, 7%)
* Secretions are controlled via a negative-feedback loop on the hypothalamic-pituitary-thyroid axis\
Increased TSH results in:
  * Increased iodine uptake
  * Increased iodination to form T~4~ and T~3~
  * Increased proteolysis of thyroglobulin, which releases T~4~ and T~3~
* Secretions are decreased with decreased iodine uptake
  * Perchlorate\
  Blocks Na^+^/I^-^ symporter.
  * Wolff-Chaikoff effect\
  A reduction in thyroid hormone production due to a high circulating [iodide].


## Synthesis

Thyroid hormones are:

:::column-margin
In brief:

* Iodide is taken into the thyroid follicles by secondary active transport, and oxidised to iodine
* Thyroglobulin is synthesised in the follicle, and excreted into the follicular cavity
* Iodine is secreted into the follicular cavity, where it combines with thyroglobulin to produce T~4~ and T~3~
:::

* **Synthesised** in **follicles**\
A follicle is formed of a single layer of cuboidal epithelium around a central lumen (follicular cavity) containing thyroglobulin.
  * **Iodide** is transported into follicular cells via a **secondary active transport** mechanism\
  Na^+^/I^-^ co-transporter.
  * Iodide is then **oxidised to iodine**
  * Thyroglobulin is synthesised in the endoplasmic reticulum of the follicular cell and excreted into the follicular cavity
  * Iodine is excreted into the follicular cavity using a chloride exchange pump
  * In the follicular cavity:
    * **Thyroid peroxidase** catalyses the iodination of thyroglobulin, forming mono-iodotyrosine and di-iodotyrosine
    * These are subsequently **oxidised**, forming T~3~ and T~4~ respectively


## Secretion and Metabolism

Thyroid hormones are:

* Secreted in vesicles via endocytosis into the surrounding capillaries
  * Colloid enters thyroid cell via pinocytosis at the apical membrane
  * Vesicles then fuse with lysosomes
  * Thyroid hormone cleaved from thyroglobulin by proteases
  * Free T~3~ and T~4~ diffuse through the base of the thyroid cell into surrounding capillaries
* Highly protein bound to albumin and thyroxine-binding globulin
  * T~4~ has a t~1/2~ of 7 days
  * T~3~ has a t~1/2~ of 24 hours
  * Both are deiodinated in the liver, kidney, and muscle
    * 55% of T~4~ will be first deiodinated to T~3~

## Physiological Effects

Thyroid hormones:

* Act on thyroid receptors in the **cell nucleus**\
Increasing gene transcription, protein synthesis, and mitochondria size and number. 
* **T~3~ is 3-5x more active than T~4~**

: Effects of Thyroid Hormone

+---------------+-------------------------------------------+
| System        | Effect                                    |
+===============+===========================================+
| **Resp**      | * ↑ MV due to ↑ CO~2~ production          |
+---------------+-------------------------------------------+
| **CVS**       | * ↑ HR                                    |
|               | * ↑ Inotropy                              |
|               | * ↑ CO                                    |
|               | * ↓ SVR                                   |
+---------------+-------------------------------------------+
| **CNS**       | * ↑ Excitability\                         |
|               | Seizures, tremor.                         |
+---------------+-------------------------------------------+
| **MSK**       | * ↑ Osteoblastic activity                 |
+---------------+-------------------------------------------+
| **GU**        | * Impotence (men)                         |
|               | * Oligomenorrhoea (women)                 |
+---------------+-------------------------------------------+
| **GIT**       | * ↑ GIT motility                          |
+---------------+-------------------------------------------+
| **Metabolic** | * ↑ BMR\                                  |
|               | Up to 100%.                               |
|               | * ↑ Carbohydrate metabolism               |
|               |     * ↑ Glucose uptake                    |
|               |     * ↑ Glycolysis                        |
|               |     * ↑ Gluconeogenesis                   |
|               | * ↑ Fat metabolism                        |
|               |     * ↑ Lipolysis                         |
|               |     * ↑ Non-shivering thermogenesis       |
|               |     * ↓ Plasma cholesterol                |
|               |     * ↓ Plasma phospholipids              |
|               |     * ↓ Triglycerides                     |
|               | * ↑ Protein metabolism                    |
|               |     * ↑ Anabolism at physiological levels |
|               |     * ↑ Catabolism at high levels         |
+---------------+-------------------------------------------+

:::column-margin
Effects of thyroid hormone are predominantly metabolic.
:::

---

## References

1. Kam P, Power I. Principles of Physiology for the Anaesthetist. 3rd Ed. Hodder Education. 2012.
2. CICM September/November 2008